import type { Metadata } from "next";
import { LegalPage, LegalSection, Fact } from "@/components/legal-page";
import { SITE } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "The terms under which the ZeroPage pilot is offered.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Use" sibling={{ href: "/privacy", label: "Privacy Policy" }}>
      <LegalSection n={1} title="Who we are">
        <p>
          {SITE.name} is operated by <Fact value={SITE.legalEntity} />, <Fact value={SITE.jurisdiction} />.
          Contact: <Fact value={SITE.contactEmail} />.
        </p>
      </LegalSection>

      <LegalSection n={2} title="The pilot">
        <p>
          {SITE.name} is in a pilot. Accounts are by invitation. Features can change, break, or be
          removed while we learn. We will tell you before anything you have made goes away, but we
          cannot promise uptime or that the service continues.
        </p>
      </LegalSection>

      <LegalSection n={3} title="Your account">
        <p>
          You sign in with Google, Discord, or an email and password. You are responsible for what
          happens under your account. Do not share it, and tell us if you think someone else has
          used it. One person per account unless we have set up a team for you.
        </p>
      </LegalSection>

      <LegalSection n={4} title="What you upload">
        <p>
          You keep ownership of everything you upload: references, footage, stills, text. You give
          us permission to store it and use it to do what you asked (research, keyframes, renders).
          You confirm you have the right to upload it. Do not upload other people&apos;s likenesses
          or work without their permission.
        </p>
      </LegalSection>

      <LegalSection n={5} title="What the studio makes">
        <p>
          Outputs (concepts, keyframes, renders) are yours to use, subject to the terms of the
          model provider that produced them. We claim no rights in your outputs and we do not use
          your uploads or outputs to train models. Outputs are generated by AI and can be wrong,
          strange, or resemble things they should not; check before you publish.
        </p>
      </LegalSection>

      <LegalSection n={6} title="Renders and allowances">
        <p>
          During the pilot, each account has a daily render allowance on the studio&apos;s provider
          keys. If you add your own provider keys, renders on those keys are billed by that
          provider to you, under their terms. Allowances can change with notice.
        </p>
      </LegalSection>

      <LegalSection n={7} title="Rules">
        <ul>
          <li>No content that is illegal, that sexualises minors, or that is meant to deceive people about a real person or event.</li>
          <li>No using someone&apos;s likeness or voice without their permission.</li>
          <li>No attempts to break, scrape, or overload the service.</li>
          <li>Follow the acceptable-use rules of the model providers we route to.</li>
        </ul>
        <p>We can suspend or close an account that breaks these rules.</p>
      </LegalSection>

      <LegalSection n={8} title="Third-party providers">
        <p>
          Renders and keyframes are produced by third parties, including Runway, fal.ai,
          Higgsfield, Google, and Midjourney. Your prompts and references are sent to them to do
          the work. Their terms apply to what they produce.
        </p>
      </LegalSection>

      <LegalSection n={9} title="No warranties, limited liability">
        <p>
          The service is provided as is. To the extent the law allows, we are not liable for
          indirect or consequential losses, and our total liability to you is limited to what you
          paid us in the twelve months before the claim (during the pilot, that is nothing).
        </p>
      </LegalSection>

      <LegalSection n={10} title="Ending things">
        <p>
          You can leave any time by emailing <Fact value={SITE.contactEmail} />; we will delete
          your account and data as described in the Privacy Policy. We can end the pilot or your
          access with reasonable notice.
        </p>
      </LegalSection>

      <LegalSection n={11} title="Changes and law">
        <p>
          If these terms change materially we will tell you by email or in the app. These terms
          are governed by the laws of <Fact value={SITE.governingLaw} />, and disputes go to the
          courts there.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
