"""
src/cut/moments.py -- what the index found in a clip, and search over it
(docs/CUT_EDITOR.md section 5.3).

Two OWNED tables (db.OWNED_TABLES):

- `media_index` -- one row per indexed file: which handle, the sha256 of
  the bytes it was indexed from, what was found, whether it worked.
  Staleness is checked on READ against that hash (the timeline.py /
  seed_hash pattern): a clip re-rendered under the same handle is a
  different file, and the old moments describe frames that no longer
  exist.
- `media_moments` -- one row per WORD, SEGMENT (a sentence of speech) or
  SHOT. Frames are at the index fps stored on media_index. Only segments
  and shots carry an embedding: a word is there for timing (cutting a
  silence, snapping a caption), never searched on its own.

The embeddings live beside the rows in the main database (pgvector, the
same 768-dim gemini-embedding-001 space as the RAG library, documents
embedded as RETRIEVAL_DOCUMENT and queries as RETRIEVAL_QUERY -- the model
is asymmetric). Not in rag_documents: a moment belongs to one account's
clip, the library is the shared brain.

`search` is hybrid: vector similarity over segments and shots, plus a
plain text match over everything (a word the transcript caught exactly,
a tag the shot log wrote), merged by reciprocal rank. With no embedding
key it degrades to the text half and says so.
"""
from __future__ import annotations

import json
from typing import Any, Optional

from .. import db
from . import doc as d

KINDS = ("word", "segment", "shot")
EMBEDDED_KINDS = ("segment", "shot")
RRF_K = 60

# `{vec}` is the vector type qualified by the schema the extension lives
# in. Supabase installs extensions in `extensions`, a plain Postgres in
# `public`, and a connection whose search_path is neither (every test
# schema) cannot see an unqualified `vector` at all -- so the type and its
# `<=>` operator are always named with their schema.
SCHEMA = """
CREATE TABLE IF NOT EXISTS media_index (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TEXT    NOT NULL,
    media       TEXT    NOT NULL,
    sha256      TEXT    NOT NULL,
    fps         INTEGER NOT NULL,
    frames      INTEGER NOT NULL,
    has_audio   BOOLEAN NOT NULL,
    speech      BOOLEAN,
    shots       INTEGER NOT NULL DEFAULT 0,
    words       INTEGER NOT NULL DEFAULT 0,
    status      TEXT    NOT NULL,
    notes       TEXT,
    account_id  BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS media_index_media
    ON media_index (media, account_id) NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS media_moments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media       TEXT    NOT NULL,
    sha256      TEXT    NOT NULL,
    kind        TEXT    NOT NULL,
    start_f     INTEGER NOT NULL,
    end_f       INTEGER NOT NULL,
    speaker     TEXT,
    text        TEXT    NOT NULL,
    tags        JSONB,
    embedding   {vec}(768),
    account_id  BIGINT
);
CREATE INDEX IF NOT EXISTS media_moments_media ON media_moments (account_id, media);
"""


def _vector_schema(conn) -> str:
    row = conn.execute("SELECT extnamespace::regnamespace::text AS s FROM pg_extension "
                       "WHERE extname = 'vector'").fetchone()
    if row is None:
        conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
        row = conn.execute("SELECT extnamespace::regnamespace::text AS s FROM pg_extension "
                           "WHERE extname = 'vector'").fetchone()
    return row["s"]


def init(dsn: Optional[str] = None) -> None:
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA.format(vec=f"{_vector_schema(conn)}.vector"))
        for table in ("media_index", "media_moments"):
            db.own_table(conn, table)


def _vec(values) -> Optional[str]:
    if values is None:
        return None
    return "[" + ",".join(f"{float(x):.7g}" for x in values) + "]"


def indexed(media: str, *, account_id: Optional[int],
            dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    with db.connect(dsn) as conn:
        if not db.table_exists(conn, "media_index"):
            return None
        row = conn.execute(
            "SELECT * FROM media_index WHERE media = %s AND account_id IS NOT DISTINCT FROM %s",
            (media, account_id)).fetchone()
    return dict(row) if row else None


def is_current(media: str, sha256: str, *, account_id: Optional[int],
               dsn: Optional[str] = None) -> bool:
    row = indexed(media, account_id=account_id, dsn=dsn)
    return bool(row) and row["sha256"] == sha256 and row["status"] == "done"


def write(media: str, sha256: str, *, account_id: Optional[int], fps: int, frames: int,
          has_audio: bool, speech: Optional[bool], moments: list[dict],
          status: str = "done", notes: Optional[str] = None,
          dsn: Optional[str] = None) -> dict[str, Any]:
    """Replace everything known about one file, in one transaction: an
    index is either the whole of what one pass found or nothing."""
    for m in moments:
        if m["kind"] not in KINDS:
            raise ValueError(f"moment kind must be one of {KINDS}")
    now = db._now()
    with db.connect(dsn) as conn:
        vs = _vector_schema(conn)
        conn.execute("DELETE FROM media_moments WHERE media = %s "
                     "AND account_id IS NOT DISTINCT FROM %s", (media, account_id))
        for m in moments:
            conn.execute(
                "INSERT INTO media_moments (media, sha256, kind, start_f, end_f, speaker, text, "
                "tags, embedding, account_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s::jsonb, "
                f"%s::{vs}.vector, %s)",
                (media, sha256, m["kind"], int(m["start_f"]), int(m["end_f"]), m.get("speaker"),
                 m["text"], json.dumps(m.get("tags")) if m.get("tags") is not None else None,
                 _vec(m.get("embedding")), account_id))
        row = conn.execute(
            "INSERT INTO media_index (created_at, media, sha256, fps, frames, has_audio, speech, "
            "shots, words, status, notes, account_id) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (media, account_id) DO UPDATE SET created_at = excluded.created_at, "
            "sha256 = excluded.sha256, fps = excluded.fps, frames = excluded.frames, "
            "has_audio = excluded.has_audio, speech = excluded.speech, shots = excluded.shots, "
            "words = excluded.words, status = excluded.status, notes = excluded.notes "
            "RETURNING *",
            (now, media, sha256, fps, frames, has_audio, speech,
             sum(1 for m in moments if m["kind"] == "shot"),
             sum(1 for m in moments if m["kind"] == "word"), status, notes,
             account_id)).fetchone()
    return dict(row)


def moments_for(media: str, *, account_id: Optional[int], kind: Optional[str] = None,
                dsn: Optional[str] = None) -> list[dict[str, Any]]:
    with db.connect(dsn) as conn:
        rows = conn.execute(
            "SELECT id, media, kind, start_f, end_f, speaker, text, tags FROM media_moments "
            "WHERE media = %s AND account_id IS NOT DISTINCT FROM %s "
            "AND (%s::text IS NULL OR kind = %s) ORDER BY start_f, id",
            (media, account_id, kind, kind)).fetchall()
    return [dict(r) for r in rows]


# --------------------------------------------------------------------------
# search
# --------------------------------------------------------------------------

def _terms(q: str) -> list[str]:
    return [t for t in (w.strip(".,!?;:\"'()").lower() for w in (q or "").split()) if len(t) >= 3]


def search(q: str, *, account_id: Optional[int], k: int = 10, query_vector=None,
           dsn: Optional[str] = None) -> dict[str, Any]:
    """{"results": [...], "notes": [...]} for a plain-words query.

    `query_vector` is the query's RETRIEVAL_QUERY embedding (the caller
    embeds, so this module never needs a Gemini client -- the rag.py
    edge/generator split). None runs the text half alone."""
    q = (q or "").strip()
    if not q:
        return {"results": [], "notes": ["an empty search finds nothing"]}
    k = max(1, min(int(k), 50))
    notes: list[str] = []
    ranked: dict[int, dict] = {}
    with db.connect(dsn) as conn:
        if not db.table_exists(conn, "media_moments"):
            return {"results": [], "notes": ["nothing has been indexed yet"]}
        if query_vector is not None:
            vs = _vector_schema(conn)
            near = f"embedding OPERATOR({vs}.<=>) %s::{vs}.vector"
            rows = conn.execute(
                "SELECT id, media, kind, start_f, end_f, speaker, text, tags, "
                f"1 - ({near}) AS similarity FROM media_moments "
                "WHERE account_id IS NOT DISTINCT FROM %s AND embedding IS NOT NULL "
                f"ORDER BY {near} LIMIT %s",
                (_vec(query_vector), account_id, _vec(query_vector), k * 3)).fetchall()
            for rank, r in enumerate(rows):
                hit = ranked.setdefault(r["id"], {**dict(r), "score": 0.0, "matched": []})
                hit["score"] += 1.0 / (RRF_K + rank)
                hit["matched"].append("meaning")
        else:
            notes.append("searched the words only -- no embedding key, so meaning was not used")
        terms = _terms(q) or [q.lower()]
        like = [f"%{t}%" for t in terms]
        rows = conn.execute(
            "SELECT id, media, kind, start_f, end_f, speaker, text, tags FROM media_moments "
            "WHERE account_id IS NOT DISTINCT FROM %s AND ("
            + " OR ".join(["(lower(text) LIKE %s OR lower(COALESCE(tags::text, '')) LIKE %s)"]
                          * len(like))
            + ") LIMIT %s",
            (account_id, *[x for pat in like for x in (pat, pat)], k * 6)).fetchall()
        # more terms matched ranks higher; an exact word (a word row) is the
        # most specific answer a text match can give
        def weight(r):
            text = f"{r['text']} {json.dumps(r['tags'] or '')}".lower()
            return (sum(t in text for t in terms), r["kind"] == "word")
        for rank, r in enumerate(sorted(rows, key=weight, reverse=True)):
            hit = ranked.setdefault(r["id"], {**dict(r), "score": 0.0, "matched": []})
            hit["score"] += 1.0 / (RRF_K + rank)
            hit["matched"].append("words")
        fps_rows = conn.execute(
            "SELECT media, fps FROM media_index WHERE account_id IS NOT DISTINCT FROM %s",
            (account_id,)).fetchall()
    fps = {r["media"]: r["fps"] for r in fps_rows}
    hits = sorted(ranked.values(), key=lambda h: h["score"], reverse=True)[:k]
    for h in hits:
        f = fps.get(h["media"]) or d.DEFAULT_FPS
        h["start_s"] = round(h["start_f"] / f, 2)
        h["end_s"] = round(h["end_f"] / f, 2)
        h["score"] = round(h["score"], 5)
        h.pop("similarity", None)
    return {"results": hits, "notes": notes}
