"""
src/cut/store.py -- where timelines live (docs/CUT_EDITOR.md section 5.1).

Three OWNED tables (db.OWNED_TABLES):

- `timelines` -- one row per VERSION of a project's cut, and a version's
  `doc` is never updated. Every edit is a new row whose `parent_id` is the
  version it was made from, so a branch is two children of one parent and
  session replay is walking the chain. The one column written after the
  insert is `export_url`: the MP4 is a derived artifact of that exact,
  frozen doc, not a change to it.
- `timeline_heads` -- the pointer. Undo and rollback MOVE it to an older
  version; nothing is deleted, the director_canvas rule that expensive
  work is never thrown away.
- `cut_media` -- what an `asset:<id>` handle names: an uploaded music bed
  or voiceover. `gen:<id>` names a generated_assets row and needs nothing
  here.

`project_id` is TEXT and namespaced. In v0 a project IS a concept
(`concept:<id>`), because a concept is the unit that has approved clips;
a creative_projects id can live in the same column later without a
migration.

Every function takes `account_id` keyword-only with no default -- the
preprod.get_concept rule: a forgotten owner is a TypeError at the call,
not a leak. Someone else's timeline is indistinguishable from a missing
one.
"""
from __future__ import annotations

import json
from typing import Any, Optional

from .. import db
from . import validate as v

SCHEMA = """
CREATE TABLE IF NOT EXISTS timelines (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TEXT    NOT NULL,
    project_id  TEXT    NOT NULL,
    version     INTEGER NOT NULL,
    parent_id   BIGINT  REFERENCES timelines(id),
    doc         JSONB   NOT NULL,
    author      TEXT    NOT NULL,
    op_summary  TEXT    NOT NULL,
    export_url  TEXT,
    account_id  BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS timelines_project_version
    ON timelines (project_id, account_id, version) NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS timeline_heads (
    project_id  TEXT    NOT NULL,
    timeline_id BIGINT  NOT NULL REFERENCES timelines(id),
    updated_at  TEXT    NOT NULL,
    account_id  BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS timeline_heads_project
    ON timeline_heads (project_id, account_id) NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS cut_media (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TEXT    NOT NULL,
    kind        TEXT    NOT NULL,
    filename    TEXT    NOT NULL,
    media_url   TEXT    NOT NULL,
    output_path TEXT,
    seconds     DOUBLE PRECISION,
    sha256      TEXT,
    account_id  BIGINT
);
"""

AUTHORS = ("user", "agent", "assemble")
MEDIA_KINDS = ("audio",)


def init(dsn: Optional[str] = None) -> None:
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA)
        for table in ("timelines", "timeline_heads", "cut_media"):
            db.own_table(conn, table)


def project_for_concept(concept_id: int) -> str:
    return f"concept:{int(concept_id)}"


def _row(row) -> Optional[dict[str, Any]]:
    if not row:
        return None
    out = dict(row)
    if isinstance(out.get("doc"), str):
        out["doc"] = json.loads(out["doc"])
    return out


def save_version(project_id: str, doc: dict, *, account_id: Optional[int],
                 author: str, op_summary: str, parent_id: Optional[int] = None,
                 dsn: Optional[str] = None) -> dict[str, Any]:
    """Append one version and point the head at it. The doc is validated
    for STRUCTURE here (its media was checked by whoever built it, since
    that needs the files) -- a malformed doc never reaches the table, from
    any writer. `parent_id` defaults to the current head."""
    if author not in AUTHORS:
        raise ValueError(f"author must be one of {AUTHORS}")
    v.validate(doc)
    now = db._now()
    with db.connect(dsn) as conn:
        if parent_id is None:
            head = conn.execute(
                "SELECT timeline_id FROM timeline_heads WHERE project_id = %s "
                "AND account_id IS NOT DISTINCT FROM %s", (project_id, account_id)).fetchone()
            parent_id = head["timeline_id"] if head else None
        elif not conn.execute(
                "SELECT 1 FROM timelines WHERE id = %s AND project_id = %s "
                "AND account_id IS NOT DISTINCT FROM %s",
                (parent_id, project_id, account_id)).fetchone():
            raise ValueError(f"no version {parent_id} of {project_id}")
        last = conn.execute(
            "SELECT COALESCE(MAX(version), 0) AS v FROM timelines WHERE project_id = %s "
            "AND account_id IS NOT DISTINCT FROM %s", (project_id, account_id)).fetchone()
        row = conn.execute(
            "INSERT INTO timelines (created_at, project_id, version, parent_id, doc, "
            "author, op_summary, account_id) VALUES (%s, %s, %s, %s, %s::jsonb, %s, %s, %s) "
            "RETURNING *",
            (now, project_id, int(last["v"]) + 1, parent_id, json.dumps(doc),
             author, op_summary, account_id)).fetchone()
        _point(conn, project_id, row["id"], account_id, now)
    return _row(row)


def _point(conn, project_id: str, timeline_id: int, account_id: Optional[int], now: str) -> None:
    conn.execute(
        "INSERT INTO timeline_heads (project_id, timeline_id, updated_at, account_id) "
        "VALUES (%s, %s, %s, %s) ON CONFLICT (project_id, account_id) "
        "DO UPDATE SET timeline_id = excluded.timeline_id, updated_at = excluded.updated_at",
        (project_id, timeline_id, now, account_id))


def head(project_id: str, *, account_id: Optional[int],
         dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    with db.connect(dsn) as conn:
        return _row(conn.execute(
            "SELECT t.* FROM timeline_heads h JOIN timelines t ON t.id = h.timeline_id "
            "WHERE h.project_id = %s AND h.account_id IS NOT DISTINCT FROM %s "
            "AND t.account_id IS NOT DISTINCT FROM %s",
            (project_id, account_id, account_id)).fetchone())


def get(timeline_id: int, *, account_id: Optional[int],
        dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    with db.connect(dsn) as conn:
        return _row(conn.execute(
            "SELECT * FROM timelines WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (timeline_id, account_id)).fetchone())


def history(project_id: str, *, account_id: Optional[int],
            dsn: Optional[str] = None) -> list[dict[str, Any]]:
    """Every version, newest first, without the docs (a card reads the
    chain; a doc is fetched when one is opened)."""
    with db.connect(dsn) as conn:
        return [dict(r) for r in conn.execute(
            "SELECT id, created_at, version, parent_id, author, op_summary, export_url "
            "FROM timelines WHERE project_id = %s AND account_id IS NOT DISTINCT FROM %s "
            "ORDER BY version DESC", (project_id, account_id)).fetchall()]


def rollback(project_id: str, timeline_id: int, *, account_id: Optional[int],
             dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    """Move the head to an earlier (or later) version of the SAME project.
    Nothing is deleted. None when that version is not this project's, or
    not this account's."""
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM timelines WHERE id = %s AND project_id = %s "
            "AND account_id IS NOT DISTINCT FROM %s",
            (timeline_id, project_id, account_id)).fetchone()
        if not row:
            return None
        _point(conn, project_id, row["id"], account_id, db._now())
    return _row(row)


def set_export(timeline_id: int, url: str, *, account_id: Optional[int],
               dsn: Optional[str] = None) -> None:
    with db.connect(dsn) as conn:
        conn.execute(
            "UPDATE timelines SET export_url = %s WHERE id = %s "
            "AND account_id IS NOT DISTINCT FROM %s", (url, timeline_id, account_id))


def latest_exports(project_ids: list[str], *, account_id: Optional[int],
                   dsn: Optional[str] = None) -> dict[str, dict[str, Any]]:
    """project_id -> the head version's {timeline_id, version, export_url},
    for a whole list of cards in one query."""
    if not project_ids:
        return {}
    with db.connect(dsn) as conn:
        if not db.table_exists(conn, "timeline_heads"):
            return {}
        rows = conn.execute(
            "SELECT h.project_id, t.id AS timeline_id, t.version, t.export_url "
            "FROM timeline_heads h JOIN timelines t ON t.id = h.timeline_id "
            "WHERE h.project_id = ANY(%s) AND h.account_id IS NOT DISTINCT FROM %s "
            "AND t.account_id IS NOT DISTINCT FROM %s",
            (list(project_ids), account_id, account_id)).fetchall()
    return {r["project_id"]: dict(r) for r in rows}


# --------------------------------------------------------------------------
# cut_media -- what an asset:<id> handle names
# --------------------------------------------------------------------------

def add_media(*, account_id: Optional[int], kind: str, filename: str, media_url: str,
              output_path: Optional[str], seconds: Optional[float],
              sha256: Optional[str], dsn: Optional[str] = None) -> dict[str, Any]:
    if kind not in MEDIA_KINDS:
        raise ValueError(f"kind must be one of {MEDIA_KINDS}")
    with db.connect(dsn) as conn:
        return dict(conn.execute(
            "INSERT INTO cut_media (created_at, kind, filename, media_url, output_path, "
            "seconds, sha256, account_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING *",
            (db._now(), kind, filename, media_url, output_path, seconds, sha256,
             account_id)).fetchone())


def get_media(media_id: int, *, account_id: Optional[int],
              dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM cut_media WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (media_id, account_id)).fetchone()
    return dict(row) if row else None
