#!/usr/bin/env python3
"""
Users, accounts, membership -- the real login's spine, on Supabase Auth.

Identity is Supabase's (2026-09-03, step 6 of
docs/tasks/task-postgres-migration.md, Mike's call): `auth.users` in the
Supabase project owns who a person is, how they prove it (Google,
Discord, email+password) and their password. This module keeps what
Supabase cannot know -- which of OUR accounts a person may enter:

- `users`           a PROFILE MIRROR of auth.users, keyed by the same
                    UUID, holding email / display_name / avatar_url. No
                    password_hash, no identities: those left with the
                    hand-rolled OAuth. No FOREIGN KEY into auth.users
                    either -- the `auth` schema is Supabase's, and the
                    throwaway Postgres the tests run on has no such
                    schema; the writer (`claim`) enforces the link.
- `accounts`        a brand (zeropage / antihero -- what the hardcoded
                    BRANDS tuple grows up into), and the tenant.
- `account_members` who may enter which account.

The gate that matters lives in the shape of this data: a fresh sign-in
gets a users row and ZERO account_members rows. Membership is granted
by an existing member (`invite`) -- or, since 2026-09-24 and while
`open_signup()` is on (the default), by `provision_personal`, which
gives a brand-new sign-in its OWN empty workspace. It never adds anyone
to an existing account. `ZEROPAGE_OPEN_SIGNUP=0` restores invite-only.

**The invite still works before the person has ever visited.** An
invite creates a users row by EMAIL with a locally minted placeholder
id and `claimed_at` NULL. The first Supabase sign-in with that email
(`claim`) rewrites the row's id to the real auth.users UUID -- the FK on
account_members says ON UPDATE CASCADE, so the membership follows --
and stamps claimed_at. So there is no secret to send anyone.

Extends db.py in its own module (own SCHEMA, own init()), the
preprod.py pattern. Every function takes `dsn` (None = DATABASE_URL).
"""
from __future__ import annotations

import argparse
import sys
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from .db import (
    OWNED_TABLES,
    add_billing_columns,
    add_manual_lane_operator_column,
    add_prompt_edits_teach_column,
    backfill_owner,
    columns,
    connect,
    table_exists,
)

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    -- auth.users.id once claimed; a placeholder uuid4 for an invited
    -- person who has not signed in yet (claimed_at IS NULL)
    id            TEXT PRIMARY KEY,
    created_at    TEXT NOT NULL,
    email         TEXT NOT NULL UNIQUE,
    display_name  TEXT,
    avatar_url    TEXT,
    claimed_at    TEXT
);

CREATE TABLE IF NOT EXISTS accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TEXT NOT NULL,
    slug           TEXT NOT NULL UNIQUE,
    display_name   TEXT NOT NULL,
    accent_color   TEXT,
    voice          TEXT,
    house_look     TEXT,
    house_negative TEXT,
    house_aspect   TEXT DEFAULT '9:16',
    never_list     TEXT,
    -- may this account spend the OPERATOR'S personal consumer plans
    -- (src/manual_lane.py)? FALSE for every account that has ever been
    -- created, including the bootstrap one: the lane fails closed and
    -- the only way in is somebody turning it on by hand. db.py carries
    -- the ALTER for databases that predate the column.
    manual_lane_operator BOOLEAN NOT NULL DEFAULT FALSE,
    -- billing (docs/tasks/task-stripe-billing.md, 2026-09-18): does this
    -- account render without being charged (the operator's own, by
    -- hand, same fail-closed shape as the lane); which Stripe customer
    -- pays for it; which plan its subscription bought (pricing.PLANS
    -- keys; NULL is no subscription, never a default).
    credit_exempt      BOOLEAN NOT NULL DEFAULT FALSE,
    stripe_customer_id TEXT,
    plan               TEXT,
    -- may a hand edit of this account's scene prompts teach the RAG
    -- shelves (src/edit_teach.py)? Same posture: FALSE until turned on.
    prompt_edits_teach BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS account_members (
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    user_id    TEXT   NOT NULL REFERENCES users(id) ON UPDATE CASCADE,
    role       TEXT   NOT NULL DEFAULT 'owner',
    PRIMARY KEY (account_id, user_id)
);
"""


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")


def init(dsn: Optional[str] = None) -> None:
    """Create the auth tables. Run after db.init_db()."""
    with connect(dsn) as conn:
        conn.execute(SCHEMA)
        # a live database predates manual_lane_operator (2026-09-08); the
        # CREATE TABLE above carries it for a fresh one, and db.init_db
        # runs before this table exists at all, so the ALTER is asked for
        # here as well as there -- both are no-ops once it has landed.
        add_manual_lane_operator_column(conn)
        add_billing_columns(conn)
        add_prompt_edits_teach_column(conn)


# --------------------------------------------------------------------------
# users -- the mirror
# --------------------------------------------------------------------------

def create_user(email: str, display_name: Optional[str] = None,
                avatar_url: Optional[str] = None, *,
                user_id: Optional[str] = None, claimed: bool = False,
                dsn: Optional[str] = None) -> str:
    """One person's mirror row. `user_id` is the auth.users UUID when the
    row is written from a sign-in (claimed=True); an invite passes
    neither and gets a placeholder that `claim` rewrites later. Raises
    psycopg.errors.UniqueViolation on a duplicate email -- never
    silently merged."""
    email = email.strip().lower()
    user_id = user_id or str(uuid.uuid4())
    with connect(dsn) as conn:
        row = conn.execute(
            "INSERT INTO users (id, created_at, email, display_name, avatar_url, "
            "claimed_at) VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
            (user_id, _now(), email, display_name, avatar_url,
             _now() if claimed else None),
        ).fetchone()
        return str(row["id"])


def get_user(user_id: str, dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    with connect(dsn) as conn:
        row = conn.execute("SELECT * FROM users WHERE id = %s", (str(user_id),)).fetchone()
        return dict(row) if row else None


def get_user_by_email(email: str, dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM users WHERE email = %s", (email.strip().lower(),)
        ).fetchone()
        return dict(row) if row else None


def update_profile(user_id: str, display_name: Optional[str] = None,
                   avatar_url: Optional[str] = None,
                   dsn: Optional[str] = None) -> None:
    """Fill profile fields from a provider sign-in without clobbering
    what's already there."""
    with connect(dsn) as conn:
        conn.execute(
            "UPDATE users SET display_name = COALESCE(display_name, %s), "
            "avatar_url = COALESCE(%s, avatar_url) WHERE id = %s",
            (display_name, avatar_url, str(user_id)),
        )


def claim(user_id: str, email: Optional[str], display_name: Optional[str] = None,
          avatar_url: Optional[str] = None, *,
          dsn: Optional[str] = None) -> tuple[Optional[str], Optional[str]]:
    """The identity-resolution ladder, run on every Supabase sign-in.
    Returns (user_id, error) -- exactly one is set.

      1. a mirror row with this UUID exists            -> sign in.
      2. the email matches an UNCLAIMED row (an invite,
         or the seeded bootstrap user)                 -> claim it: the
         row's id becomes this UUID (account_members follows through
         ON UPDATE CASCADE), claimed_at is stamped.
      3. the email matches a row claimed by a DIFFERENT
         UUID                                          -> refuse. Supabase
         keeps one auth user per email, so this only happens when an
         auth user was deleted and re-created; merging silently would
         hand the new person the old memberships.
      4. brand-new                                     -> new mirror row,
         zero memberships (the gate).

    `email` None is a clear failure, not a NULL users.email row: a
    provider that returned no verified address gets told so.
    """
    user_id = str(user_id)
    with connect(dsn) as conn:
        if conn.execute("SELECT 1 FROM users WHERE id = %s", (user_id,)).fetchone():
            conn.execute(
                "UPDATE users SET display_name = COALESCE(display_name, %s), "
                "avatar_url = COALESCE(%s, avatar_url) WHERE id = %s",
                (display_name, avatar_url, user_id))
            return user_id, None
        if not email:
            return None, ("the provider did not return a verified email for this "
                          "account -- verify your email there and try again")
        email = email.strip().lower()
        row = conn.execute("SELECT id, claimed_at FROM users WHERE email = %s",
                           (email,)).fetchone()
        if row is not None and row["claimed_at"] is None:
            conn.execute(
                "UPDATE users SET id = %s, claimed_at = %s, "
                "display_name = COALESCE(display_name, %s), "
                "avatar_url = COALESCE(%s, avatar_url) WHERE id = %s",
                (user_id, _now(), display_name, avatar_url, row["id"]))
            return user_id, None
        if row is not None:
            return None, ("an account with this email already exists -- sign in "
                          "the way you first signed up")
        conn.execute(
            "INSERT INTO users (id, created_at, email, display_name, avatar_url, "
            "claimed_at) VALUES (%s, %s, %s, %s, %s, %s)",
            (user_id, _now(), email, display_name, avatar_url, _now()))
        return user_id, None


# --------------------------------------------------------------------------
# accounts + membership
# --------------------------------------------------------------------------

def upsert_account(slug: str, display_name: str, accent_color: Optional[str] = None,
                   dsn: Optional[str] = None) -> int:
    with connect(dsn) as conn:
        row = conn.execute("SELECT id FROM accounts WHERE slug = %s", (slug,)).fetchone()
        if row:
            return int(row["id"])
        row = conn.execute(
            "INSERT INTO accounts (created_at, slug, display_name, accent_color) "
            "VALUES (%s, %s, %s, %s) RETURNING id",
            (_now(), slug, display_name, accent_color),
        ).fetchone()
        return int(row["id"])


def add_member(account_id: int, user_id: str, role: str = "owner",
               dsn: Optional[str] = None) -> None:
    with connect(dsn) as conn:
        conn.execute(
            "INSERT INTO account_members (account_id, user_id, role) "
            "VALUES (%s, %s, %s) ON CONFLICT (account_id, user_id) DO NOTHING",
            (account_id, str(user_id), role),
        )


def memberships(user_id: str, dsn: Optional[str] = None) -> list[dict[str, Any]]:
    """The accounts this user may enter. Empty list == signed in but no
    access -- the state the membership gate renders, fixed only by an
    invite or, at sign-in, by provision_personal (open sign-up)."""
    with connect(dsn) as conn:
        rows = conn.execute(
            "SELECT a.*, m.role FROM accounts a "
            "JOIN account_members m ON m.account_id = a.id "
            "WHERE m.user_id = %s ORDER BY a.slug",
            (str(user_id),),
        ).fetchall()
        return [dict(r) for r in rows]


# --------------------------------------------------------------------------
# the manual render lane's gate -- a column, not an environment
# --------------------------------------------------------------------------

def set_manual_lane_operator(slug: str, on: bool,
                             dsn: Optional[str] = None) -> dict[str, Any]:
    """Turn the manual render lane on or off for ONE account.

    The write half of src/manual_lane.py's gate, which is a column on
    this table and nothing else since 2026-09-08. It is here rather than
    in manual_lane.py because this module owns `accounts`, and it is a
    deliberate, auditable act with a person behind it: there is no route,
    no env var and no API -- somebody has to be able to reach the
    database and run `python -m src.accounts operator <slug> --on`.

    Idempotent, and it reports the BEFORE as well as the after, because
    "already on" and "just turned on" are different facts about an
    install and the operator should not have to guess which one happened.

    Raises ValueError for an unknown slug -- naming an account that does
    not exist must not read as success.
    """
    return _set_account_flag("manual_lane_operator", slug, on, dsn=dsn)


def _set_account_flag(column: str, slug: str, on: bool,
                      dsn: Optional[str] = None) -> dict[str, Any]:
    """Flip ONE boolean gate column on ONE account row, by slug. The
    shared body of set_manual_lane_operator and set_prompt_edits_teach;
    `column` is a literal from this module, never caller input."""
    init(dsn)
    slug = (slug or "").strip().lower()
    if not slug:
        raise ValueError("which account? -- pass the slug, e.g. zeropage")
    with connect(dsn) as conn:
        row = conn.execute(
            f"SELECT id, {column} FROM accounts WHERE slug = %s",
            (slug,)).fetchone()
        if row is None:
            known = [r["slug"] for r in conn.execute(
                "SELECT slug FROM accounts ORDER BY slug")]
            raise ValueError(
                f"no account {slug!r}" + (f" -- try one of {known}" if known else ""))
        was = bool(row[column])
        now = bool(on)
        if was != now:
            conn.execute(
                f"UPDATE accounts SET {column} = %s WHERE id = %s",
                (now, int(row["id"])))
        return {"slug": slug, "account_id": int(row["id"]),
                "was": was, "now": now, "changed": was != now}


def set_credit_exempt(slug: str, on: bool, dsn: Optional[str] = None) -> dict[str, Any]:
    """Turn the credit exemption on or off for ONE account -- the
    operator's own (docs/tasks/task-stripe-billing.md, phase 3).
    set_manual_lane_operator's shape exactly: a deliberate act with a
    person behind it, no route, no env var; idempotent; reports the
    BEFORE; an unknown slug is an error, never a silent success. The
    gate reads it in ONE place, ledger.hold_for_render."""
    init(dsn)
    slug = (slug or "").strip().lower()
    if not slug:
        raise ValueError("which account? -- pass the slug, e.g. zeropage")
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT id, credit_exempt FROM accounts WHERE slug = %s", (slug,)).fetchone()
        if row is None:
            known = [r["slug"] for r in conn.execute(
                "SELECT slug FROM accounts ORDER BY slug")]
            raise ValueError(
                f"no account {slug!r}" + (f" -- try one of {known}" if known else ""))
        was = bool(row["credit_exempt"])
        now = bool(on)
        if was != now:
            conn.execute("UPDATE accounts SET credit_exempt = %s WHERE id = %s",
                         (now, int(row["id"])))
        return {"slug": slug, "account_id": int(row["id"]),
                "was": was, "now": now, "changed": was != now}


def is_credit_exempt(account_id: Optional[int], dsn: Optional[str] = None) -> bool:
    """One row, asked for by id -- manual_lane_allowed's shape. `None` is
    never exempt; a missing table or column reads as not exempt, because
    the failure mode of this predicate must be "charged", never "free"."""
    if account_id is None:
        return False
    try:
        wanted = int(account_id)
    except (TypeError, ValueError):
        return False
    try:
        with connect(dsn) as conn:
            if not table_exists(conn, "accounts") or "credit_exempt" not in columns(conn, "accounts"):
                return False
            row = conn.execute(
                "SELECT credit_exempt FROM accounts WHERE id = %s", (wanted,)).fetchone()
    except Exception:
        return False
    return bool(row and row["credit_exempt"])


def credit_exempt_accounts(dsn: Optional[str] = None) -> list[dict[str, Any]]:
    """Every exempt account, for the CLI to print -- never for the gate."""
    with connect(dsn) as conn:
        if not table_exists(conn, "accounts") or "credit_exempt" not in columns(conn, "accounts"):
            return []
        rows = conn.execute(
            "SELECT id, slug FROM accounts WHERE credit_exempt ORDER BY slug").fetchall()
        return [{"account_id": int(r["id"]), "slug": r["slug"]} for r in rows]


# --------------------------------------------------------------------------
# billing identity -- which Stripe customer, which plan (app/billing.py)
# --------------------------------------------------------------------------

def plan_of(account_id: Optional[int], dsn: Optional[str] = None) -> Optional[str]:
    """The plan this account's subscription bought (a pricing.PLANS key),
    or None -- no subscription, or a row/table that predates the column.
    Read on the pricing path (pricing.tier_for), so it never raises."""
    if account_id is None:
        return None
    try:
        with connect(dsn) as conn:
            if not table_exists(conn, "accounts") or "plan" not in columns(conn, "accounts"):
                return None
            row = conn.execute("SELECT plan FROM accounts WHERE id = %s",
                               (int(account_id),)).fetchone()
    except Exception:
        return None
    return (row["plan"] or None) if row else None


def set_plan(account_id: int, plan: Optional[str], dsn: Optional[str] = None) -> None:
    """Record (or clear, with None) the plan a subscription bought. Called
    by the webhook only; raises like every ledger-adjacent write."""
    with connect(dsn) as conn:
        conn.execute("UPDATE accounts SET plan = %s WHERE id = %s", (plan, int(account_id)))


def stripe_customer_of(account_id: int, dsn: Optional[str] = None) -> Optional[str]:
    with connect(dsn) as conn:
        row = conn.execute("SELECT stripe_customer_id FROM accounts WHERE id = %s",
                           (int(account_id),)).fetchone()
    return (row["stripe_customer_id"] or None) if row else None


def set_stripe_customer(account_id: int, customer_id: str, dsn: Optional[str] = None) -> None:
    """Bind an account to the Stripe customer that pays for it. One
    customer per account and one account per customer (the partial
    unique index); rebinding to a different customer is refused, because
    a webhook for the old one would otherwise credit the wrong tenant."""
    customer_id = (customer_id or "").strip()
    if not customer_id:
        raise ValueError("a Stripe customer id is required")
    with connect(dsn) as conn:
        row = conn.execute("SELECT stripe_customer_id FROM accounts WHERE id = %s",
                           (int(account_id),)).fetchone()
        if row is None:
            raise ValueError(f"no account {account_id}")
        have = row["stripe_customer_id"]
        if have and have != customer_id:
            raise ValueError(f"account {account_id} already pays as {have}; "
                             f"refusing to rebind to {customer_id}")
        if not have:
            conn.execute("UPDATE accounts SET stripe_customer_id = %s WHERE id = %s",
                         (customer_id, int(account_id)))


def account_for_stripe_customer(customer_id: str, dsn: Optional[str] = None) -> Optional[int]:
    """The account a Stripe customer pays for, or None -- and None is
    what the webhook acks with a 200 and a log line, never a guess."""
    customer_id = (customer_id or "").strip()
    if not customer_id:
        return None
    with connect(dsn) as conn:
        if not table_exists(conn, "accounts") or "stripe_customer_id" not in columns(conn, "accounts"):
            return None
        row = conn.execute("SELECT id FROM accounts WHERE stripe_customer_id = %s",
                           (customer_id,)).fetchone()
    return int(row["id"]) if row else None


def set_prompt_edits_teach(slug: str, on: bool,
                           dsn: Optional[str] = None) -> dict[str, Any]:
    """Turn hand-edit teaching on or off for ONE account
    (src/edit_teach.py, 2026-09-18). Same contract as
    set_manual_lane_operator: idempotent, reports before and after,
    ValueError on an unknown slug, and no route or env var beside it --
    `python -m src.accounts edits-teach <slug> --on`."""
    return _set_account_flag("prompt_edits_teach", slug, on, dsn=dsn)


def prompt_edits_teachers(dsn: Optional[str] = None) -> list[dict[str, Any]]:
    """Every account whose hand edits teach, for the CLI to print. The
    gate itself asks about one id (edit_teach.allowed)."""
    with connect(dsn) as conn:
        if not table_exists(conn, "accounts"):
            return []
        rows = conn.execute(
            "SELECT id, slug FROM accounts WHERE prompt_edits_teach "
            "ORDER BY slug").fetchall()
        return [{"account_id": int(r["id"]), "slug": r["slug"]} for r in rows]


def manual_lane_operators(dsn: Optional[str] = None) -> list[dict[str, Any]]:
    """Every account the column names, for the CLI to print. The GATE
    does not read this -- it asks about one account id (see
    manual_lane.manual_lane_allowed), because a gate that builds a set
    is a gate that can be widened by anything that widens the set."""
    with connect(dsn) as conn:
        if not table_exists(conn, "accounts"):
            return []
        rows = conn.execute(
            "SELECT id, slug FROM accounts WHERE manual_lane_operator "
            "ORDER BY slug").fetchall()
        return [{"account_id": int(r["id"]), "slug": r["slug"]} for r in rows]


# --------------------------------------------------------------------------
# seed
# --------------------------------------------------------------------------

def seed(email: str, display_name: str = "Mike",
         dsn: Optional[str] = None) -> dict[str, Any]:
    """
    The once-only bootstrap: Mike's user, the two real accounts, and
    owner membership on both. Idempotent -- re-running finds instead of
    duplicating. The user row is UNCLAIMED until the first Supabase
    sign-in with that email (`claim`), which is what attaches the real
    identity; there is no password here -- Supabase holds those. Brand
    metadata (labels, accents) mirrors app.main's BRAND_META so the
    picker looks like the brand pill always has.
    """
    init(dsn)
    user = get_user_by_email(email, dsn=dsn)
    user_id = user["id"] if user else create_user(
        email, display_name=display_name, dsn=dsn)

    zeropage = upsert_account("zeropage", "Zero Page Films", "#8b5cf6", dsn=dsn)
    antihero = upsert_account("antihero", "ANTIHERO", "#d64550", dsn=dsn)
    add_member(zeropage, user_id, dsn=dsn)
    add_member(antihero, user_id, dsn=dsn)
    claimed = claim_unowned_rows(dsn=dsn)
    return {"user_id": user_id, "accounts": [zeropage, antihero],
            "claimed": claimed}


def claim_unowned_rows(account_id: Optional[int] = None,
                       dsn: Optional[str] = None) -> dict[str, int]:
    """Give every pre-tenancy row an owner. Returns {table: rows claimed}.

    Each module's own init() backfills too, but init() runs before there
    is an account to backfill *to* on a fresh database -- so seeding is
    the other end of that. Tables that do not exist yet are skipped
    rather than created: this claims ownership, it does not define
    schema.
    """
    claimed: dict[str, int] = {}
    with connect(dsn) as conn:
        for table in OWNED_TABLES:
            if not table_exists(conn, table):
                continue
            if "account_id" not in columns(conn, table):
                continue
            n = backfill_owner(conn, table, account_id)
            if n:
                claimed[table] = n
    return claimed


def slug_of(account_id: Optional[int], dsn: Optional[str] = None) -> Optional[str]:
    """The tenant's slug for an account id -- the label rag_documents.project
    carries (see src/rag.py). Never raises: None in, None out; a database
    with no accounts table (a fresh install, most test fixtures) is None
    too, which the library treats as "unlabelled", never as an error."""
    if account_id is None:
        return None
    try:
        with connect(dsn) as conn:
            if not table_exists(conn, "accounts"):
                return None
            row = conn.execute("SELECT slug FROM accounts WHERE id = %s",
                               (int(account_id),)).fetchone()
            return str(row["slug"]) if row else None
    except Exception:
        return None


def resolve_account(slug: Optional[str] = None,
                    dsn: Optional[str] = None) -> Optional[int]:
    """Turn a `--account <slug>` into an id, or fall back to the oldest
    account on the database.

    For ENTRY POINTS only -- CLIs, the nightly run, anything with no
    session behind it. Library functions take `account_id` as a required
    argument on purpose; a fallback buried in the data layer is the leak
    that rule exists to prevent. Here it is deliberate and in one place.

    Returns None on a database with no accounts -- including one where
    the table does not exist yet, which a fresh install genuinely is.
    The caller then operates on the unowned pool, which is exactly what
    such a database holds. Raising there instead would turn "nothing has
    been seeded" into a crash in every CLI and MCP tool, which is what
    it did until a full-suite run happened to schedule the mcp_server
    tests onto a worker with an unseeded database. (The table check is
    to_regclass on the connection's search_path, so a per-test schema
    and the real one look alike.)
    """
    with connect(dsn) as conn:
        if not table_exists(conn, "accounts"):
            if slug:
                raise ValueError(f"no account {slug!r} -- no accounts exist yet")
            return None
        if slug:
            row = conn.execute(
                "SELECT id FROM accounts WHERE slug = %s", (slug.strip().lower(),)
            ).fetchone()
            if row is None:
                known = [r["slug"] for r in conn.execute(
                    "SELECT slug FROM accounts ORDER BY slug")]
                raise ValueError(
                    f"no account {slug!r}" + (f" -- try one of {known}" if known else ""))
            return int(row["id"])
        row = conn.execute("SELECT MIN(id) AS id FROM accounts").fetchone()
        return int(row["id"]) if row and row["id"] is not None else None


def invite(email: str, slug: str, display_name: Optional[str] = None,
           role: str = "member", join_existing: bool = False,
           dsn: Optional[str] = None) -> dict[str, Any]:
    """Give one person their own account, and the membership to enter it.

    The v1 posture, made a command instead of a hand-written INSERT: a
    sign-in gets a users row and zero memberships, so access is only
    ever granted deliberately. This is that grant.

    **A pilot user gets their OWN account.** That is the whole point and
    it is the easy thing to get catastrophically wrong: adding someone to
    `zeropage` does not give them a workspace, it gives them Mike's --
    every concept, location and cast member on the board, because
    account_id is the ownership boundary. So an account that already owns
    rows is refused unless `join_existing` says otherwise, and the error
    counts what they would have been able to see.

    No identity is created on purpose: the row sits unclaimed until they
    sign in through Supabase with that exact email, and `claim` takes it
    over (the same path the bootstrap user takes). So the invite is
    complete before they have ever visited, and there is no secret to
    send them.

    Returns {"user_id", "account_id", "slug", "created_user",
    "created_account", "role"}.
    """
    email = email.strip().lower()
    if not email or "@" not in email:
        raise ValueError(f"that does not look like an email: {email!r}")
    slug = slug.strip().lower()
    if not slug:
        raise ValueError("an invite needs an account slug")

    with connect(dsn) as conn:
        existing = conn.execute(
            "SELECT id FROM accounts WHERE slug = %s", (slug,)).fetchone()
        if existing is not None and not join_existing:
            owned = 0
            for table in OWNED_TABLES:
                if not table_exists(conn, table):
                    continue
                if "account_id" not in columns(conn, table):
                    continue
                owned += conn.execute(
                    f"SELECT COUNT(*) FROM {table} WHERE account_id = %s",
                    (existing["id"],)).fetchone()[0]
            if owned:
                raise ValueError(
                    f"account {slug!r} already exists and owns {owned} rows -- "
                    f"inviting {email} into it would show them all of that. "
                    f"Give them their own slug, or pass join_existing=True "
                    f"(--join-existing) if sharing a workspace is what you mean.")

    created_account = existing is None
    account_id = upsert_account(slug, display_name or slug.title(), dsn=dsn)

    user = get_user_by_email(email, dsn=dsn)
    created_user = user is None
    user_id = user["id"] if user else create_user(email, dsn=dsn)

    add_member(account_id, user_id, role=role, dsn=dsn)
    return {"user_id": user_id, "account_id": account_id, "slug": slug,
            "created_user": created_user, "created_account": created_account,
            "role": role}



# --------------------------------------------------------------------------
# open sign-up -- a first sign-in gets its own workspace (2026-09-24)
# --------------------------------------------------------------------------

# Slugs a stranger's email must never turn into: the operator's own
# brands (taken anyway, but that should not be the only reason), the
# media layer's shared prefix, and names that read as the system.
RESERVED_SLUGS = frozenset({
    "zeropage", "antihero", "shared", "admin", "api", "www", "studio",
    "support", "billing", "system", "root", "none", "null",
})


def open_signup() -> bool:
    """Does a brand-new sign-in get its own workspace?

    What InVideo and LTX Studio do (2026-09-24, Mike's call): one door,
    and walking through it the first time IS signing up -- you land in
    your own empty studio, not on a page saying you have no access.
    `ZEROPAGE_OPEN_SIGNUP=0` puts the invite-only gate back exactly as
    it was: a fresh sign-in gets a mirror row and zero memberships.
    Anything but an explicit off value reads as on, because on is the
    shipped posture."""
    import os
    return os.environ.get("ZEROPAGE_OPEN_SIGNUP", "1").strip().lower() not in (
        "0", "false", "off", "no")


def _slug_base(email: Optional[str], display_name: Optional[str]) -> str:
    import re
    raw = (email or "").split("@")[0] or (display_name or "")
    base = re.sub(r"[^a-z0-9]+", "-", raw.lower()).strip("-")[:24].strip("-")
    if len(base) < 3 or base in RESERVED_SLUGS:
        base = f"studio-{base}" if base else "studio"
    return base


def _workspace_name(email: Optional[str], display_name: Optional[str]) -> str:
    first = (display_name or "").strip().split(" ")[0]
    if not first:
        first = (email or "").split("@")[0]
    return f"{first}'s studio" if first else "My studio"


def provision_personal(user_id: str, email: Optional[str] = None,
                       display_name: Optional[str] = None, *,
                       dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    """Give a signed-in person with NO membership their own account.

    Returns {"account_id", "slug", "created": True} when one was made,
    None when they already belong somewhere (every sign-in after the
    first, every invited pilot, Mike) or open sign-up is off.

    **Their OWN account, never an existing one** -- invite()'s rule, for
    the same reason: account_id is the tenancy boundary, so joining an
    existing slug would hand a stranger somebody's whole board. The slug
    comes from the email's local part and takes a numeric suffix when
    taken; it never reuses a row.

    Idempotent and race-safe: the check and the insert run under a
    per-user advisory lock in one transaction, so two tabs finishing
    sign-in at once make one workspace, not two.

    Nothing is switched on here: the account starts at zero credits, not
    exempt, not an operator, not teaching -- every flag on `accounts`
    fails closed and stays that way. `grant_signup_credits` is the
    separate, optional welcome grant."""
    if not open_signup():
        return None
    user_id = str(user_id)
    with connect(dsn) as conn:
        conn.execute("SELECT pg_advisory_xact_lock(hashtext(%s))",
                     ("zp-provision:" + user_id,))
        if conn.execute("SELECT 1 FROM users WHERE id = %s",
                        (user_id,)).fetchone() is None:
            return None
        if conn.execute("SELECT 1 FROM account_members WHERE user_id = %s LIMIT 1",
                        (user_id,)).fetchone():
            return None
        base = _slug_base(email, display_name)
        slug, n = base, 1
        while conn.execute("SELECT 1 FROM accounts WHERE slug = %s",
                           (slug,)).fetchone():
            n += 1
            slug = f"{base}-{n}"
        row = conn.execute(
            "INSERT INTO accounts (created_at, slug, display_name) "
            "VALUES (%s, %s, %s) RETURNING id",
            (_now(), slug, _workspace_name(email, display_name))).fetchone()
        account_id = int(row["id"])
        conn.execute(
            "INSERT INTO account_members (account_id, user_id, role) "
            "VALUES (%s, %s, 'owner')", (account_id, user_id))
    return {"account_id": account_id, "slug": slug, "created": True}


def signup_credits() -> int:
    """`ZEROPAGE_SIGNUP_CREDITS`: the welcome grant a new workspace gets.
    0 (the default) grants nothing -- how much free rendering a stranger
    gets is a pricing decision, not a default somebody inherits."""
    import os
    try:
        return max(0, int(os.environ.get("ZEROPAGE_SIGNUP_CREDITS", "0")))
    except ValueError:
        return 0


def grant_signup_credits(account_id: int, *, dsn: Optional[str] = None) -> int:
    """The welcome grant, once per account (the ledger's source_ref is the
    guard, so a retry cannot grant twice). Returns the credits granted,
    0 when none are configured. Never raises: a welcome that failed is a
    workspace with no free credit, never a failed sign-in."""
    credits = signup_credits()
    if credits <= 0:
        return 0
    try:
        from . import ledger
        ledger.grant(account_id, credits, "promo",
                     source_ref=f"signup:{account_id}",
                     note="welcome credits (open sign-up)", dsn=dsn)
        return credits
    except Exception as exc:  # noqa: BLE001 -- see docstring
        print(f"[accounts] signup credits not granted to {account_id}: {exc}",
              file=sys.stderr)
        return 0


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(
        prog="accounts",
        description="Account tables + the once-only seed of Mike's user and "
                    "the two brand accounts. Identity itself is Supabase Auth's.",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    p_seed = sub.add_parser("seed", help="create user + zeropage/antihero accounts")
    p_seed.add_argument("email")
    p_seed.add_argument("--name", default="Mike")

    p_inv = sub.add_parser(
        "invite",
        help="give one person their OWN account and the membership to enter it")
    p_inv.add_argument("email")
    p_inv.add_argument(
        "--brand", required=True,
        help="the account slug they will own -- their workspace, not yours. "
             "Use a new one; an existing slug that owns rows is refused.")
    p_inv.add_argument("--name", default=None,
                       help="display name for the account (default: the slug)")
    p_inv.add_argument("--role", default="member",
                       help="recorded on the membership row. Nothing enforces "
                            "it yet -- it is a label, not a permission.")
    p_inv.add_argument("--join-existing", action="store_true",
                       help="allow adding them to an account that already owns "
                            "rows, i.e. deliberately share a workspace")

    sub.add_parser("members", help="who can enter what")

    p_op = sub.add_parser(
        "operator",
        help="turn the manual (subscription) render lanes on or off for one "
             "account -- the whole gate, and the only way to move it")
    p_op.add_argument("slug", help="the account slug, e.g. zeropage")
    door = p_op.add_mutually_exclusive_group(required=True)
    door.add_argument("--on", dest="on", action="store_true",
                      help="this account may spend the operator's own "
                           "Runway/Higgsfield subscriptions by hand")
    door.add_argument("--off", dest="on", action="store_false",
                      help="it may not (the state every account starts in)")
    p_op.set_defaults(on=None)

    p_et = sub.add_parser(
        "edits-teach",
        help="turn on/off whether a hand edit of a scene prompt (Director, "
             "Pipeline card, Direct note) teaches the RAG shelves for one account")
    p_et.add_argument("slug", help="the account slug, e.g. zeropage")
    door = p_et.add_mutually_exclusive_group(required=True)
    door.add_argument("--on", dest="on", action="store_true",
                      help="this account's prompt edits are recorded as "
                           "draft -> fix pairs on the Teach tab")
    door.add_argument("--off", dest="on", action="store_false",
                      help="they are not (the state every account starts in)")
    p_et.set_defaults(on=None)

    p_cr = sub.add_parser(
        "credits",
        help="exempt one account from being charged credits for renders -- the "
             "operator's own account, and the only way to make one")
    p_cr.add_argument("slug", help="the account slug, e.g. zeropage")
    wall = p_cr.add_mutually_exclusive_group(required=True)
    wall.add_argument("--on", dest="on", action="store_true",
                      help="this account renders without a credit hold")
    wall.add_argument("--off", dest="on", action="store_false",
                      help="it is charged like everyone else (the state every "
                           "account starts in)")
    p_cr.set_defaults(on=None)

    args = parser.parse_args(argv)

    if args.command == "credits":
        try:
            result = set_credit_exempt(args.slug, args.on)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            sys.exit(1)
        state = "ON" if result["now"] else "OFF"
        where = f"{result['slug']!r} (account {result['account_id']})"
        if result["changed"]:
            print(f"credit exemption {'OFF -> ON' if result['now'] else 'ON -> OFF'} "
                  f"for {where}")
        else:
            print(f"credit exemption already {state} for {where} -- nothing changed")
        others = [o for o in credit_exempt_accounts()
                  if o["account_id"] != result["account_id"]]
        if others:
            print("also exempt: " + ", ".join(
                f"{o['slug']} (account {o['account_id']})" for o in others))
        return

    if args.command == "edits-teach":
        try:
            result = set_prompt_edits_teach(args.slug, args.on)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            sys.exit(1)
        state = "ON" if result["now"] else "OFF"
        where = f"{result['slug']!r} (account {result['account_id']})"
        if result["changed"]:
            print(f"prompt edits teach {'OFF -> ON' if result['now'] else 'ON -> OFF'} "
                  f"for {where}")
        else:
            print(f"prompt edits teach already {state} for {where} -- nothing changed")
        others = [o for o in prompt_edits_teachers()
                  if o["account_id"] != result["account_id"]]
        if others:
            print("also on: " + ", ".join(
                f"{o['slug']} (account {o['account_id']})" for o in others))
        return

    if args.command == "operator":
        try:
            result = set_manual_lane_operator(args.slug, args.on)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            sys.exit(1)
        state = "ON" if result["now"] else "OFF"
        where = f"{result['slug']!r} (account {result['account_id']})"
        if result["changed"]:
            print(f"manual render lane {'OFF -> ON' if result['now'] else 'ON -> OFF'} "
                  f"for {where}")
        else:
            print(f"manual render lane already {state} for {where} -- nothing changed")
        others = [o for o in manual_lane_operators()
                  if o["account_id"] != result["account_id"]]
        if others:
            print("also on: " + ", ".join(
                f"{o['slug']} (account {o['account_id']})" for o in others))
        return

    if args.command == "members":
        with connect() as conn:
            rows = conn.execute(
                "SELECT a.slug, a.id AS account_id, u.email, m.role, u.claimed_at "
                "FROM account_members m "
                "JOIN accounts a ON a.id = m.account_id "
                "JOIN users u ON u.id = m.user_id "
                "ORDER BY a.slug, u.email").fetchall()
        if not rows:
            print("nobody has access to anything yet")
            return
        for r in rows:
            state = "" if r["claimed_at"] else "  (not signed in yet)"
            print(f"  {r['slug']:<16} {r['email']:<32} {r['role']}{state}")
        return

    if args.command == "invite":
        try:
            result = invite(args.email, args.brand, display_name=args.name,
                            role=args.role, join_existing=args.join_existing)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            sys.exit(1)
        made = []
        if result["created_account"]:
            made.append(f"account {result['slug']!r} (id {result['account_id']})")
        if result["created_user"]:
            made.append(f"user {args.email}")
        print("created " + " and ".join(made) if made
              else f"{args.email} already existed")
        print(f"{args.email} is now {result['role']} of {result['slug']!r}.")
        print("Tell them to sign in (Google, Discord, or email + password) using "
              "that exact email -- the first sign-in claims the row. Their board "
              "starts empty; they cannot see anyone else's.")
        return

    result = seed(args.email, display_name=args.name)
    print(f"seeded user {args.email} as owner of zeropage + antihero -- the first "
          "sign-in through Supabase with that email claims it")


if __name__ == "__main__":
    main()
