#!/usr/bin/env python3
"""
Users, accounts, membership -- the real login's spine, on Supabase Auth.

Identity is Supabase's (2026-09-03, step 6 of
docs/tasks/task-postgres-migration.md, Mike's call): `auth.users` in the
Supabase project owns who a person is, how they prove it (Google,
Discord, email+password) and their password. This module keeps what
Supabase cannot know -- which of OUR accounts a person may enter:

- `users`           a PROFILE MIRROR of auth.users, keyed by the same
                    UUID, holding email / display_name / avatar_url. No
                    password_hash, no identities: those left with the
                    hand-rolled OAuth. No FOREIGN KEY into auth.users
                    either -- the `auth` schema is Supabase's, and the
                    throwaway Postgres the tests run on has no such
                    schema; the writer (`claim`) enforces the link.
- `accounts`        a brand (zeropage / antihero -- what the hardcoded
                    BRANDS tuple grows up into), and the tenant.
- `account_members` who may enter which account.

The gate that matters lives in the shape of this data: a fresh sign-in
gets a users row and ZERO account_members rows. Membership is granted
by an existing member (`invite`), never by signing up -- these are
Mike's real accounts, not a public product.

**The invite still works before the person has ever visited.** An
invite creates a users row by EMAIL with a locally minted placeholder
id and `claimed_at` NULL. The first Supabase sign-in with that email
(`claim`) rewrites the row's id to the real auth.users UUID -- the FK on
account_members says ON UPDATE CASCADE, so the membership follows --
and stamps claimed_at. So there is no secret to send anyone.

Extends db.py in its own module (own SCHEMA, own init()), the
preprod.py pattern. Every function takes `dsn` (None = DATABASE_URL).
"""
from __future__ import annotations

import argparse
import sys
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from .db import OWNED_TABLES, backfill_owner, columns, connect, table_exists

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    -- auth.users.id once claimed; a placeholder uuid4 for an invited
    -- person who has not signed in yet (claimed_at IS NULL)
    id            TEXT PRIMARY KEY,
    created_at    TEXT NOT NULL,
    email         TEXT NOT NULL UNIQUE,
    display_name  TEXT,
    avatar_url    TEXT,
    claimed_at    TEXT
);

CREATE TABLE IF NOT EXISTS accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TEXT NOT NULL,
    slug           TEXT NOT NULL UNIQUE,
    display_name   TEXT NOT NULL,
    accent_color   TEXT,
    voice          TEXT,
    house_look     TEXT,
    house_negative TEXT,
    house_aspect   TEXT DEFAULT '9:16',
    never_list     TEXT
);

CREATE TABLE IF NOT EXISTS account_members (
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    user_id    TEXT   NOT NULL REFERENCES users(id) ON UPDATE CASCADE,
    role       TEXT   NOT NULL DEFAULT 'owner',
    PRIMARY KEY (account_id, user_id)
);
"""


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")


def init(dsn: Optional[str] = None) -> None:
    """Create the auth tables. Run after db.init_db()."""
    with connect(dsn) as conn:
        conn.execute(SCHEMA)


# --------------------------------------------------------------------------
# users -- the mirror
# --------------------------------------------------------------------------

def create_user(email: str, display_name: Optional[str] = None,
                avatar_url: Optional[str] = None, *,
                user_id: Optional[str] = None, claimed: bool = False,
                dsn: Optional[str] = None) -> str:
    """One person's mirror row. `user_id` is the auth.users UUID when the
    row is written from a sign-in (claimed=True); an invite passes
    neither and gets a placeholder that `claim` rewrites later. Raises
    psycopg.errors.UniqueViolation on a duplicate email -- never
    silently merged."""
    email = email.strip().lower()
    user_id = user_id or str(uuid.uuid4())
    with connect(dsn) as conn:
        row = conn.execute(
            "INSERT INTO users (id, created_at, email, display_name, avatar_url, "
            "claimed_at) VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
            (user_id, _now(), email, display_name, avatar_url,
             _now() if claimed else None),
        ).fetchone()
        return str(row["id"])


def get_user(user_id: str, dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    with connect(dsn) as conn:
        row = conn.execute("SELECT * FROM users WHERE id = %s", (str(user_id),)).fetchone()
        return dict(row) if row else None


def get_user_by_email(email: str, dsn: Optional[str] = None) -> Optional[dict[str, Any]]:
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM users WHERE email = %s", (email.strip().lower(),)
        ).fetchone()
        return dict(row) if row else None


def update_profile(user_id: str, display_name: Optional[str] = None,
                   avatar_url: Optional[str] = None,
                   dsn: Optional[str] = None) -> None:
    """Fill profile fields from a provider sign-in without clobbering
    what's already there."""
    with connect(dsn) as conn:
        conn.execute(
            "UPDATE users SET display_name = COALESCE(display_name, %s), "
            "avatar_url = COALESCE(%s, avatar_url) WHERE id = %s",
            (display_name, avatar_url, str(user_id)),
        )


def claim(user_id: str, email: Optional[str], display_name: Optional[str] = None,
          avatar_url: Optional[str] = None, *,
          dsn: Optional[str] = None) -> tuple[Optional[str], Optional[str]]:
    """The identity-resolution ladder, run on every Supabase sign-in.
    Returns (user_id, error) -- exactly one is set.

      1. a mirror row with this UUID exists            -> sign in.
      2. the email matches an UNCLAIMED row (an invite,
         or the seeded bootstrap user)                 -> claim it: the
         row's id becomes this UUID (account_members follows through
         ON UPDATE CASCADE), claimed_at is stamped.
      3. the email matches a row claimed by a DIFFERENT
         UUID                                          -> refuse. Supabase
         keeps one auth user per email, so this only happens when an
         auth user was deleted and re-created; merging silently would
         hand the new person the old memberships.
      4. brand-new                                     -> new mirror row,
         zero memberships (the gate).

    `email` None is a clear failure, not a NULL users.email row: a
    provider that returned no verified address gets told so.
    """
    user_id = str(user_id)
    with connect(dsn) as conn:
        if conn.execute("SELECT 1 FROM users WHERE id = %s", (user_id,)).fetchone():
            conn.execute(
                "UPDATE users SET display_name = COALESCE(display_name, %s), "
                "avatar_url = COALESCE(%s, avatar_url) WHERE id = %s",
                (display_name, avatar_url, user_id))
            return user_id, None
        if not email:
            return None, ("the provider did not return a verified email for this "
                          "account -- verify your email there and try again")
        email = email.strip().lower()
        row = conn.execute("SELECT id, claimed_at FROM users WHERE email = %s",
                           (email,)).fetchone()
        if row is not None and row["claimed_at"] is None:
            conn.execute(
                "UPDATE users SET id = %s, claimed_at = %s, "
                "display_name = COALESCE(display_name, %s), "
                "avatar_url = COALESCE(%s, avatar_url) WHERE id = %s",
                (user_id, _now(), display_name, avatar_url, row["id"]))
            return user_id, None
        if row is not None:
            return None, ("an account with this email already exists -- sign in "
                          "the way you first signed up")
        conn.execute(
            "INSERT INTO users (id, created_at, email, display_name, avatar_url, "
            "claimed_at) VALUES (%s, %s, %s, %s, %s, %s)",
            (user_id, _now(), email, display_name, avatar_url, _now()))
        return user_id, None


# --------------------------------------------------------------------------
# accounts + membership
# --------------------------------------------------------------------------

def upsert_account(slug: str, display_name: str, accent_color: Optional[str] = None,
                   dsn: Optional[str] = None) -> int:
    with connect(dsn) as conn:
        row = conn.execute("SELECT id FROM accounts WHERE slug = %s", (slug,)).fetchone()
        if row:
            return int(row["id"])
        row = conn.execute(
            "INSERT INTO accounts (created_at, slug, display_name, accent_color) "
            "VALUES (%s, %s, %s, %s) RETURNING id",
            (_now(), slug, display_name, accent_color),
        ).fetchone()
        return int(row["id"])


def add_member(account_id: int, user_id: str, role: str = "owner",
               dsn: Optional[str] = None) -> None:
    with connect(dsn) as conn:
        conn.execute(
            "INSERT INTO account_members (account_id, user_id, role) "
            "VALUES (%s, %s, %s) ON CONFLICT (account_id, user_id) DO NOTHING",
            (account_id, str(user_id), role),
        )


def memberships(user_id: str, dsn: Optional[str] = None) -> list[dict[str, Any]]:
    """The accounts this user may enter. Empty list == signed in but no
    access -- the state the membership gate renders, never auto-fixed."""
    with connect(dsn) as conn:
        rows = conn.execute(
            "SELECT a.*, m.role FROM accounts a "
            "JOIN account_members m ON m.account_id = a.id "
            "WHERE m.user_id = %s ORDER BY a.slug",
            (str(user_id),),
        ).fetchall()
        return [dict(r) for r in rows]


# --------------------------------------------------------------------------
# seed
# --------------------------------------------------------------------------

def seed(email: str, display_name: str = "Mike",
         dsn: Optional[str] = None) -> dict[str, Any]:
    """
    The once-only bootstrap: Mike's user, the two real accounts, and
    owner membership on both. Idempotent -- re-running finds instead of
    duplicating. The user row is UNCLAIMED until the first Supabase
    sign-in with that email (`claim`), which is what attaches the real
    identity; there is no password here -- Supabase holds those. Brand
    metadata (labels, accents) mirrors app.main's BRAND_META so the
    picker looks like the brand pill always has.
    """
    init(dsn)
    user = get_user_by_email(email, dsn=dsn)
    user_id = user["id"] if user else create_user(
        email, display_name=display_name, dsn=dsn)

    zeropage = upsert_account("zeropage", "Zero Page Films", "#8b5cf6", dsn=dsn)
    antihero = upsert_account("antihero", "ANTIHERO", "#d64550", dsn=dsn)
    add_member(zeropage, user_id, dsn=dsn)
    add_member(antihero, user_id, dsn=dsn)
    claimed = claim_unowned_rows(dsn=dsn)
    return {"user_id": user_id, "accounts": [zeropage, antihero],
            "claimed": claimed}


def claim_unowned_rows(account_id: Optional[int] = None,
                       dsn: Optional[str] = None) -> dict[str, int]:
    """Give every pre-tenancy row an owner. Returns {table: rows claimed}.

    Each module's own init() backfills too, but init() runs before there
    is an account to backfill *to* on a fresh database -- so seeding is
    the other end of that. Tables that do not exist yet are skipped
    rather than created: this claims ownership, it does not define
    schema.
    """
    claimed: dict[str, int] = {}
    with connect(dsn) as conn:
        for table in OWNED_TABLES:
            if not table_exists(conn, table):
                continue
            if "account_id" not in columns(conn, table):
                continue
            n = backfill_owner(conn, table, account_id)
            if n:
                claimed[table] = n
    return claimed


def slug_of(account_id: Optional[int], dsn: Optional[str] = None) -> Optional[str]:
    """The tenant's slug for an account id -- the label rag_documents.project
    carries (see src/rag.py). Never raises: None in, None out; a database
    with no accounts table (a fresh install, most test fixtures) is None
    too, which the library treats as "unlabelled", never as an error."""
    if account_id is None:
        return None
    try:
        with connect(dsn) as conn:
            if not table_exists(conn, "accounts"):
                return None
            row = conn.execute("SELECT slug FROM accounts WHERE id = %s",
                               (int(account_id),)).fetchone()
            return str(row["slug"]) if row else None
    except Exception:
        return None


def resolve_account(slug: Optional[str] = None,
                    dsn: Optional[str] = None) -> Optional[int]:
    """Turn a `--account <slug>` into an id, or fall back to the oldest
    account on the database.

    For ENTRY POINTS only -- CLIs, the nightly run, anything with no
    session behind it. Library functions take `account_id` as a required
    argument on purpose; a fallback buried in the data layer is the leak
    that rule exists to prevent. Here it is deliberate and in one place.

    Returns None on a database with no accounts -- including one where
    the table does not exist yet, which a fresh install genuinely is.
    The caller then operates on the unowned pool, which is exactly what
    such a database holds. Raising there instead would turn "nothing has
    been seeded" into a crash in every CLI and MCP tool, which is what
    it did until a full-suite run happened to schedule the mcp_server
    tests onto a worker with an unseeded database. (The table check is
    to_regclass on the connection's search_path, so a per-test schema
    and the real one look alike.)
    """
    with connect(dsn) as conn:
        if not table_exists(conn, "accounts"):
            if slug:
                raise ValueError(f"no account {slug!r} -- no accounts exist yet")
            return None
        if slug:
            row = conn.execute(
                "SELECT id FROM accounts WHERE slug = %s", (slug.strip().lower(),)
            ).fetchone()
            if row is None:
                known = [r["slug"] for r in conn.execute(
                    "SELECT slug FROM accounts ORDER BY slug")]
                raise ValueError(
                    f"no account {slug!r}" + (f" -- try one of {known}" if known else ""))
            return int(row["id"])
        row = conn.execute("SELECT MIN(id) AS id FROM accounts").fetchone()
        return int(row["id"]) if row and row["id"] is not None else None


def invite(email: str, slug: str, display_name: Optional[str] = None,
           role: str = "member", join_existing: bool = False,
           dsn: Optional[str] = None) -> dict[str, Any]:
    """Give one person their own account, and the membership to enter it.

    The v1 posture, made a command instead of a hand-written INSERT: a
    sign-in gets a users row and zero memberships, so access is only
    ever granted deliberately. This is that grant.

    **A pilot user gets their OWN account.** That is the whole point and
    it is the easy thing to get catastrophically wrong: adding someone to
    `zeropage` does not give them a workspace, it gives them Mike's --
    every concept, location and cast member on the board, because
    account_id is the ownership boundary. So an account that already owns
    rows is refused unless `join_existing` says otherwise, and the error
    counts what they would have been able to see.

    No identity is created on purpose: the row sits unclaimed until they
    sign in through Supabase with that exact email, and `claim` takes it
    over (the same path the bootstrap user takes). So the invite is
    complete before they have ever visited, and there is no secret to
    send them.

    Returns {"user_id", "account_id", "slug", "created_user",
    "created_account", "role"}.
    """
    email = email.strip().lower()
    if not email or "@" not in email:
        raise ValueError(f"that does not look like an email: {email!r}")
    slug = slug.strip().lower()
    if not slug:
        raise ValueError("an invite needs an account slug")

    with connect(dsn) as conn:
        existing = conn.execute(
            "SELECT id FROM accounts WHERE slug = %s", (slug,)).fetchone()
        if existing is not None and not join_existing:
            owned = 0
            for table in OWNED_TABLES:
                if not table_exists(conn, table):
                    continue
                if "account_id" not in columns(conn, table):
                    continue
                owned += conn.execute(
                    f"SELECT COUNT(*) FROM {table} WHERE account_id = %s",
                    (existing["id"],)).fetchone()[0]
            if owned:
                raise ValueError(
                    f"account {slug!r} already exists and owns {owned} rows -- "
                    f"inviting {email} into it would show them all of that. "
                    f"Give them their own slug, or pass join_existing=True "
                    f"(--join-existing) if sharing a workspace is what you mean.")

    created_account = existing is None
    account_id = upsert_account(slug, display_name or slug.title(), dsn=dsn)

    user = get_user_by_email(email, dsn=dsn)
    created_user = user is None
    user_id = user["id"] if user else create_user(email, dsn=dsn)

    add_member(account_id, user_id, role=role, dsn=dsn)
    return {"user_id": user_id, "account_id": account_id, "slug": slug,
            "created_user": created_user, "created_account": created_account,
            "role": role}


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(
        prog="accounts",
        description="Account tables + the once-only seed of Mike's user and "
                    "the two brand accounts. Identity itself is Supabase Auth's.",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    p_seed = sub.add_parser("seed", help="create user + zeropage/antihero accounts")
    p_seed.add_argument("email")
    p_seed.add_argument("--name", default="Mike")

    p_inv = sub.add_parser(
        "invite",
        help="give one person their OWN account and the membership to enter it")
    p_inv.add_argument("email")
    p_inv.add_argument(
        "--brand", required=True,
        help="the account slug they will own -- their workspace, not yours. "
             "Use a new one; an existing slug that owns rows is refused.")
    p_inv.add_argument("--name", default=None,
                       help="display name for the account (default: the slug)")
    p_inv.add_argument("--role", default="member",
                       help="recorded on the membership row. Nothing enforces "
                            "it yet -- it is a label, not a permission.")
    p_inv.add_argument("--join-existing", action="store_true",
                       help="allow adding them to an account that already owns "
                            "rows, i.e. deliberately share a workspace")

    sub.add_parser("members", help="who can enter what")

    args = parser.parse_args(argv)

    if args.command == "members":
        with connect() as conn:
            rows = conn.execute(
                "SELECT a.slug, a.id AS account_id, u.email, m.role, u.claimed_at "
                "FROM account_members m "
                "JOIN accounts a ON a.id = m.account_id "
                "JOIN users u ON u.id = m.user_id "
                "ORDER BY a.slug, u.email").fetchall()
        if not rows:
            print("nobody has access to anything yet")
            return
        for r in rows:
            state = "" if r["claimed_at"] else "  (not signed in yet)"
            print(f"  {r['slug']:<16} {r['email']:<32} {r['role']}{state}")
        return

    if args.command == "invite":
        try:
            result = invite(args.email, args.brand, display_name=args.name,
                            role=args.role, join_existing=args.join_existing)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            sys.exit(1)
        made = []
        if result["created_account"]:
            made.append(f"account {result['slug']!r} (id {result['account_id']})")
        if result["created_user"]:
            made.append(f"user {args.email}")
        print("created " + " and ".join(made) if made
              else f"{args.email} already existed")
        print(f"{args.email} is now {result['role']} of {result['slug']!r}.")
        print("Tell them to sign in (Google, Discord, or email + password) using "
              "that exact email -- the first sign-in claims the row. Their board "
              "starts empty; they cannot see anyone else's.")
        return

    result = seed(args.email, display_name=args.name)
    print(f"seeded user {args.email} as owner of zeropage + antihero -- the first "
          "sign-in through Supabase with that email claims it")


if __name__ == "__main__":
    main()
