"""
What the assistant pill remembers, per account (2026-09-29).

Until today the pill kept its persona in localStorage and its conversation
in sessionStorage, so the thread died with the tab (it was lost twice on
2026-09-28 alone) and Nova had to be set up again in every browser. Three
OWNED tables, one owner each:

- `assistants`: the persona -- a name, an emoji, one of the three tones.
  One row per account. Cleaned with the same rules the brain applies when
  it puts the name into a prompt (assistant_brain.clean_name/clean_tone),
  so the pill never shows a name the model was not given.
- `assistant_projects`: the conversation and the step it is on, and since
  2026-10-02 the composer's DRAFT beside it (`draft_json`: the idea in the
  box, the brief the guide wrote, the picked references, the uploads as
  their bin URLs, which mode the box is in, the last "scene written"
  card). One OPEN project per account (archived_at NULL); "New project"
  archives it and a fresh one starts. Archived rows are kept -- the same
  rule as the board: leaving is never deleting. The Studio composer's own
  Guide thread lived only in the page's React state until today, so
  clicking to another tab lost the conversation and every frame the hunt
  had drawn; now the composer and the pill are two views on this one row.
- `reference_verdicts`: the person's click on a contact sheet beside what
  refcheck decided about the same frame. Keep a frame the checker cut, or
  leave one it kept, and that disagreement is the only evidence there is of
  where the checker's taste and the person's part. `agreement()` reads it.
  Nothing consumes it automatically yet: a checker that retuned itself off
  a dozen clicks would be learning noise.

Nothing here calls a model or spends; every function degrades to "nothing
remembered" rather than raising into the page.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any, Optional

from . import db

# A thread is the pill's working memory, not an archive: the newest turns
# are what the next turn sends and what the card draws. Bounded so a long
# project cannot grow one row without limit.
MAX_TURNS = 40
MAX_TURNS_BYTES = 400_000
MAX_AVATAR_CHARS = 16          # one emoji can be a long ZWJ sequence
# The draft is bounded by construction (_clean_draft keeps known keys and
# cuts each), so no byte cap is needed beyond the per-field ones.
MAX_DRAFT_TEXT = 10_000        # the composer's own textarea maxLength
MAX_DRAFT_REFS = 40            # picked photos / uploads, each a URL
DRAFT_MODES = ("guide", "create")

SCHEMA = """
CREATE TABLE IF NOT EXISTS assistants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    avatar      TEXT NOT NULL,
    tone        TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS assistant_projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT NOT NULL DEFAULT '',
    stage       TEXT NOT NULL DEFAULT '',
    turns_json  TEXT NOT NULL DEFAULT '[]',
    draft_json  TEXT NOT NULL DEFAULT '{}',
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    archived_at TEXT
);
CREATE TABLE IF NOT EXISTS reference_verdicts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT,
    candidate_id  TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT '',
    query         TEXT NOT NULL DEFAULT '',
    checker_kept  BOOLEAN NOT NULL,
    checker_why   TEXT NOT NULL DEFAULT '',
    person_kept   BOOLEAN NOT NULL,
    source_url    TEXT NOT NULL DEFAULT '',
    created_at    TEXT NOT NULL
);
"""

INDEXES = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_assistants_account ON assistants (account_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_assistant_projects_open
    ON assistant_projects (account_id) WHERE archived_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_reference_verdicts_account
    ON reference_verdicts (account_id, created_at);
"""

TABLES = ("assistants", "assistant_projects", "reference_verdicts")


def init(dsn: Optional[str] = None) -> None:
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA)
        # additive, for the live table made before the draft existed
        conn.execute("ALTER TABLE assistant_projects "
                     "ADD COLUMN IF NOT EXISTS draft_json TEXT NOT NULL DEFAULT '{}'")
        for table in TABLES:
            db.own_table(conn, table)
        conn.execute(INDEXES)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# --- the persona -------------------------------------------------------------

def clean_avatar(avatar) -> str:
    """One emoji (or any short glyph), never markup: whitespace and angle
    brackets are dropped, the rest cut to MAX_AVATAR_CHARS."""
    avatar = re.sub(r"[\s<>&\"']", "", str(avatar or ""))
    return avatar[:MAX_AVATAR_CHARS]


def get_persona(*, account_id: int, dsn: Optional[str] = None) -> Optional[dict]:
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT name, avatar, tone, updated_at FROM assistants WHERE account_id = %s",
            (account_id,)).fetchone()
    return dict(row) if row else None


def save_persona(name, avatar, tone, *, account_id: int,
                 dsn: Optional[str] = None) -> dict:
    """Upsert the account's persona, cleaned. Returns what was stored."""
    from . import assistant_brain
    persona = {"name": assistant_brain.clean_name(name),
               "avatar": clean_avatar(avatar) or "🦊",
               "tone": assistant_brain.clean_tone(tone)}
    with db.connect(dsn) as conn:
        conn.execute(
            "INSERT INTO assistants (account_id, name, avatar, tone, updated_at) "
            "VALUES (%s, %s, %s, %s, %s) "
            "ON CONFLICT (account_id) DO UPDATE SET name = EXCLUDED.name, "
            "avatar = EXCLUDED.avatar, tone = EXCLUDED.tone, updated_at = EXCLUDED.updated_at",
            (account_id, persona["name"], persona["avatar"], persona["tone"], _now()))
    return persona


# --- the project ------------------------------------------------------------

def _bounded(turns: list) -> list:
    """The newest MAX_TURNS turns, dropping from the front until the JSON
    fits MAX_TURNS_BYTES. A turn that is not a dict is not a turn."""
    turns = [t for t in (turns or []) if isinstance(t, dict)][-MAX_TURNS:]
    while turns and len(json.dumps(turns, default=str)) > MAX_TURNS_BYTES:
        turns = turns[1:]
    return turns


def _urls(value) -> list:
    """A list of reference URLs as the composer holds them: site-relative
    paths or http(s), strings only, deduplicated in order, bounded."""
    out: list = []
    for u in (value if isinstance(value, list) else [])[:MAX_DRAFT_REFS * 2]:
        u = str(u or "").strip() if isinstance(u, str) else ""
        if u and len(u) <= 1000 and (u.startswith("/") or u.startswith("http")) \
                and u not in out:
            out.append(u)
        if len(out) >= MAX_DRAFT_REFS:
            break
    return out


def _clean_draft(draft) -> dict:
    """The composer's draft, keys and types this store knows and nothing
    else. A field the page never wrote comes back as its empty value, so
    the client can trust the shape and never has to default it."""
    d = draft if isinstance(draft, dict) else {}
    uploads: list = []
    for item in (d.get("uploads") if isinstance(d.get("uploads"), list) else [])[:MAX_DRAFT_REFS]:
        if not isinstance(item, dict):
            continue
        url = _urls([item.get("url")])
        if url:
            uploads.append({"url": url[0],
                            "name": " ".join(str(item.get("name") or "").split())[:200]})
    written = d.get("written") if isinstance(d.get("written"), dict) else None
    if written is not None:
        cid = written.get("conceptId")
        written = {"conceptId": int(cid) if isinstance(cid, int) and not isinstance(cid, bool) else None,
                   "detail": str(written.get("detail") or "")[:300]}
    mode = str(d.get("mode") or "")
    return {"idea": str(d.get("idea") or "")[:MAX_DRAFT_TEXT],
            "brief": str(d.get("brief") or "")[:MAX_DRAFT_TEXT],
            # Create is the box's default (Direction A, 2026-10-02); a
            # Guide the person chose is stored and kept
            "mode": mode if mode in DRAFT_MODES else "create",
            "picked": _urls(d.get("picked")),
            "uploads": uploads,
            "written": written}


EMPTY_DRAFT = _clean_draft({})


def _project(row) -> dict:
    out = dict(row)
    try:
        out["turns"] = json.loads(out.pop("turns_json") or "[]")
    except ValueError:
        out["turns"] = []
    try:
        out["draft"] = _clean_draft(json.loads(out.pop("draft_json", None) or "{}"))
    except ValueError:
        out["draft"] = dict(EMPTY_DRAFT)
    return out


_PROJECT_COLS = "id, title, stage, turns_json, draft_json, created_at, updated_at"


def open_project(*, account_id: int, dsn: Optional[str] = None) -> Optional[dict]:
    with db.connect(dsn) as conn:
        row = conn.execute(
            f"SELECT {_PROJECT_COLS} "
            "FROM assistant_projects WHERE account_id = %s AND archived_at IS NULL",
            (account_id,)).fetchone()
    return _project(row) if row else None


def save_project(turns, stage, *, account_id: int, title: str = "",
                 draft: Optional[dict] = None, dsn: Optional[str] = None) -> dict:
    """Write the open project's thread and step, creating it on first save.

    `draft` is the composer's box (see _clean_draft); None -- a caller
    that only knows the thread, like the pill did before the two shared
    a row -- leaves whatever draft is stored exactly as it was."""
    from . import assistant_brain
    turns = _bounded(turns)
    stage = assistant_brain.clean_stage(stage)
    title = " ".join(str(title or "").split())[:120]
    if not title:
        first = next((t.get("content") for t in turns
                      if t.get("role") == "user" and t.get("content")), "")
        title = " ".join(str(first).split())[:80]
    blob = json.dumps(turns, default=str)
    draft_blob = json.dumps(_clean_draft(draft)) if draft is not None else None
    now = _now()
    with db.connect(dsn) as conn:
        row = conn.execute(
            "UPDATE assistant_projects SET turns_json = %s, stage = %s, "
            "draft_json = COALESCE(%s, draft_json), "
            "title = CASE WHEN title = '' THEN %s ELSE title END, updated_at = %s "
            "WHERE account_id = %s AND archived_at IS NULL "
            f"RETURNING {_PROJECT_COLS}",
            (blob, stage, draft_blob, title, now, account_id)).fetchone()
        if row is None:
            row = conn.execute(
                "INSERT INTO assistant_projects "
                "(account_id, title, stage, turns_json, draft_json, created_at, updated_at) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s) "
                f"RETURNING {_PROJECT_COLS}",
                (account_id, title, stage, blob, draft_blob or "{}", now, now)).fetchone()
    return _project(row)


def new_project(*, account_id: int, dsn: Optional[str] = None) -> None:
    """Archive the open project, if any. The next save starts a fresh one."""
    with db.connect(dsn) as conn:
        conn.execute("UPDATE assistant_projects SET archived_at = %s "
                     "WHERE account_id = %s AND archived_at IS NULL",
                     (_now(), account_id))


# --- keep / reject against the checker -------------------------------------

def record_verdicts(frames, *, account_id: int, project_id: Optional[int] = None,
                    dsn: Optional[str] = None) -> int:
    """One row per frame the person saw on a contact sheet when they pressed
    Keep: what refcheck decided (`checker_kept`, `why`) and what they did
    (`person_kept`). Only ids a hunt actually served are recorded
    (imagesearch.get), the same fabrication rule keep_references applies.
    Returns how many rows were written."""
    from .imagesearch import get
    rows = []
    for f in list(frames or [])[:200]:
        if not isinstance(f, dict):
            continue
        cid = str(f.get("id") or "").strip()
        if not cid or (get(cid, dsn=dsn) if dsn is not None else get(cid)) is None:
            continue
        rows.append((account_id, project_id, cid,
                     str(f.get("role") or "")[:40], str(f.get("query") or "")[:200],
                     bool(f.get("checker_kept")), str(f.get("why") or "")[:300],
                     bool(f.get("person_kept")), str(f.get("source_url") or "")[:500],
                     _now()))
    if not rows:
        return 0
    with db.connect(dsn) as conn:
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO reference_verdicts (account_id, project_id, candidate_id, role, "
                "query, checker_kept, checker_why, person_kept, source_url, created_at) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", rows)
    return len(rows)


def agreement(*, account_id: int, dsn: Optional[str] = None) -> dict[str, Any]:
    """How often the person's Keep matched the checker's call.
    `kept_anyway` is a frame the checker cut and the person kept (the
    checker too strict); `left_out` is one it kept and the person dropped
    (too lenient). `rate` is None until there is anything to divide."""
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS n, "
            "COUNT(*) FILTER (WHERE checker_kept = person_kept) AS agree, "
            "COUNT(*) FILTER (WHERE NOT checker_kept AND person_kept) AS kept_anyway, "
            "COUNT(*) FILTER (WHERE checker_kept AND NOT person_kept) AS left_out "
            "FROM reference_verdicts WHERE account_id = %s", (account_id,)).fetchone()
    n = int(row["n"])
    return {"n": n, "agree": int(row["agree"]), "kept_anyway": int(row["kept_anyway"]),
            "left_out": int(row["left_out"]),
            "rate": round(int(row["agree"]) / n, 3) if n else None}
