"""
Autonomy bookkeeping for the content graph: which destination may post
on its own, what got parked instead of posted, and the one switch that
stops everything.

Same shape as preprod.py/entities.py: own SCHEMA, own init(), tables on
the shared pipeline DB through db.connect -- one database, not a
second store. Postgres since 2026-09-03; `dsn` where it took `path`.

Four tables:
- channels     -- per-destination autonomy ("shadow" | "queue" | "auto")
                  and a hard posts/day rate cap. Autonomy is a property
                  of each destination, never a global flag: Zero Page
                  can run unattended while the personal account stays
                  gated. Promotion is a one-row change.
- hold_queue   -- the dead-man log. EVERY graph run ends here as a row:
                  held (with why) or posted (with what). If you want to
                  know what the graph did while you weren't looking,
                  it's one table. OWNED (db.OWNED_TABLES, 2026-09-02):
                  a hold is the run of one account, and the dry run
                  proved any signed-in user could list and reject
                  Mike's until it carried an owner.
- corrections  -- mid-run human notes, for the human_note interrupt
                  node when it lands. Written now so the schema exists.
- settings     -- key/value; the kill switch lives here. Global on
                  purpose: one place to pull the plug on every channel
                  at once.

Both channels seed as "shadow": nothing posts unattended on day one --
auto is earned by grading the evaluator against your own judgment, then
promoted with a one-row change.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Optional

import psycopg

from . import db

SCHEMA = """
CREATE TABLE IF NOT EXISTS channels (
    name       TEXT PRIMARY KEY,
    autonomy   TEXT NOT NULL DEFAULT 'shadow',   -- shadow | queue | auto
    rate_cap   INTEGER NOT NULL DEFAULT 1,       -- hard max posts/day
    targets    TEXT NOT NULL DEFAULT '',         -- comma list: instagram,youtube
    notes      TEXT
);

CREATE TABLE IF NOT EXISTS hold_queue (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    channel    TEXT NOT NULL,
    status     TEXT NOT NULL DEFAULT 'held',     -- held | approved | rejected | posted
    reason     TEXT,
    concept_id BIGINT,
    caption    TEXT,
    payload    TEXT,                             -- JSON: prompts/clips/anything worth replaying
    account_id BIGINT                            -- OWNED: db.own_table declares the FK
);
CREATE INDEX IF NOT EXISTS idx_hold_queue_status ON hold_queue (status);
CREATE INDEX IF NOT EXISTS idx_hold_queue_channel ON hold_queue (channel);

CREATE TABLE IF NOT EXISTS corrections (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    run_id     TEXT,
    note       TEXT NOT NULL,
    consumed   INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS settings (
    key        TEXT PRIMARY KEY,
    value      TEXT
);

CREATE TABLE IF NOT EXISTS prompt_scores (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TEXT NOT NULL,
    run_id        TEXT,
    prompt        TEXT,
    score         INTEGER,
    passed        INTEGER,
    reason        TEXT,
    dims          TEXT,           -- json {subject, camera, motion, lighting, coherence}
    human_verdict TEXT,           -- 'post' | 'reject' | NULL, filled when the hold is graded
    unreadable    INTEGER NOT NULL DEFAULT 0  -- 1 = the judge errored, so this row is NOT a verdict
);
CREATE INDEX IF NOT EXISTS idx_prompt_scores_run ON prompt_scores (run_id);
"""

KILL_KEY = "kill_switch"

# name, autonomy, rate_cap, targets, notes.
# Zero Page auto-generates and (once you approve) posts to IG + YouTube;
# Antihero is the personal brand and stays under further review.
DEFAULT_CHANNELS = (
    ("zeropage", "queue", 1, "instagram,youtube",
     "auto-generates; approve to post; the pipeline posts to IG + YouTube"),
    ("antihero", "shadow", 1, "",
     "personal brand — further review; grade every run before it can post"),
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def init(dsn=None) -> None:
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA)
        # seed defaults (fresh installs only). The SQLite-era migrations
        # that used to sit here (the `targets` ALTER, the personal ->
        # antihero rename) are gone: no Postgres database predates them.
        for name, autonomy, cap, targets, notes in DEFAULT_CHANNELS:
            conn.execute(
                "INSERT INTO channels (name, autonomy, rate_cap, targets, notes) "
                "VALUES (%s, %s, %s, %s, %s) ON CONFLICT (name) DO NOTHING",
                (name, autonomy, cap, targets, notes),
            )
        # tenancy (2026-09-02): the additive ALTER + backfill every owned
        # table got on 2026-08-31, which this one was left out of. Every
        # existing hold belongs to the bootstrap account -- on the live
        # database that is account 1, the one that owns every concept the
        # holds point at. Proved against a copy before it landed here.
        db.own_table(conn, "hold_queue")
        # prompt_scores.unreadable (2026-09-14): a live database predates
        # it, and the default is what makes the backfill a no-op -- every
        # existing row WAS a real verdict as far as anyone can now tell,
        # so 0 is both the honest value and the one that leaves
        # prompt_gate_agreement reading exactly as it did before.
        if "unreadable" not in db.columns(conn, "prompt_scores"):
            conn.execute("ALTER TABLE prompt_scores ADD COLUMN "
                         "unreadable INTEGER NOT NULL DEFAULT 0")


# --- channels -------------------------------------------------------------

def get_channel(name: str, dsn=None) -> Optional[dict]:
    with db.connect(dsn) as conn:
        row = conn.execute("SELECT * FROM channels WHERE name = %s", (name,)).fetchone()
        return dict(row) if row else None


def set_autonomy(name: str, autonomy: str, dsn=None) -> None:
    """The promotion (or demotion): one row change, nothing else moves."""
    if autonomy not in ("shadow", "queue", "auto"):
        raise ValueError(f"autonomy must be shadow|queue|auto, got {autonomy!r}")
    with db.connect(dsn) as conn:
        conn.execute("UPDATE channels SET autonomy = %s WHERE name = %s", (autonomy, name))


# The platforms a channel may name as a post target. A target is a
# promise that an adapter exists: autopilot._post_dispatch routes on
# exactly these names, and a typo'd one would fan a post action out to a
# platform that raises NotImplementedError in live mode -- which is a
# gate failure discovered at the worst possible moment. Validated on the
# way IN (set_targets) and again on the way OUT (channel_targets), since
# the seed and any hand-edited row bypass the setter.
POST_TARGETS = ("instagram", "youtube", "tiktok")


def parse_targets(value) -> list[str]:
    """The stored comma list as a clean, ordered, de-duplicated list.
    Order is kept because it is the order a fan-out posts in, and a
    person who wrote "instagram,youtube" meant Instagram first."""
    seen: list[str] = []
    for part in str(value or "").split(","):
        name = part.strip().lower()
        if name and name not in seen:
            seen.append(name)
    return seen


def validate_targets(value) -> list[str]:
    """Parse and refuse anything without an adapter. Raises ValueError
    naming the offender -- the caller is a person editing a channel, and
    "instgram" should fail at the edit, not at 3am."""
    targets = parse_targets(value)
    unknown = [t for t in targets if t not in POST_TARGETS]
    if unknown:
        raise ValueError(
            f"unknown post target(s) {', '.join(unknown)} -- "
            f"must be one of {', '.join(POST_TARGETS)}")
    return targets


def set_targets(name: str, targets, dsn=None) -> list[str]:
    """Set a channel's post targets. Validated first, so an unroutable
    target can never reach the row the fan-out reads."""
    clean = validate_targets(targets if isinstance(targets, str) else ",".join(targets))
    with db.connect(dsn) as conn:
        conn.execute("UPDATE channels SET targets = %s WHERE name = %s",
                     (",".join(clean), name))
    return clean


def channel_targets(name: str, dsn=None) -> list[str]:
    """Where this channel posts, as a list an executor can be dispatched
    on. NEVER RAISES, and that is the whole point: it is read from
    autopilot.build_plan, which is a read-only preview that must work on
    a database with no channels table at all (every preprod-only test
    fixture) and must not be taken down by a hand-edited row naming a
    platform we cannot reach. Unknown names are dropped, not honoured."""
    try:
        row = get_channel(name, dsn=dsn) or {}
    except Exception:
        return []
    return [t for t in parse_targets(row.get("targets")) if t in POST_TARGETS]


def list_channels(dsn=None) -> list[dict]:
    with db.connect(dsn) as conn:
        return [dict(r) for r in conn.execute("SELECT * FROM channels ORDER BY name")]


# --- the kill switch ------------------------------------------------------

def kill(reason: str = "", dsn=None) -> None:
    with db.connect(dsn) as conn:
        conn.execute(
            "INSERT INTO settings (key, value) VALUES (%s, %s) "
            "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            (KILL_KEY, reason or "killed"),
        )


def unkill(dsn=None) -> None:
    with db.connect(dsn) as conn:
        conn.execute("DELETE FROM settings WHERE key = %s", (KILL_KEY,))


def killed(dsn=None) -> bool:
    """True forces every run on every channel to hold. Also honours the
    ZEROPAGE_KILL env var so the plug can be pulled without a DB write."""
    import os
    if os.environ.get("ZEROPAGE_KILL"):
        return True
    with db.connect(dsn) as conn:
        row = conn.execute("SELECT value FROM settings WHERE key = %s", (KILL_KEY,)).fetchone()
        return row is not None


# --- the hold queue / dead-man log ---------------------------------------

def to_hold(channel: str, reason: str, concept_id=None, caption: str = "",
            payload: Optional[dict] = None, status: str = "held",
            dsn=None, *, account_id: Optional[int]) -> int:
    """Park a run. `account_id` is keyword-only with no default, the
    preprod.get_concept rule: a forgotten owner is a TypeError at the
    call, not a row nobody can see (or everybody can)."""
    with db.connect(dsn) as conn:
        row = conn.execute(
            "INSERT INTO hold_queue (created_at, channel, status, reason, "
            "concept_id, caption, payload, account_id) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
            (_now(), channel, status, reason, concept_id, caption,
             json.dumps(payload) if payload is not None else None, account_id),
        ).fetchone()
        return int(row["id"])


def _parse_payload(row: dict) -> dict:
    if row.get("payload"):
        try:
            row["payload"] = json.loads(row["payload"])
        except (ValueError, TypeError):
            pass
    return row


def list_hold(status: Optional[str] = "held", dsn=None, *,
              account_id: Optional[int]) -> list[dict]:
    """This account's holds, newest first. status=None lists every
    status; the owner predicate is never optional."""
    query = "SELECT * FROM hold_queue WHERE account_id IS NOT DISTINCT FROM %s"
    params: tuple = (account_id,)
    if status is not None:
        query += " AND status = %s"
        params = (account_id, status)
    query += " ORDER BY created_at DESC"
    with db.connect(dsn) as conn:
        rows = [dict(r) for r in conn.execute(query, params)]
    return [_parse_payload(row) for row in rows]


def get_hold(hold_id: int, dsn=None, *,
             account_id: Optional[int]) -> Optional[dict]:
    """One hold, if it is this account's. None for someone else's, the
    same answer as for a missing id -- ids are sequential, so "not
    yours" and "not found" must be indistinguishable or the table can
    be mapped by counting (the preprod.get_concept rule)."""
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM hold_queue WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (hold_id, account_id),
        ).fetchone()
    return _parse_payload(dict(row)) if row else None


def hold_for_concept(concept_id: int, dsn=None, *,
                     account_id: Optional[int]) -> Optional[dict]:
    """The latest graph run that ended on this concept, or None when no
    run ever did -- which is how a Studio Create row (Create stops on
    the board by design) or a phone capture reads. Owner predicate never
    optional, the get_hold rule. A database with no hold table yet (a
    fresh clone the graph has never run against) reads as "no run", not
    as an error -- the same answer, for the same reason."""
    try:
        with db.connect(dsn) as conn:
            row = conn.execute(
                "SELECT * FROM hold_queue WHERE concept_id = %s AND account_id IS NOT DISTINCT FROM %s "
                "ORDER BY id DESC LIMIT 1",
                (concept_id, account_id),
            ).fetchone()
    except psycopg.Error:
        return None
    return _parse_payload(dict(row)) if row else None


def prompt_scores_for_run(run_id: Optional[str], dsn=None) -> list[dict]:
    """Every gate verdict logged against one run, oldest first -- the
    first-draft score and, after a rework, the revised one -- so the
    reader can see whether the rewrite moved the number. Empty for a
    run that never reached the gate."""
    if not run_id:
        return []
    try:
        with db.connect(dsn) as conn:
            rows = conn.execute(
                "SELECT id, created_at, score, passed, reason, dims, human_verdict "
                "FROM prompt_scores WHERE run_id = %s ORDER BY id",
                (run_id,)).fetchall()
    except psycopg.Error:
        return []
    out = []
    for r in rows:
        row = dict(r)
        try:
            row["dims"] = json.loads(row["dims"]) if row.get("dims") else {}
        except (ValueError, TypeError):
            row["dims"] = {}
        row["passed"] = bool(row.get("passed"))
        out.append(row)
    return out


def gates_for_concepts(concept_ids, dsn=None, *,
                       account_id: Optional[int]) -> dict:
    """The prompt gate's verdict for MANY concepts at once: {concept_id:
    {score, passed, reason, reworks, status, outcome}}, for a board that
    prints a card per concept (2026-09-17).

    The same reading `mcp_server._gate` makes one concept at a time --
    the latest hold row this account owns, its payload's run_id, the
    LAST score that run logged (a rework's revised verdict, not the first
    draft's) -- in TWO queries however long the board is, where calling
    hold_for_concept + prompt_scores_for_run per card would be two
    hundred. A concept with no hold row is absent from the result: no
    graph run ever ended on it (a Studio Create, a capture), which the
    card must be able to tell apart from "scored badly". A run that held
    before it reached the gate is present with score None.

    `passed` is what the gate SAID, never what the run then did: under
    ZEROPAGE_GATES=advisory a failed prompt still proceeds, and this
    still reads False -- the log_prompt_scores rule.

    Never raises and never guesses: a database with no graph history, or
    an unreadable payload, reads as nothing to show."""
    ids = sorted({int(i) for i in concept_ids or [] if i is not None})
    if not ids:
        return {}
    try:
        with db.connect(dsn) as conn:
            # run_id read IN Postgres (2026-09-25). The payload is the
            # run's whole replay record -- prompts, clips, candidates --
            # and this used to fetch it for every card to read one key:
            # ~420 KB of a ~940 KB board. The nested CASE is the "never
            # guesses" rule in SQL: a payload that is not a JSON object
            # reads as no run, exactly as _parse_payload's fallback did,
            # and CASE (unlike AND) evaluates in order, so the cast is
            # never tried on text that would not parse.
            holds = conn.execute(
                "SELECT DISTINCT ON (concept_id) concept_id, status, reason, "
                "CASE WHEN pg_input_is_valid(payload, 'jsonb') THEN "
                "  CASE WHEN jsonb_typeof(payload::jsonb) = 'object' "
                "  THEN payload::jsonb->>'run_id' END "
                "END AS run_id "
                "FROM hold_queue WHERE concept_id = ANY(%s) "
                "AND account_id IS NOT DISTINCT FROM %s "
                "ORDER BY concept_id, id DESC",
                (ids, account_id)).fetchall()
            runs = {}
            for row in holds:
                runs[row["concept_id"]] = (dict(row), row["run_id"])
            wanted = sorted({r for _, r in runs.values() if r})
            scores: dict = {}
            if wanted:
                for r in conn.execute(
                        "SELECT run_id, score, passed, reason FROM prompt_scores "
                        "WHERE run_id = ANY(%s) ORDER BY id", (wanted,)).fetchall():
                    scores.setdefault(r["run_id"], []).append(dict(r))
    except psycopg.Error:
        return {}
    out = {}
    for concept_id, (hold, run_id) in runs.items():
        logged = scores.get(run_id) or []
        latest = logged[-1] if logged else None
        out[concept_id] = {
            "score": latest["score"] if latest else None,
            "passed": bool(latest["passed"]) if latest else None,
            "reason": (latest.get("reason") or "") if latest else "",
            # how many times the gate sent it back before this verdict
            "reworks": max(0, len(logged) - 1),
            "status": hold.get("status") or "held",
            "outcome": hold.get("reason") or "",
        }
    return out


def resolve_hold(hold_id: int, status: str, dsn=None, *,
                 account_id: Optional[int]) -> bool:
    """Your morning verdict on a shadow run: approved (would have
    posted) or rejected (glad it held). This is how the evaluator gets
    graded -- agreement over these rows is the number that earns auto.

    Returns whether a row changed: False for someone else's hold, same
    as for a missing id, so the route above answers 404 for both."""
    if status not in ("approved", "rejected", "posted"):
        raise ValueError(f"status must be approved|rejected|posted, got {status!r}")
    with db.connect(dsn) as conn:
        cursor = conn.execute(
            "UPDATE hold_queue SET status = %s WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (status, hold_id, account_id))
        return cursor.rowcount > 0


def posts_today(channel: str, dsn=None) -> int:
    """Posted rows for this channel since UTC midnight -- what the rate
    cap in the publish gate counts against.

    Deliberately NOT scoped by account: a channel is the installation's
    destination (db.SHARED_TABLES), and its rate cap is a cap on what
    reaches that destination per day, whoever filed the run. The static
    tenancy test allows this statement by name."""
    today = datetime.now(timezone.utc).date().isoformat()
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT COUNT(*) FROM hold_queue "
            "WHERE channel = %s AND status = 'posted' AND created_at >= %s",
            (channel, today),
        ).fetchone()
        return row[0]


def evaluator_agreement(channel: Optional[str] = None, dsn=None, *,
                        account_id: Optional[int]) -> dict:
    """The credit-gate number: of the shadow runs you've graded, how
    often would you have posted what the graph wanted to post? ~0.9
    over a real stretch is the doc's bar for promoting a channel.
    Over THIS account's graded holds -- the grades are one person's
    judgment of the graph, not a pooled score."""
    query = ("SELECT status, COUNT(*) FROM hold_queue "
             "WHERE status IN ('approved', 'rejected') AND account_id IS NOT DISTINCT FROM %s")
    params: tuple = (account_id,)
    if channel:
        query += " AND channel = %s"
        params = (account_id, channel)
    query += " GROUP BY status"
    with db.connect(dsn) as conn:
        # not dict(rows): a db.Row is a mapping, not the 2-tuple
        # sqlite3.Row was, and dict() over mappings pairs their KEYS
        counts = {r[0]: r[1] for r in conn.execute(query, params).fetchall()}
    graded = sum(counts.values())
    return {
        "graded": graded,
        "approved": counts.get("approved", 0),
        "agreement": round(counts.get("approved", 0) / graded, 3) if graded else None,
    }


# --- the prompt gate's log -------------------------------------------------

def log_prompt_scores(run_id, scored: list, dsn=None) -> None:
    """One row per scored prompt per run -- the record the gate-vs-you
    agreement number is computed from. Logged before any credit could
    be spent, pass or fail."""
    with db.connect(dsn) as conn:
        for x in scored:
            conn.execute(
                "INSERT INTO prompt_scores (created_at, run_id, prompt, score, "
                "passed, reason, dims, unreadable) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
                (_now(), run_id, x.get("prompt"), x.get("score"),
                 int(bool(x.get("pass"))), x.get("reason"),
                 json.dumps(x.get("dims", {})),
                 int(bool(x.get("unreadable")))),
            )


def set_prompt_verdicts(run_id, verdict: str, dsn=None) -> int:
    """Your /holds grade written next to the gate's: approved -> 'post',
    rejected -> 'reject'. Returns rows updated (0 when a run predates
    the gate or had no AI shots)."""
    if verdict not in ("post", "reject"):
        raise ValueError(f"verdict must be post|reject, got {verdict!r}")
    if not run_id:
        return 0
    with db.connect(dsn) as conn:
        cursor = conn.execute(
            "UPDATE prompt_scores SET human_verdict = %s WHERE run_id = %s",
            (verdict, run_id),
        )
        return cursor.rowcount


def prompt_gate_agreement(dsn=None) -> dict:
    """Gate vs. you, over the graded rows: (passed AND you'd post) OR
    (held AND you'd reject). The two disagreement types cost
    differently -- passed-but-reject burns a credit, held-but-post only
    costs a manual approval -- so both are broken out."""
    with db.connect(dsn) as conn:
        row = conn.execute(
            # Postgres cannot SUM a boolean; SQLite quietly treated one as 0/1
            "SELECT COUNT(*),"
            " SUM(CASE WHEN (passed = 1 AND human_verdict = 'post') OR"
            "     (passed = 0 AND human_verdict = 'reject') THEN 1 ELSE 0 END),"
            " SUM(CASE WHEN passed = 1 AND human_verdict = 'reject' THEN 1 ELSE 0 END),"
            " SUM(CASE WHEN passed = 0 AND human_verdict = 'post' THEN 1 ELSE 0 END)"
            " FROM prompt_scores WHERE human_verdict IS NOT NULL"
            # A row the judge never rendered a verdict on measures the
            # Gemini API's uptime, not the gate's judgement. Genuine
            # passed = 0 rows stay in, deliberately -- see
            # orchestrator._gate_advisory on why the scores themselves
            # are never massaged.
            " AND unreadable = 0"
        ).fetchone()
    graded, agreed, expensive, cheap = (row[0], row[1] or 0, row[2] or 0, row[3] or 0)
    return {
        "graded": graded,
        "agreement": round(agreed / graded, 3) if graded else None,
        "passed_but_rejected": expensive,   # would have burned a credit
        "held_but_posted": cheap,           # only cost an approval
    }


def first_try_pass_rate(dsn=None) -> dict:
    """Purely descriptive: how often the gate lets a render through.
    Not the trust number -- that's prompt_gate_agreement."""
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT COUNT(*), SUM(passed) FROM prompt_scores "
            "WHERE unreadable = 0"
        ).fetchone()
    total, passed = row[0], row[1] or 0
    return {"total": total, "passed": passed,
            "rate": round(passed / total, 3) if total else None}


# --- corrections (for the human_note interrupt, when it lands) ------------

def add_correction(note: str, run_id: Optional[str] = None, dsn=None) -> int:
    with db.connect(dsn) as conn:
        row = conn.execute(
            "INSERT INTO corrections (created_at, run_id, note) VALUES (%s, %s, %s) "
            "RETURNING id",
            (_now(), run_id, note),
        ).fetchone()
        return int(row["id"])


def pending_corrections(dsn=None) -> list[dict]:
    with db.connect(dsn) as conn:
        return [dict(r) for r in conn.execute(
            "SELECT * FROM corrections WHERE consumed = 0 ORDER BY created_at"
        )]


def consume_correction(correction_id: int, dsn=None) -> None:
    with db.connect(dsn) as conn:
        conn.execute("UPDATE corrections SET consumed = 1 WHERE id = %s", (correction_id,))
