"""
Stripe in front of the ledger (2026-09-18, phase 2 of
docs/tasks/task-stripe-billing.md; Mike: "make stripe in front of ledger").

A person signs in, buys a plan or a top-up with a card, and renders. The
money side of that is three things, and this module is the middle one:

  the ledger (src/ledger.py)   what an account has -- built, tested, and
                               since today actually HELD against by every
                               adapter (src/charge.py)
  THIS MODULE                  the pure half of Stripe: which Price is which
                               plan, what a webhook event means for the
                               ledger, and the Checkout / Portal calls
  app/billing.py               the HTTP half: the webhook route (outside
                               /api -- Stripe cannot sign in) and the
                               customer-facing routes under /api/billing

THE FACTS THIS IS BUILT ON, all decided before it (the task doc, section 0):

- Webhook idempotency is the ledger's unique index on (account_id, kind,
  source_ref): the same event delivered twice calls grant() twice and the
  second call returns the first lot. No second guard is built here.
- Stripe customer -> account is `accounts.stripe_customer_id`, written
  the first time a checkout for that account completes. An event for a
  customer nobody knows is LOGGED AND ACKED (200) -- never retried
  forever, never guessed at.
- grant() raises by design. A real failure is a 500 so Stripe retries;
  only unknown-customer and unhandled-type are 200s.
- A subscription lot is granted per PAID INVOICE with the invoice id as
  its source_ref -- one per billing period, which is what makes "your
  monthly allowance" a monthly lot with the ledger's own expiry.
- `charge.refunded` does NOT claw credit back (the documented decision):
  a refund is the operator's call, made through Stripe, and the ledger
  keeps what was granted so the trail stays whole. Log it.
- A YEARLY invoice is a schedule, not a lot (second pass, same day). The
  ledger expires a lot two months after it lands, so twelve months of
  credit on one invoice would die ten months early. `invoice.paid` on a
  yearly Price grants month one and writes one `credit_schedules` row;
  `release_due` grants each later month as its own lot -- source_ref
  `<invoice>:m<n>`, so a release is idempotent through the same unique
  index -- from a cron (`python -m src.billing release`), and lazily
  from `balance()` and `charge.Charge.take()`, so a dead cron never
  hides a month somebody paid for. A lapse cancels the schedule.

CONFIGURATION is environment only, never a table: STRIPE_SECRET_KEY,
STRIPE_WEBHOOK_SECRET, and one STRIPE_PRICE_* per plan and pack
(pricing.PLANS / pricing.TOPUP name them). `configured()` is what the
routes and the site ask; an unconfigured install answers 503 with the
variable to set, and the plan buttons say "checkout not configured"
rather than pointing at a dead link. Test-mode keys until the whole flow
has passed end to end.

Every network call is behind `_stripe()` so the suite -- which blocks
the network -- exercises everything else with events built as fixtures
and signed with the test secret (stripe's own construct_event runs for
real; see tests/test_billing.py).
"""

from __future__ import annotations

import os
import sys
from typing import Any, Optional

from . import accounts, db, ledger, pricing

SECRET_ENV = "STRIPE_SECRET_KEY"
WEBHOOK_ENV = "STRIPE_WEBHOOK_SECRET"
RETURN_ENV = "BILLING_RETURN_URL"

# The events this module acts on. Anything else is acknowledged and
# ignored -- Stripe sends dozens of types and a webhook that 500s on a
# type it never asked for is a webhook Stripe eventually disables.
HANDLED_EVENTS = (
    "checkout.session.completed",
    "invoice.paid",
    "customer.subscription.deleted",
    "customer.subscription.updated",
    "charge.refunded",
)
# subscription statuses at which the allowance dies (LAPSE_POLICY decides
# which lots); "past_due" is deliberately NOT here -- Stripe is still
# retrying the card and the person is still a customer
LAPSED_STATUSES = ("canceled", "unpaid", "incomplete_expired")


# --------------------------------------------------------------------------
# the yearly schedule -- an OWNED table (db.OWNED_TABLES)
# --------------------------------------------------------------------------
# One row per yearly invoice: how many months it bought, how many have
# landed, and when the next one is due. `months_released` counts month
# one, granted the moment the invoice is paid. `cancelled_at` stops the
# releases without deleting the record of what was paid for.
SCHEMA = """
CREATE TABLE IF NOT EXISTS credit_schedules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT,
    plan             TEXT NOT NULL,
    source_ref       TEXT NOT NULL,
    credits_per_month BIGINT NOT NULL,
    months_total     INTEGER NOT NULL,
    months_released  INTEGER NOT NULL DEFAULT 0,
    started_at       TEXT NOT NULL,
    next_release_at  TEXT,
    cancelled_at     TEXT,
    created_at       TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS credit_schedules_source_idx
    ON credit_schedules (account_id, source_ref);
CREATE INDEX IF NOT EXISTS credit_schedules_due_idx
    ON credit_schedules (next_release_at) WHERE cancelled_at IS NULL;
"""


def init(dsn: Optional[str] = None) -> None:
    """Create the schedule table and own it. Idempotent; registered in
    app/main.py's lifespan and tests/test_tenancy.py::_init_everything."""
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA)
        db.own_table(conn, "credit_schedules")


def month_ref(source_ref: str, month: int) -> str:
    return f"{source_ref}:m{month}"


def schedule_year(account_id: int, plan: "pricing.Plan", source_ref: str, *,
                  months: int = pricing.MONTHS_PER_YEAR, now: Optional[str] = None,
                  dsn: Optional[str] = None) -> dict:
    """A yearly invoice was paid: grant month one now and record the
    other eleven. Idempotent on (account, source_ref): a redelivered
    invoice finds its row and grants nothing twice (the month-one lot's
    own unique index is the backstop)."""
    init(dsn)
    now = now or ledger._now()
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT id FROM credit_schedules WHERE account_id IS NOT DISTINCT FROM %s "
            "AND source_ref = %s", (account_id, source_ref)).fetchone()
        if row is None:
            conn.execute(
                "INSERT INTO credit_schedules (account_id, plan, source_ref, credits_per_month, "
                "months_total, months_released, started_at, next_release_at, created_at) "
                "VALUES (%s, %s, %s, %s, %s, 0, %s, %s, %s)",
                (account_id, plan.key, source_ref, plan.credits, int(months), now, now, now))
    released = release_due(account_id, now=now, dsn=dsn)
    return {"scheduled": int(months), "released_now": released}


def release_due(account_id: Optional[int] = None, *, now: Optional[str] = None,
                dsn: Optional[str] = None) -> int:
    """Grant every scheduled month whose date has come, for one account or
    (None) for everyone. Returns lots granted. Each month is its own
    `subscription` lot with the ledger's own expiry, source_ref
    `<invoice>:m<n>`, so calling this twice grants once. grant() raises
    by design; a failure leaves the schedule where it was and the next
    run picks it up."""
    init(dsn)
    now = now or ledger._now()
    granted = 0
    with db.connect(dsn) as conn:
        if account_id is None:
            rows = conn.execute(
                "SELECT * FROM credit_schedules WHERE cancelled_at IS NULL "
                "AND next_release_at IS NOT NULL AND next_release_at <= %s "
                "ORDER BY id", (now,)).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM credit_schedules WHERE account_id IS NOT DISTINCT FROM %s "
                "AND cancelled_at IS NULL AND next_release_at IS NOT NULL "
                "AND next_release_at <= %s ORDER BY id", (account_id, now)).fetchall()
        due = [dict(r) for r in rows]
    for sched in due:
        plan = pricing.PLANS.get(sched["plan"])
        while (sched["next_release_at"] is not None and sched["next_release_at"] <= now
               and sched["months_released"] < sched["months_total"]):
            n = int(sched["months_released"]) + 1
            ledger.grant(sched["account_id"], int(sched["credits_per_month"]), "subscription",
                         source_ref=month_ref(sched["source_ref"], n),
                         note=f"stripe yearly {sched['source_ref']} month {n}/{sched['months_total']}"
                              + (f" ({plan.key})" if plan else ""),
                         granted_at=sched["next_release_at"], dsn=dsn)
            granted += 1
            done = n >= int(sched["months_total"])
            next_at = None if done else ledger._plus_months(sched["started_at"], n)
            with db.connect(dsn) as conn:
                conn.execute(
                    "UPDATE credit_schedules SET months_released = %s, next_release_at = %s "
                    "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
                    (n, next_at, sched["id"], sched["account_id"]))
            sched["months_released"], sched["next_release_at"] = n, next_at
    return granted


def cancel_schedules(account_id: int, *, now: Optional[str] = None,
                     dsn: Optional[str] = None) -> int:
    """The subscription ended: no further months land. Returns rows
    cancelled. What was already released is the ledger's (LAPSE_POLICY
    decides its fate in on_subscription_lapsed)."""
    init(dsn)
    with db.connect(dsn) as conn:
        cur = conn.execute(
            "UPDATE credit_schedules SET cancelled_at = %s "
            "WHERE account_id IS NOT DISTINCT FROM %s AND cancelled_at IS NULL",
            (now or ledger._now(), account_id))
        return int(cur.rowcount or 0)


def schedules(account_id: int, *, dsn: Optional[str] = None) -> list[dict]:
    init(dsn)
    with db.connect(dsn) as conn:
        rows = conn.execute(
            "SELECT * FROM credit_schedules WHERE account_id IS NOT DISTINCT FROM %s "
            "ORDER BY id", (account_id,)).fetchall()
        return [dict(r) for r in rows]


class BillingUnconfigured(RuntimeError):
    def __init__(self, what: str):
        super().__init__(f"{what} is not set -- Stripe checkout is not configured on this install")
        self.what = what


class UnknownCustomer(LookupError):
    """An event for a Stripe customer no account pays as."""


def configured() -> bool:
    return bool((os.environ.get(SECRET_ENV) or "").strip())


def webhook_configured() -> bool:
    return bool((os.environ.get(WEBHOOK_ENV) or "").strip())


def _log(message: str) -> None:
    print(f"[billing] {message}", file=sys.stderr)


# --------------------------------------------------------------------------
# prices <-> plans
# --------------------------------------------------------------------------

def products() -> dict[str, Any]:
    """Every buyable thing by key: the three plans and the top-up."""
    out: dict[str, Any] = dict(pricing.PLANS)
    out[pricing.TOPUP.key] = pricing.TOPUP
    return out


INTERVALS = ("month", "year")


def price_env_for(key: str, interval: str = "month") -> Optional[str]:
    """The env var naming the Stripe Price for this item at this interval.
    The top-up has no interval; a plan has one per INTERVALS."""
    item = products().get(key)
    if item is None:
        return None
    if not is_plan(key):
        return item.price_env
    if interval not in INTERVALS:
        return None
    return item.price_env if interval == "month" else item.price_env_yearly


def price_id(key: str, interval: str = "month") -> Optional[str]:
    """The Stripe Price for a plan (at an interval) or the pack, from its
    named env var, or None when that var is unset -- which the checkout
    reports as unconfigured rather than sending a person to a Price that
    does not exist."""
    env = price_env_for(key, interval)
    if not env:
        return None
    return (os.environ.get(env) or "").strip() or None


def key_for_price(price: Optional[str]) -> Optional[str]:
    """The plan or pack a Stripe Price id sells, or None."""
    found = item_for_price(price)
    return found[0] if found else None


def item_for_price(price: Optional[str]) -> Optional[tuple[str, str]]:
    """(key, interval) for a Stripe Price id -- "month" for the pack and
    the monthly Prices, "year" for a yearly one. Read off the environment
    at call time so a rotated Price takes effect on the next event, not
    the next deploy."""
    if not price:
        return None
    for key in products():
        for interval in INTERVALS:
            env = price_env_for(key, interval)
            if env and (os.environ.get(env) or "").strip() == price:
                return key, interval
    return None


def is_plan(key: Optional[str]) -> bool:
    return key in pricing.PLANS


# --------------------------------------------------------------------------
# checkout / portal -- the only network here
# --------------------------------------------------------------------------

def _stripe():
    if not configured():
        raise BillingUnconfigured(SECRET_ENV)
    import stripe  # imported lazily: the suite never needs it configured

    stripe.api_key = os.environ[SECRET_ENV].strip()
    return stripe


def return_url(path: str = "/pricing") -> str:
    """Where Checkout and the Portal send the person back to: the public
    site (BILLING_RETURN_URL, else STUDIO_URL, else SITE_URL) plus a
    path. The pricing page lives on the Next site, not on this origin."""
    base = (os.environ.get(RETURN_ENV) or os.environ.get("STUDIO_URL")
            or os.environ.get("SITE_URL") or "http://127.0.0.1:3000").strip().rstrip("/")
    return f"{base}{path}"


def _customer_for(account_id: int, email: Optional[str], dsn: Optional[str] = None) -> str:
    """The Stripe customer this account pays as, created on first use and
    bound to the row so every later event resolves to this tenant."""
    have = accounts.stripe_customer_of(account_id, dsn=dsn)
    if have:
        return have
    stripe = _stripe()
    customer = stripe.Customer.create(
        email=email or None,
        metadata={"account_id": str(account_id)},
    )
    accounts.set_stripe_customer(account_id, customer["id"], dsn=dsn)
    return customer["id"]


def checkout_url(account_id: int, key: str, *, interval: str = "month",
                 email: Optional[str] = None, dsn: Optional[str] = None) -> str:
    """A Stripe Checkout Session URL for one plan (monthly or yearly) or
    the pack. Raises BillingUnconfigured (no key, or no Price for this
    item at this interval) and ValueError (no such item / interval)."""
    item = products().get(key)
    if item is None:
        raise ValueError(f"no such plan or pack: {key!r}")
    interval = (interval or "month").strip().lower()
    if interval not in INTERVALS:
        raise ValueError(f"interval must be one of {INTERVALS}, not {interval!r}")
    price = price_id(key, interval)
    if not price:
        raise BillingUnconfigured(price_env_for(key, interval) or item.price_env)
    stripe = _stripe()
    customer = _customer_for(account_id, email, dsn=dsn)
    mode = "subscription" if is_plan(key) else "payment"
    session = stripe.checkout.Session.create(
        mode=mode,
        customer=customer,
        line_items=[{"price": price, "quantity": 1}],
        success_url=return_url("/pricing?checkout=success"),
        cancel_url=return_url("/pricing?checkout=cancelled"),
        client_reference_id=str(account_id),
        # the webhook reads these back: which account, which item -- so a
        # one-time pack can be granted without a second API call to list
        # the session's line items
        metadata={"account_id": str(account_id), "item": key, "interval": interval},
        **({"subscription_data": {"metadata": {"account_id": str(account_id), "item": key,
                                               "interval": interval}}}
           if mode == "subscription" else
           {"payment_intent_data": {"metadata": {"account_id": str(account_id), "item": key}}}),
        allow_promotion_codes=True,
    )
    return session["url"]


def portal_url(account_id: int, *, dsn: Optional[str] = None) -> str:
    """The Customer Portal (change plan, cancel, invoices). Raises
    BillingUnconfigured; ValueError when the account has never paid."""
    customer = accounts.stripe_customer_of(account_id, dsn=dsn)
    if not customer:
        raise ValueError("this account has no billing yet -- choose a plan first")
    stripe = _stripe()
    session = stripe.billing_portal.Session.create(
        customer=customer, return_url=return_url("/pricing"))
    return session["url"]


# --------------------------------------------------------------------------
# the webhook -- verify, then act
# --------------------------------------------------------------------------

def verify(payload: bytes, signature: Optional[str]) -> dict:
    """The event, as a dict, or raise. stripe.Webhook.construct_event does
    the HMAC and the timestamp tolerance; this only supplies the secret.
    Raises BillingUnconfigured (no secret) or ValueError (bad signature
    or body)."""
    secret = (os.environ.get(WEBHOOK_ENV) or "").strip()
    if not secret:
        raise BillingUnconfigured(WEBHOOK_ENV)
    import json

    import stripe
    from stripe import SignatureVerificationError

    try:
        stripe.Webhook.construct_event(payload, signature or "", secret)
    except SignatureVerificationError as e:
        raise ValueError(f"bad signature: {e}") from e
    except ValueError as e:
        raise ValueError(f"bad payload: {e}") from e
    # the verified bytes, as plain data: handle_event wants dicts, not the
    # SDK's resource objects, so the fixtures in the suite are the wire shape
    return json.loads(payload.decode("utf-8"))


def _account_for(obj: dict, dsn: Optional[str]) -> int:
    """The account an event's object belongs to: the customer binding
    first, the metadata the checkout wrote second (the FIRST checkout is
    what creates the binding, so its own event may arrive before it)."""
    customer = obj.get("customer")
    if isinstance(customer, dict):
        customer = customer.get("id")
    if customer:
        found = accounts.account_for_stripe_customer(customer, dsn=dsn)
        if found is not None:
            return found
    meta = obj.get("metadata") or {}
    ref = meta.get("account_id") or obj.get("client_reference_id")
    if ref:
        try:
            account_id = int(ref)
        except (TypeError, ValueError):
            account_id = None
        if account_id is not None:
            if customer:
                try:
                    accounts.set_stripe_customer(account_id, customer, dsn=dsn)
                except ValueError as e:
                    _log(f"could not bind customer {customer} to account {account_id}: {e}")
            return account_id
    raise UnknownCustomer(f"no account pays as customer {customer!r}")


def _line_price(obj: dict) -> Optional[str]:
    """The Price id on an invoice's first line, whichever shape Stripe
    sent it in (a string id, or the expanded object)."""
    lines = (obj.get("lines") or {}).get("data") or []
    for line in lines:
        price = line.get("price") or (line.get("pricing") or {}).get("price_details", {}).get("price")
        if isinstance(price, dict):
            price = price.get("id")
        if price:
            return price
    return None


def handle_event(event: dict, *, dsn: Optional[str] = None) -> dict:
    """Act on ONE verified event. Returns what happened, for the route to
    log and answer with. Raises UnknownCustomer (route: 200 + log) and
    lets ledger errors propagate (route: 500, Stripe retries).

    Pure against the database -- no Stripe call is made here, which is
    what makes it testable with fixture events.
    """
    kind = event.get("type") or ""
    obj = ((event.get("data") or {}).get("object")) or {}
    if kind not in HANDLED_EVENTS:
        return {"type": kind, "action": "ignored"}

    if kind == "checkout.session.completed":
        account_id = _account_for(obj, dsn)
        item = (obj.get("metadata") or {}).get("item")
        if obj.get("mode") == "payment":
            pack = products().get(item or "")
            if pack is None or is_plan(item):
                _log(f"checkout {obj.get('id')} paid for unknown item {item!r} -- not granted")
                return {"type": kind, "action": "unknown_item", "account_id": account_id}
            ref = obj.get("payment_intent") or obj.get("id")
            lot = ledger.grant(account_id, pack.credits, "purchase", source_ref=str(ref),
                               note=f"stripe checkout {obj.get('id')} ({pack.key})", dsn=dsn)
            return {"type": kind, "action": "granted", "account_id": account_id,
                    "credits": pack.credits, "lot": lot}
        # a subscription checkout: the plan is recorded now, the credit
        # arrives with invoice.paid (which Stripe sends for the first
        # period too, so nothing is granted twice)
        if is_plan(item):
            accounts.set_plan(account_id, item, dsn=dsn)
        return {"type": kind, "action": "subscribed", "account_id": account_id, "plan": item}

    if kind == "invoice.paid":
        account_id = _account_for(obj, dsn)
        found = item_for_price(_line_price(obj))
        meta = ((obj.get("subscription_details") or {}).get("metadata")
                or obj.get("metadata") or {})
        key, interval = found if found else (meta.get("item"), meta.get("interval") or "month")
        plan = pricing.PLANS.get(key or "")
        if plan is None:
            _log(f"invoice {obj.get('id')} paid for no known plan (price "
                 f"{_line_price(obj)!r}) -- not granted")
            return {"type": kind, "action": "unknown_plan", "account_id": account_id}
        accounts.set_plan(account_id, plan.key, dsn=dsn)
        if interval == "year":
            # a schedule, not a lot: month one now, eleven more on their dates
            done = schedule_year(account_id, plan, str(obj.get("id")), dsn=dsn)
            return {"type": kind, "action": "scheduled", "account_id": account_id,
                    "plan": plan.key, "credits": plan.credits, **done}
        lot = ledger.grant(account_id, plan.credits, "subscription", source_ref=str(obj.get("id")),
                           note=f"stripe invoice {obj.get('id')} ({plan.key})", dsn=dsn)
        return {"type": kind, "action": "granted", "account_id": account_id,
                "plan": plan.key, "credits": plan.credits, "lot": lot}

    if kind in ("customer.subscription.deleted", "customer.subscription.updated"):
        account_id = _account_for(obj, dsn)
        status = obj.get("status")
        if kind == "customer.subscription.updated" and status not in LAPSED_STATUSES:
            # a plan change lands here too: keep the plan column current
            key = key_for_price(_line_price(obj.get("items") and {"lines": obj["items"]} or {}))
            if is_plan(key):
                accounts.set_plan(account_id, key, dsn=dsn)
                return {"type": kind, "action": "plan_changed", "account_id": account_id, "plan": key}
            return {"type": kind, "action": "noted", "account_id": account_id, "status": status}
        expired = ledger.on_subscription_lapsed(account_id, dsn=dsn)
        stopped = cancel_schedules(account_id, dsn=dsn)
        accounts.set_plan(account_id, None, dsn=dsn)
        return {"type": kind, "action": "lapsed", "account_id": account_id,
                "credits_expired": expired, "schedules_cancelled": stopped}

    if kind == "charge.refunded":
        # documented decision: no clawback -- see the module docstring
        try:
            account_id = _account_for(obj, dsn)
        except UnknownCustomer:
            account_id = None
        _log(f"charge {obj.get('id')} refunded ({obj.get('amount_refunded')} cents) for "
             f"account {account_id!r} -- credit NOT clawed back; adjust by hand if wanted")
        return {"type": kind, "action": "logged", "account_id": account_id}

    return {"type": kind, "action": "ignored"}  # pragma: no cover


# --------------------------------------------------------------------------
# what the UI shows
# --------------------------------------------------------------------------

def balance(account_id: int, *, dsn: Optional[str] = None) -> dict:
    """Available, committed and the lots, plus the plan -- the numbers the
    studio's account row and the pricing page's "your plan" state print."""
    release_due(account_id, dsn=dsn)          # a month that is due lands before it is counted
    plan_key = accounts.plan_of(account_id, dsn=dsn)
    plan = pricing.PLANS.get(plan_key or "")
    pending = [{"plan": s["plan"], "months_released": s["months_released"],
                "months_total": s["months_total"], "next_release_at": s["next_release_at"]}
               for s in schedules(account_id, dsn=dsn)
               if s["cancelled_at"] is None and s["next_release_at"] is not None]
    lots = [{"id": lot["id"], "kind": lot["kind"],
             "credits": lot["credits_granted"],
             "remaining": lot["credits_remaining"], "granted_at": lot["granted_at"],
             "expires_at": lot["expires_at"]}
            for lot in ledger.lots(account_id, dsn, include_expired=False)]
    return {
        "available": ledger.available(account_id, dsn),
        "outstanding": ledger.outstanding(account_id, dsn),
        "plan": ({"key": plan.key, "name": plan.name, "tier": plan.tier,
                  "credits": plan.credits, "monthly_usd": plan.monthly_usd}
                 if plan else None),
        "exempt": accounts.is_credit_exempt(account_id, dsn=dsn),
        "lots": lots,
        "schedules": pending,
        "checkout_configured": configured() and all(price_id(k) for k in pricing.PLANS),
        "yearly_configured": configured() and all(price_id(k, "year") for k in pricing.PLANS),
        "portal": bool(accounts.stripe_customer_of(account_id, dsn=dsn)),
    }


def main(argv: Optional[list[str]] = None) -> None:
    """`python -m src.billing release` -- grant every scheduled month whose
    date has come, for everyone. Cron-safe: idempotent, prints a count."""
    import argparse
    parser = argparse.ArgumentParser(prog="python -m src.billing")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("release", help="grant every yearly-plan month that is due (run daily)")
    args = parser.parse_args(argv)
    if args.command == "release":
        n = release_due()
        print(f"released {n} scheduled month{'s' if n != 1 else ''}")


if __name__ == "__main__":  # pragma: no cover
    main()


__all__ = [
    "SECRET_ENV", "WEBHOOK_ENV", "RETURN_ENV", "HANDLED_EVENTS", "LAPSED_STATUSES", "INTERVALS",
    "BillingUnconfigured", "UnknownCustomer",
    "init", "schedule_year", "release_due", "cancel_schedules", "schedules", "month_ref",
    "configured", "webhook_configured", "products", "price_env_for", "price_id",
    "key_for_price", "item_for_price", "is_plan",
    "checkout_url", "portal_url", "return_url", "verify", "handle_event", "balance", "main",
]
