"""
The spine: what got pitched, what got shot, how it did.

Four tables:

    pitch_runs - one execution of pitch.py against a manifest
    ideas      - one pitch. 10 per run. `selected` records your choice.
    videos     - something you actually posted
    metrics    - a snapshot of how a video was doing at one moment

Two design decisions worth knowing.

`selected` on ideas exists because pitch.py generates 10 and you pick a
few. That choice is a human label. Ten pitches from the same manifest
under the same prompt, three marked good, seven not — that is a
preference set, and it is the only source of ground truth in this
system that does not require waiting for a video to be posted.

`metrics` is its own table because numbers change. A video has 8k views
on day one and 40k on day thirty. Overwrite the row and you lose the
growth curve, and you can no longer compare a video posted yesterday
against one posted last year. Snapshots let you ask "how did each look
at 7 days old", which is the only fair comparison.

Postgres since 2026-09-03 (docs/tasks/task-postgres-migration.md, step 1
of the module order). It was SQLite for a year because that needed no
setup; it moved because row-level security is the structural fix for the
owner-predicate class of bug the pilot dry run found, and RLS wants a
real server. Postgres ONLY -- no dual code path. The connection URL is
`DATABASE_URL` (the name docs/DEPLOY_FLY.md already uses), and every
function takes `dsn` where it used to take `path`. `DB_PATH` still names
the legacy SQLite file: the data copy reads from it, and the modules not
yet ported still import it.

The dialect choices, each from the migration doc's translation table:
`%s` placeholders; `IS NOT DISTINCT FROM` where SQLite had `IS ?` (a
plain `=` silently drops every NULL-owned row -- a different bug from
the one tenancy fixed); `RETURNING id` instead of `lastrowid`;
identity columns are `GENERATED BY DEFAULT AS IDENTITY` (Mike's call,
2026-09-03: `ALWAYS` refuses the explicit ids the SQLite data copy has
to preserve); `julianday(a) - julianday(b)` is
`extract(epoch from (a::timestamptz - b::timestamptz)) / 86400`, which
is only equivalent with the session in UTC -- connect() sets that,
because a date-only `posted_at` cast in a local-time session would be
hours off from a full ISO `captured_at` carrying `+00:00`.
"""

from __future__ import annotations

import hashlib
import json
import os
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterator, Optional, Sequence

import psycopg

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# The legacy SQLite file. Nothing in this module reads or writes it any
# more; it stays named because (a) the one-off SQLite -> Postgres data
# copy reads from it and (b) the modules not yet ported still import it.
# Delete it with the last `db.DB_PATH` reference.
DB_PATH = PROJECT_ROOT / "data" / "pipeline.db"

# What docker-compose.yml serves, and what the throwaway test box is.
# `DATABASE_URL` in .env overrides it; a deployment sets it to Supabase.
DEFAULT_DSN = "postgresql://zeropage:zeropage@localhost:5432/zeropage"

PLATFORMS = ("instagram", "tiktok", "youtube")

# How far a snapshot may sit from the requested age and still count as a
# reading "at" that age, as a fraction of at_days. Without this, the
# closest snapshot always wins however far off it is, so a video measured
# on day 1 gets ranked against one measured on day 90 and the benchmark
# colouring is comparing two different questions. Proportional rather
# than fixed: two days' slip matters at day 7 and is noise at day 90.
AGE_TOLERANCE = 0.5


SCHEMA = """
CREATE TABLE IF NOT EXISTS pitch_runs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TEXT    NOT NULL,
    model         TEXT,
    clip_count    INTEGER,
    brief_hash    TEXT,
    settings_hash TEXT,
    prompt_hash   TEXT,
    notes         TEXT
);

CREATE TABLE IF NOT EXISTS ideas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         BIGINT REFERENCES pitch_runs(id) ON DELETE CASCADE,
    number         INTEGER,
    title          TEXT    NOT NULL,
    logline        TEXT,
    story_note     TEXT,
    hook_clip      TEXT,
    selected       INTEGER NOT NULL DEFAULT 0,
    trend_informed INTEGER NOT NULL DEFAULT 0,
    notes          TEXT
);

CREATE TABLE IF NOT EXISTS videos (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idea_id    BIGINT REFERENCES ideas(id) ON DELETE SET NULL,
    -- The concept that produced this post (2026-08-31). Deliberately NOT
    -- a REFERENCES: shoot_concepts is created by preprod.init, which runs
    -- AFTER this schema, so a declared foreign key here fails every insert
    -- with "no such table: main.shoot_concepts". The link is enforced by
    -- the writer, not the schema -- same trade db.py already makes for
    -- being the spine that loads first.
    concept_id BIGINT,
    title      TEXT    NOT NULL,
    platform   TEXT    NOT NULL,
    posted_at  TEXT    NOT NULL,
    url        TEXT,
    timeline   TEXT,
    topic      TEXT,
    hook_type  TEXT,
    duration_s DOUBLE PRECISION,
    notes      TEXT,
    brand      TEXT,
    -- Nullable: NULL is the unowned pool (rows that predate tenancy, and
    -- every fixture database with no seeded account). The REFERENCES
    -- accounts(id) is not inline because accounts.SCHEMA lives in
    -- accounts.py, which imports this module -- own_table() below adds
    -- the constraint right after, once _ensure_accounts_table has run.
    account_id BIGINT
);

CREATE TABLE IF NOT EXISTS metrics (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id           BIGINT  NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    captured_at        TEXT    NOT NULL,
    views              INTEGER,
    likes              INTEGER,
    comments           INTEGER,
    saves              INTEGER,
    shares             INTEGER,
    watch_time_seconds DOUBLE PRECISION,
    UNIQUE (video_id, captured_at)
);

CREATE INDEX IF NOT EXISTS idx_ideas_run       ON ideas (run_id);
CREATE INDEX IF NOT EXISTS idx_ideas_selected  ON ideas (selected);
CREATE INDEX IF NOT EXISTS idx_videos_platform ON videos (platform);
CREATE INDEX IF NOT EXISTS idx_metrics_video   ON metrics (video_id);
"""

# Age of a snapshot in days, the julianday() difference translated. Both
# columns are ISO text: `posted_at` is usually date-only, `captured_at`
# usually a full timestamp. The cast reads both, and connect() pins the
# session to UTC so a date-only value means midnight UTC the way SQLite's
# julianday() always did.
_AGE_DAYS = (
    "extract(epoch from (m.captured_at::timestamptz"
    " - v.posted_at::timestamptz)) / 86400"
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _hash(text: str | None) -> str | None:
    """Short content hash, so you can tell which prompt version produced what."""
    if text is None:
        return None
    return hashlib.sha256(text.encode()).hexdigest()[:12]


class Row(dict):
    """A result row: a dict by column name AND a sequence by position.

    That is the sqlite3.Row contract every caller was written against --
    `row["id"]`, `row[0]`, `dict(row)` -- and psycopg's stock factories
    give one or the other, never both.

    The positions are kept as their own tuple, not read back out of the
    dict: `SELECT COUNT(*), SUM(a), SUM(b)` names its columns `count`,
    `sum`, `sum`, and a dict keeps one `sum`. Reading `row[2]` off the
    dict's values was an IndexError (autonomy.prompt_gate_agreement).
    """

    __slots__ = ("_values",)

    def __init__(self, names, values):
        super().__init__(zip(names, values))
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)

    # Iterating and unpacking yield VALUES, as sqlite3.Row did:
    # `prompt, params = conn.execute(...).fetchone()` is a pattern the
    # tests use. dict(row), row.keys(), `k in row` and **row still see
    # the mapping -- CPython's dict() takes the generic keys() path once
    # __iter__ is overridden, and that path is correct here.
    def __iter__(self):
        return iter(self._values)

    def __len__(self):
        return len(self._values)


def _row_factory(cursor):
    names = [d.name for d in cursor.description] if cursor.description else []

    def make(values):
        return Row(names, values)

    return make


def resolve_dsn(dsn: Optional[str] = None) -> str:
    """The connection URL: an explicit one, else DATABASE_URL, else the
    compose box."""
    return dsn or os.environ.get("DATABASE_URL") or DEFAULT_DSN


@contextmanager
def connect(dsn: Optional[str] = None) -> Iterator[psycopg.Connection]:
    """Commits on success, rolls back on error, always closes."""
    conn = psycopg.connect(resolve_dsn(dsn), row_factory=_row_factory)
    try:
        # See _AGE_DAYS: the date arithmetic is only right in UTC.
        conn.execute("SET TIME ZONE 'UTC'")
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


# --------------------------------------------------------------------------
# tenancy -- every owned row carries the account that owns it
# --------------------------------------------------------------------------

# The tables whose rows belong to one account rather than to the
# installation. Every SELECT against one of these needs an account_id
# predicate; tests/test_tenancy.py asserts that none is missing.
#
# `accounts` IS the brand table (accounts.seed creates zeropage and
# antihero), so account_id is the scoping key and the `brand` TEXT column
# is a label carried alongside it, not the boundary. See
# docs/tasks/task-account-tenancy.md.
OWNED_TABLES = (
    "shoot_concepts",
    "locations",
    "characters",
    "props",
    "generations",
    "videos",
    "scene_briefs",
    "shots",
    # The two the dry run found (docs/PILOT_DRY_RUN.md, 2026-09-02). They
    # were never on this list, so the static SQL test -- which audits the
    # list -- could not see that any signed-in user read Mike's publishing
    # queue and could delete his Director canvases.
    "hold_queue",
    "workflows",
    # main's assets archive (9444f23), decided at the merge (2026-09-02):
    # a generated asset is one account's paid render
    "generated_assets",
)

# The tables that are global BY DECISION, each with the reason. This is
# the other half of OWNED_TABLES: every table a user's actions write rows
# into is either owned (above, with an account_id and a predicate on
# every query) or named here. tests/test_tenancy.py enumerates the live
# schema and fails on a table in neither, so a future session cannot
# "finish the migration" by scoping the shared brain, and cannot add a
# new table without deciding which side it lands on.
#
# Mike's decision (BACKLOG #11, 2026-09-01): "the learning loop continues
# for all users, the entire app learns as it goes and gets better, that
# is the loop." A label is not a fence -- rag_documents.project ranks a
# tenant's own lessons first without hiding anyone else's.
SHARED_TABLES = {
    # -- the auth schema itself: it defines tenancy, it is not subject to it
    "users": "the profile mirror of Supabase's auth.users; ownership is "
             "derived FROM this table (identities and passwords are Supabase's)",
    "accounts": "the tenant/brand table every account_id points at",
    "account_members": "the membership grant; the gate, not a row someone owns",
    # -- the shared brain: learning tables global by Mike's decision
    "winning_prompts": "taught prompts; the lesson is shared, ranked by "
                       "rag_documents.project rather than fenced",
    "prompt_scores": "the credit gate's own log, one row per scored prompt; "
                     "gate-vs-human agreement is a number about the gate",
    "scout_findings": "the research bank; a direction is not anyone's row",
    "scout_bin": "the scout's reference bin, keyed by pass, not by person",
    "inspiration_accounts": "the researched accounts a brand draws on",
    "eval_golden": "the retrieval eval's labelled queries; measure the store",
    "eval_runs": "the retrieval eval's run history; measures the store",
    "crag_retrievals": "CRAG's per-retrieval telemetry (93c49ff); measures the "
                       "store and the rewrite, not anyone's rows",
    # -- reached only through an owned row, so no owner of their own
    "concept_locations": "join table under shoot_concepts; cascades with it",
    "metrics": "snapshots under videos; every read joins v.account_id",
    # -- the installation's own configuration and bookkeeping
    "settings": "the kill switch and the Dev Studio tunables; one installation",
    "channels": "publish destinations bound to the INSTALLATION's credentials "
                "(IG_USER_ID, IG_ACCESS_TOKEN are env, not rows). A channel is "
                "created only by autonomy.init's seed, so a tenant with no "
                "channel row has no post targets and cannot reach them. "
                "Decided out loud 2026-09-02: this is the publishing path and "
                "it stays the operator's, not a per-tenant row",
    "scheduled_posts": "the publish worker's queue: an intention to post "
                       "through the installation's credentials, written only "
                       "by the operator's CLI (no route exists), drained by "
                       "cron for the whole installation. Becomes owned the "
                       "day a route can write it -- decided 2026-09-02",
    "corrections": "standing notes folded into the next run's spark. GLOBAL "
                   "BY ACCIDENT, and a live bug (BACKLOG #11, PILOT_DRY_RUN "
                   "#8): a pilot's denial steers Mike's night once. Listed "
                   "here so the schema test passes; fix order item 4",
    "ig_hashtag_ids": "a cache of Meta's hashtag ids; the tag is the key",
    # -- the legacy pitch pipeline, removed Aug 2026; nothing writes them
    "pitch_runs": "historical rows from the removed post-production chain",
    "ideas": "historical rows from the removed post-production chain",
    # -- the closed reference set (src/imagesearch.py, src/framebank.py)
    "image_candidates": "server-found image search results the agent may "
                        "only reference by id; a search cache, not authorship",
    "frames": "stills cut from the operator's own footage; the frame bank",
}


def table_exists(conn: psycopg.Connection, table: str) -> bool:
    """Whether `table` resolves on the connection's search_path -- which
    is what makes a per-test schema and the real `public` look alike."""
    row = conn.execute("SELECT to_regclass(%s)", (table,)).fetchone()
    return row is not None and row[0] is not None


def columns(conn: psycopg.Connection, table: str) -> set[str]:
    """The column names of `table` in the current schema. What
    `PRAGMA table_info` was for."""
    rows = conn.execute(
        """
        SELECT column_name FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = %s
        """,
        (table,),
    ).fetchall()
    return {r["column_name"] for r in rows}


def _ensure_accounts_table(conn: psycopg.Connection) -> None:
    """The FK target has to exist before a column can point at it.

    Imported lazily: accounts.py imports this module, so a top-level
    import would be a cycle. Idempotent -- the schema is all
    CREATE TABLE IF NOT EXISTS -- which matters because init order varies
    (the app lifespan runs accounts.init() itself; a test that only calls
    preprod.init() does not).
    """
    from .accounts import SCHEMA as ACCOUNTS_SCHEMA
    conn.execute(ACCOUNTS_SCHEMA)


def _ensure_owner_fk(conn: psycopg.Connection, table: str) -> bool:
    """`<table>_account_id_fkey`, the constraint SQLite declared inline
    and Postgres gets as a separate step (see add_account_column). True
    if it was added now. Looked up by name on the table's own oid, so it
    resolves on search_path like everything else."""
    name = f"{table}_account_id_fkey"
    present = conn.execute(
        "SELECT 1 FROM pg_constraint WHERE conrelid = %s::regclass AND conname = %s",
        (table, name),
    ).fetchone()
    if present:
        return False
    conn.execute(
        f"ALTER TABLE {table} ADD CONSTRAINT {name} "
        f"FOREIGN KEY (account_id) REFERENCES accounts(id)"
    )
    return True


def add_account_column(conn: psycopg.Connection, table: str) -> bool:
    """Additive ALTER TABLE, the preprod.picked_at pattern. True if added.

    Nullable on purpose. The only honest default -- a literal account id
    -- differs per database, so NULL means "predates tenancy" and
    backfill_owner is what claims those rows. Ownership is enforced by
    the queries, not by the column.

    Two idempotent halves: the column, then the FOREIGN KEY to
    accounts(id) as its own constraint. Separate because a module's
    SCHEMA may already carry the column inline (db.SCHEMA's videos does)
    but cannot carry the REFERENCES -- accounts.SCHEMA is in the module
    that imports this one -- so the constraint is always applied here,
    after _ensure_accounts_table has made the target exist.
    """
    _ensure_accounts_table(conn)
    added = "account_id" not in columns(conn, table)
    if added:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN account_id BIGINT")
    _ensure_owner_fk(conn, table)
    return added


def bootstrap_account_id(conn: psycopg.Connection) -> Optional[int]:
    """The account pre-tenancy rows belong to: the oldest one, which on
    every database that exists today is Mike's. None before seeding."""
    if not table_exists(conn, "accounts"):
        return None
    row = conn.execute("SELECT MIN(id) AS id FROM accounts").fetchone()
    return row["id"] if row and row["id"] is not None else None


def backfill_owner(conn: psycopg.Connection, table: str,
                   account_id: Optional[int] = None) -> int:
    """Claim every ownerless row for the bootstrap account; returns how
    many. A no-op when there is no account yet -- init() runs before
    seed() on a fresh database, so accounts.seed() calls this again once
    there is finally an owner to claim them for."""
    if account_id is None:
        account_id = bootstrap_account_id(conn)
    if account_id is None:
        return 0
    cur = conn.execute(
        f"UPDATE {table} SET account_id = %s WHERE account_id IS NULL",
        (account_id,),
    )
    return cur.rowcount


def own_table(conn: psycopg.Connection, table: str) -> None:
    """add_account_column + backfill_owner -- the pair every init() wants."""
    add_account_column(conn, table)
    backfill_owner(conn, table)


def init_db(dsn: Optional[str] = None) -> None:
    """Create the tables. Safe to run repeatedly.

    The SQLite-era migrations that used to live here (add videos.brand,
    add videos.concept_id) are gone: they upgraded a file that predated
    those columns, and no Postgres database predates anything -- both
    are in the CREATE TABLE. own_table stays: it is what declares the
    FK to accounts(id), which cannot be inline (see SCHEMA).
    """
    with connect(dsn) as conn:
        conn.execute(SCHEMA)
        # tenancy: a posted video belongs to the account that made it
        own_table(conn, "videos")


# --------------------------------------------------------------------------
# pitches
# --------------------------------------------------------------------------


def save_pitch_run(
    pitches: Sequence[dict],
    model: Optional[str] = None,
    clip_count: Optional[int] = None,
    brief: Optional[str] = None,
    settings: Optional[str] = None,
    prompt_template: Optional[str] = None,
    dsn: Optional[str] = None,
) -> int:
    """
    Store a whole batch from pitch.py. Returns the run id.

    Pass the raw text of brief.txt, settings.txt and pitch_prompt.txt and
    their hashes get recorded. That is what lets you ask later whether a
    prompt change actually improved anything, instead of guessing.

    Accepts the exact dicts pitch.py already builds:
        {"number": 1, "title": ..., "logline": ..., "story_note": ...}
    """
    if not pitches:
        raise ValueError("no pitches to save")

    with connect(dsn) as conn:
        run_id = conn.execute(
            """
            INSERT INTO pitch_runs
                (created_at, model, clip_count, brief_hash, settings_hash,
                 prompt_hash)
            VALUES (%s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (_now(), model, clip_count, _hash(brief), _hash(settings),
             _hash(prompt_template)),
        ).fetchone()["id"]

        for p in pitches:
            title = (p.get("title") or "").strip()
            if not title:
                raise ValueError(f"pitch {p.get('number')} has no title")
            conn.execute(
                """
                INSERT INTO ideas
                    (run_id, number, title, logline, story_note, hook_clip)
                VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (run_id, p.get("number"), title, p.get("logline"),
                 p.get("story_note"), p.get("hook_clip")),
            )
        return int(run_id)


def mark_selected(
    idea_ids: Sequence[int],
    dsn: Optional[str] = None,
) -> int:
    """
    Record which pitches you chose to cut. Returns how many were updated.

    Call this from editgen.py with the pitches the human picked. This is
    the label. Without it the run is just ten unranked strings.
    """
    if not idea_ids:
        return 0
    with connect(dsn) as conn:
        placeholders = ",".join(["%s"] * len(idea_ids))
        cur = conn.execute(
            f"UPDATE ideas SET selected = 1 WHERE id IN ({placeholders})",
            tuple(idea_ids),
        )
        return cur.rowcount


def mark_selected_by_number(
    run_id: int,
    numbers: Sequence[int],
    dsn: Optional[str] = None,
) -> int:
    """
    Same, but by the pitch numbers editgen.py already takes on the command
    line, so wiring it in is a one-line change.
    """
    if not numbers:
        return 0
    with connect(dsn) as conn:
        placeholders = ",".join(["%s"] * len(numbers))
        cur = conn.execute(
            f"""
            UPDATE ideas SET selected = 1
            WHERE run_id = %s AND number IN ({placeholders})
            """,
            (run_id, *numbers),
        )
        return cur.rowcount


def most_recent_run_id(dsn: Optional[str] = None) -> Optional[int]:
    """
    The id of the latest pitch_runs row, or None if none exist yet.

    Backs editgen.py's --run-id default, so marking a selection doesn't
    require typing the run id back in by hand for the common case of
    editing right after the pitch run that produced it.
    """
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT id FROM pitch_runs ORDER BY id DESC LIMIT 1"
        ).fetchone()
    return row["id"] if row else None


def get_labelled_pitches(
    selected_only: bool = False,
    limit: int = 200,
    dsn: Optional[str] = None,
) -> list[dict[str, Any]]:
    """
    Pitches from runs where at least one was picked, so you know the
    unpicked ones were genuinely rejected rather than never reviewed.

    This is your evaluation set. Feed the selected ones in as examples of
    what good looks like; use the pairing to check whether a new prompt
    ranks your real choices near the top.
    """
    sql = """
        SELECT i.*, r.created_at AS run_created_at, r.model, r.prompt_hash
        FROM ideas i
        JOIN pitch_runs r ON r.id = i.run_id
        WHERE i.run_id IN (SELECT run_id FROM ideas WHERE selected = 1)
        {selected_clause}
        ORDER BY i.run_id DESC, i.number ASC
        LIMIT %s
    """.format(selected_clause="AND i.selected = 1" if selected_only else "")
    with connect(dsn) as conn:
        return [dict(r) for r in conn.execute(sql, (limit,))]


def selection_rate(dsn: Optional[str] = None) -> dict[str, Any]:
    """
    How many pitches you keep, overall and per prompt version.

    If a prompt change makes you pick 4 out of 10 instead of 2, that is a
    real signal and it costs nothing to collect.
    """
    with connect(dsn) as conn:
        rows = conn.execute(
            """
            SELECT r.prompt_hash,
                   COUNT(*)                AS pitched,
                   SUM(i.selected)         AS chosen
            FROM ideas i
            JOIN pitch_runs r ON r.id = i.run_id
            WHERE i.run_id IN (SELECT run_id FROM ideas WHERE selected = 1)
            GROUP BY r.prompt_hash
            """
        ).fetchall()
    by_prompt = [
        {
            "prompt_hash": r["prompt_hash"],
            "pitched": r["pitched"],
            "chosen": r["chosen"] or 0,
            "rate": round((r["chosen"] or 0) / r["pitched"], 3),
        }
        for r in rows
    ]
    total_pitched = sum(b["pitched"] for b in by_prompt)
    total_chosen = sum(b["chosen"] for b in by_prompt)
    return {
        "pitched": total_pitched,
        "chosen": total_chosen,
        "rate": round(total_chosen / total_pitched, 3) if total_pitched else None,
        "by_prompt": by_prompt,
    }


# --------------------------------------------------------------------------
# videos and numbers
# --------------------------------------------------------------------------


def add_video(
    title: str,
    platform: str,
    posted_at: str,
    idea_id: Optional[int] = None,
    url: Optional[str] = None,
    timeline: Optional[str] = None,
    topic: Optional[str] = None,
    hook_type: Optional[str] = None,
    duration_s: Optional[float] = None,
    notes: Optional[str] = None,
    brand: Optional[str] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> int:
    """
    Store a posted video. Returns its id.

    `timeline` is the Resolve timeline name, so a posted video traces back
    to the actual project. posted_at is an ISO date like "2026-07-14".
    idea_id is optional so you can backfill videos that predate this.

    One idea posted to two platforms is two rows, because the numbers
    differ and that difference is worth seeing.
    """
    if platform not in PLATFORMS:
        raise ValueError(f"platform must be one of {PLATFORMS}, got {platform!r}")
    _check_date(posted_at, "posted_at")
    with connect(dsn) as conn:
        if idea_id is not None:
            if not conn.execute("SELECT 1 FROM ideas WHERE id = %s", (idea_id,)).fetchone():
                raise ValueError(f"no idea with id {idea_id}")
        row = conn.execute(
            """
            INSERT INTO videos
                (idea_id, title, platform, posted_at, url, timeline,
                 topic, hook_type, duration_s, notes, brand, account_id)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (idea_id, title, platform, posted_at, url, timeline,
             topic, hook_type, duration_s, notes, brand, account_id),
        ).fetchone()
        return int(row["id"])


def record_metrics(
    video_id: int,
    views: Optional[int] = None,
    likes: Optional[int] = None,
    comments: Optional[int] = None,
    saves: Optional[int] = None,
    shares: Optional[int] = None,
    watch_time_seconds: Optional[float] = None,
    captured_at: Optional[str] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> int:
    """
    Save a snapshot of how a video is doing right now.

    `metrics` carries no owner of its own: a snapshot belongs to a video,
    and the video belongs to an account. What is scoped is the right to
    write one -- you cannot attach numbers to a stranger's post.

    Call it every time you check. Do not overwrite old rows. A repeat
    write for the same timestamp updates in place rather than duplicating.
    """
    captured_at = captured_at or _now()
    with connect(dsn) as conn:
        owned = conn.execute(
            "SELECT 1 FROM videos WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (video_id, account_id),
        ).fetchone()
        if not owned:
            raise ValueError(f"no video with id {video_id}")
        # RETURNING on an upsert yields the row's id whether it was
        # inserted or updated -- which lastrowid never promised.
        row = conn.execute(
            """
            INSERT INTO metrics
                (video_id, captured_at, views, likes, comments, saves,
                 shares, watch_time_seconds)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (video_id, captured_at) DO UPDATE SET
                views              = excluded.views,
                likes              = excluded.likes,
                comments           = excluded.comments,
                saves              = excluded.saves,
                shares             = excluded.shares,
                watch_time_seconds = excluded.watch_time_seconds
            RETURNING id
            """,
            (video_id, captured_at, views, likes, comments, saves,
             shares, watch_time_seconds),
        ).fetchone()
        return int(row["id"])


def list_videos(
    platform: Optional[str] = None,
    limit: int = 200,
    brand: Optional[str] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> list[dict[str, Any]]:
    """This account's videos, newest first, optionally filtered to one
    platform and/or brand. A brand filter is NULL-inclusive -- videos
    tagged with that brand OR not yet tagged at all -- so legacy posts
    still show while the pipeline tags new ones. Ownership is not
    NULL-inclusive in the same way: `brand` is a label you may not have
    filled in, `account_id` is who the row belongs to."""
    sql = "SELECT * FROM videos"
    clauses: list[str] = ["account_id IS NOT DISTINCT FROM %s"]
    params: list[Any] = [account_id]
    if platform:
        clauses.append("platform = %s")
        params.append(platform)
    if brand:
        clauses.append("(brand = %s OR brand IS NULL)")
        params.append(brand)
    if clauses:
        sql += " WHERE " + " AND ".join(clauses)
    sql += " ORDER BY posted_at DESC LIMIT %s"
    params.append(limit)
    with connect(dsn) as conn:
        return [dict(r) for r in conn.execute(sql, params)]


def get_video(video_id: int, dsn: Optional[str] = None, *,
              account_id: int) -> Optional[dict[str, Any]]:
    """
    One video's full metadata, plus its originating pitch (idea_title,
    idea_logline, idea_story_note) if idea_id is set -- all None
    otherwise. None if no such video.
    """
    with connect(dsn) as conn:
        row = conn.execute(
            """
            SELECT v.*, i.title AS idea_title, i.logline AS idea_logline,
                   i.story_note AS idea_story_note
            FROM videos v
            LEFT JOIN ideas i ON i.id = v.idea_id
            WHERE v.id = %s AND v.account_id IS NOT DISTINCT FROM %s
            """,
            (video_id, account_id),
        ).fetchone()
    return dict(row) if row else None


def _cutoff(
    within_days: Optional[int],
    since: Optional[str],
) -> Optional[str]:
    """
    Turn a window into a date string comparable against posted_at.

    Date-only on purpose. posted_at is often stored as "2026-07-14" with no
    time, and ISO strings compare lexically — "2026-07-14" >= a full
    "2026-07-14T09:30:00" is False, which would silently drop videos posted
    on the boundary day.
    """
    if within_days is not None and since is not None:
        raise ValueError("pass within_days or since, not both")
    if since is not None:
        _check_date(since, "since")
        return since[:10]
    if within_days is not None:
        if within_days < 1:
            raise ValueError(f"within_days must be at least 1, got {within_days}")
        return (datetime.now(timezone.utc) - timedelta(days=within_days)).date().isoformat()
    return None


def get_top_performers(
    at_days: int = 7,
    posted_within_days: Optional[int] = None,
    posted_since: Optional[str] = None,
    platform: Optional[str] = None,
    limit: int = 5,
    metric: str = "views",
    ascending: bool = False,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> list[dict[str, Any]]:
    """
    Your best videos, compared fairly.

    Two independent knobs, easy to confuse:

      at_days             how old each video was when measured. Every video
                          is judged at the same age, so one from last year
                          does not beat one from last month purely on
                          accumulated totals.
      posted_within_days  which videos are eligible at all. 180 for the
                          last six months.

    So at_days=7, posted_within_days=180 means: of everything posted since
    roughly January, which did best in its first week.

    Use the window when feeding retrieval. An all-time winner from two years
    ago is a poor model for what to shoot next — your style moved, the
    platform moved, the audience moved.

    ascending=True flips it to worst-first. Feed both ends to an LLM and ask
    what separates them; that is the "why did this work" analysis, and it
    needs the losers as much as the winners.

    Returns the originating pitch text where there is one.
    """
    allowed = {"views", "likes", "comments", "saves", "shares",
               "watch_time_seconds"}
    if metric not in allowed:
        raise ValueError(f"metric must be one of {sorted(allowed)}")

    cutoff = _cutoff(posted_within_days, posted_since)

    # ROUND(double, int) does not exist in Postgres -- only ROUND(numeric,
    # int) -- and the cast back to float is so callers get a float, not a
    # Decimal that only compares equal to one.
    sql = f"""
        WITH snapshots AS (
            SELECT
                v.id AS video_id, v.title, v.platform, v.posted_at,
                v.topic, v.hook_type, v.timeline, v.idea_id,
                i.logline, i.story_note,
                m.{metric} AS score,
                m.captured_at,
                {_AGE_DAYS} AS age_days,
                ROW_NUMBER() OVER (
                    PARTITION BY v.id
                    ORDER BY ABS({_AGE_DAYS} - %s)
                ) AS closest
            FROM videos v
            JOIN metrics m ON m.video_id = v.id
            LEFT JOIN ideas i ON i.id = v.idea_id
            WHERE m.{metric} IS NOT NULL
              AND v.account_id IS NOT DISTINCT FROM %s
              AND ABS({_AGE_DAYS} - %s) <= %s
              {"AND substr(v.posted_at, 1, 10) >= %s" if cutoff else ""}
        )
        SELECT video_id, title, platform, posted_at, topic, hook_type,
               timeline, idea_id, logline, story_note, score, captured_at,
               ROUND(age_days::numeric, 1)::float8 AS measured_at_days
        FROM snapshots
        WHERE closest = 1
          {"AND platform = %s" if platform else ""}
        ORDER BY score {"ASC" if ascending else "DESC"}
        LIMIT %s
    """
    # order matters: the account predicate sits before the two age
    # placeholders in the WHERE clause above
    params: list[Any] = [at_days, account_id, at_days, at_days * AGE_TOLERANCE]
    if cutoff:
        params.append(cutoff)
    if platform:
        params.append(platform)
    params.append(limit)

    with connect(dsn) as conn:
        return [dict(r) for r in conn.execute(sql, params)]


def benchmark(
    at_days: int = 7,
    posted_within_days: Optional[int] = None,
    posted_since: Optional[str] = None,
    platform: Optional[str] = None,
    metric: str = "views",
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> dict[str, Any]:
    """
    Median and spread for the same window, so a single video can be called
    above or below par.

    The dashboard needs this: colouring a row green for "above median"
    requires knowing the median of a comparable set, not of everything ever
    posted. Same two knobs as get_top_performers.
    """
    rows = get_top_performers(
        at_days=at_days,
        posted_within_days=posted_within_days,
        posted_since=posted_since,
        platform=platform,
        limit=100_000,
        metric=metric,
        dsn=dsn,
        account_id=account_id,
    )
    scores = sorted(r["score"] for r in rows if r["score"] is not None)
    if not scores:
        return {"n": 0, "median": None, "best": None, "worst": None}
    mid = len(scores) // 2
    median = (
        scores[mid] if len(scores) % 2
        else (scores[mid - 1] + scores[mid]) / 2
    )
    return {
        "n": len(scores),
        "median": median,
        "best": scores[-1],
        "worst": scores[0],
    }


def get_video_history(
    video_id: int, dsn: Optional[str] = None, *, account_id: int
) -> list[dict[str, Any]]:
    """Every snapshot for one video, oldest first. The growth curve."""
    with connect(dsn) as conn:
        return [
            dict(r)
            for r in conn.execute(
                f"""
                SELECT m.*,
                       ROUND(({_AGE_DAYS})::numeric, 1)::float8 AS age_days
                FROM metrics m
                JOIN videos v ON v.id = m.video_id
                WHERE m.video_id = %s AND v.account_id IS NOT DISTINCT FROM %s
                ORDER BY m.captured_at ASC
                """,
                (video_id, account_id),
            )
        ]


_VIDEO_TEXT_FIELDS = {"topic", "hook_type"}


def distinct_video_field_values(field: str, dsn: Optional[str] = None, *,
                                account_id: int) -> list[str]:
    """
    Values already used for a free-text video field, so a datalist can
    converge vocabulary without locking it down. `field` is checked
    against an allowlist rather than trusted directly -- column names
    can't be parameterized, so this is what keeps it injection-safe.
    """
    if field not in _VIDEO_TEXT_FIELDS:
        raise ValueError(f"field must be one of {sorted(_VIDEO_TEXT_FIELDS)}, got {field!r}")
    with connect(dsn) as conn:
        rows = conn.execute(
            f"SELECT DISTINCT {field} FROM videos "
            f"WHERE account_id IS NOT DISTINCT FROM %s "
            f"AND {field} IS NOT NULL AND {field} != '' "
            f"ORDER BY {field}",
            (account_id,),
        ).fetchall()
    return [r[0] for r in rows]


def latest_metrics_by_video(dsn: Optional[str] = None, *,
                            account_id: int) -> list[dict[str, Any]]:
    """
    One row per video with its most recent snapshot, if any. Backs
    /metrics/new's "previous value greyed behind each input" -- the
    reference point for whether a new number is worth typing.
    """
    with connect(dsn) as conn:
        return [
            dict(r)
            for r in conn.execute(
                """
                SELECT v.id AS video_id, v.title, v.platform, v.posted_at,
                       v.brand, m.views, m.likes, m.comments, m.saves, m.captured_at
                FROM videos v
                LEFT JOIN metrics m ON m.id = (
                    SELECT id FROM metrics
                    WHERE video_id = v.id
                    ORDER BY captured_at DESC
                    LIMIT 1
                )
                WHERE v.account_id IS NOT DISTINCT FROM %s
                ORDER BY v.posted_at DESC
                """,
                (account_id,),
            )
        ]


def summary(dsn: Optional[str] = None) -> dict[str, int]:
    """Row counts. A quick check that things are landing."""
    with connect(dsn) as conn:
        return {
            t: conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
            for t in ("pitch_runs", "ideas", "videos", "metrics")
        }


def _check_date(value: str, field: str) -> None:
    try:
        datetime.fromisoformat(value)
    except (TypeError, ValueError):
        raise ValueError(
            f"{field} must be an ISO date like '2026-07-14', got {value!r}"
        ) from None


def import_pitches_file(
    pitches_path: Path | str,
    dsn: Optional[str] = None,
) -> int:
    """
    One-off: pull an existing pitches.json into the database so past runs
    are not lost. Returns the run id.
    """
    pitches = json.loads(Path(pitches_path).read_text())
    return save_pitch_run(pitches, dsn=dsn)


if __name__ == "__main__":
    init_db()
    print(f"database ready at {resolve_dsn()}")
    print(summary())
