"""
fal's queue receipts, persisted the moment a job is submitted -- and the
sweep that finishes a render whose worker died (2026-09-26).

WHY THIS EXISTS. Render work runs in app/jobs.py's in-process thread
registry, which dies with the process. On 2026-09-26 PR #70 merged, the
"Fly Deploy" action restarted the API while `fal._submit_and_wait` was
polling two Queue renders (#121 Kling, #135 Seedance), and both were
orphaned: the ledger holds stayed `submitted` with no generations row,
and fal's request_id / status_url / response_url had only ever lived in
a local variable, so nothing could reattach to jobs fal may well have
finished and billed. They were released by hand.

So the receipt is written HERE, right after the submit and before the
first poll, keyed by the ledger ref (`charge.ref` -- the same string
`ledger.ref_params` puts on the generations row, so one ref links the
hold, the request and the clip). `recover()` then does, for a request
whose worker has stopped, what the worker would have done:

- COMPLETED with an output -> fetch, download, write the generations
  row, settle the hold, attach the clip to the concept / part -- through
  the SAME tail `fal.generate_for_shot` runs (`fal._finish_shot`), so
  the two doors cannot drift apart.
- an error payload, a request fal no longer knows (404/410/422), no
  output, or still queued past GIVE_UP_SECONDS -> a failed generations
  row and a RELEASE with the reason.
- anything that is not an answer from fal (the network, a 5xx, a 429, no
  key on this machine) -> left alone and logged. Releasing there would
  hand back credit for a render fal may have billed, which is exactly
  the discrepancy `ledger.reap` refuses to paper over.

THIS IS NOT THE LEDGER. The ledger's rule -- nothing is written to it
after the submit except by settle or release -- holds: everything this
module writes after the submit goes to its own table, and the money only
ever moves through `ledger.settle` / `ledger.release`.

WHICH REQUESTS ARE "DEAD". A live worker stamps `beat_at` while it
polls (at most every HEARTBEAT_SECONDS) and marks the row resolved when
it has finished. The sweep only claims a row whose beat is older than
STALE_SECONDS, and the claim itself bumps `beat_at`, so a second machine
in a rolling deploy -- or a second sweep -- leaves it alone. Every
finishing step is also idempotent (a generations row carrying this ref
is reused, not duplicated; settle and release are guarded in the ledger).
"""

from __future__ import annotations

import json
import os
import sys
import threading
import time
import urllib.error
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Optional

from . import db, ledger

# The key the adapter puts in its generations params so the sweep can find
# the row a request already produced -- ledger_ref's twin, present whether
# or not a hold was taken (an exempt account's render is still a render).
GENERATION_REF_KEY = "fal_ref"

HEARTBEAT_SECONDS = 30
# Longer than the one stretch a live worker cannot beat through -- the
# download, whose socket timeout is 300s -- so a slow download is never
# mistaken for a dead worker. The cost is only that a render orphaned by a
# restart is picked up ~10 minutes later rather than ~2.
STALE_SECONDS = int(os.environ.get("FAL_RECOVER_STALE_S", "600"))
# fal says "still queued" for this long after the submit and we stop
# waiting. Longer than fal.TIMEOUT_SECONDS on purpose: the live path gives
# up at its deadline too, but a sweep that finds the job STILL running an
# hour later is looking at a job that is not coming back.
GIVE_UP_SECONDS = int(os.environ.get("FAL_RECOVER_GIVE_UP_S", "3600"))
SWEEP_EVERY_SECONDS = 60
# fal's answers that mean "there is no such job" rather than "try later".
GONE_CODES = {404, 410, 422}

SCHEMA = """
CREATE TABLE IF NOT EXISTS fal_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref           TEXT   NOT NULL,
    hold_id       BIGINT,
    held          BIGINT NOT NULL DEFAULT 0,
    model         TEXT   NOT NULL,
    model_id      TEXT   NOT NULL,
    request_id    TEXT,
    status_url    TEXT   NOT NULL,
    response_url  TEXT   NOT NULL,
    cancel_url    TEXT,
    out_path      TEXT   NOT NULL,
    context_json  TEXT   NOT NULL DEFAULT '{}',
    submitted_at  TEXT   NOT NULL,
    beat_at       TEXT   NOT NULL,
    resolved_at   TEXT,
    outcome       TEXT,
    generation_id BIGINT
);
"""

INDEXES = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_fal_requests_ref
    ON fal_requests (account_id, ref) NULLS NOT DISTINCT;
CREATE INDEX IF NOT EXISTS idx_fal_requests_open
    ON fal_requests (resolved_at, beat_at);
"""


def init(dsn: Optional[str] = None) -> None:
    """Create and own the table. Idempotent; the app lifespan runs it, and
    so does the first record() on a database nothing has initialised."""
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA)
        db.own_table(conn, "fal_requests")
        conn.execute(INDEXES)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _log(message: str) -> None:
    print(f"[fal-recover] {message}", file=sys.stderr)


# --------------------------------------------------------------------------
# the live path's side: record, beat, resolve
# --------------------------------------------------------------------------

class Tracker:
    """What `fal.generate_video` holds while one job is in flight.

    Every method is best-effort: the job has ALREADY been submitted when
    the first one runs, so a bookkeeping failure must never become the
    exception that abandons it -- that would be the orphan this module
    exists to prevent, caused by the thing meant to prevent it. It is
    logged instead, loudly, because an untracked request is one nobody
    can recover.
    """

    def __init__(self, *, account_id: Optional[int], ref: str,
                 hold_id: Optional[int], held: int, model: str, model_id: str,
                 out_path, context: Optional[dict], dsn: Optional[str] = None):
        self.account_id = account_id
        self.ref = str(ref)
        self.hold_id = hold_id
        self.held = int(held or 0)
        self.model = model
        self.model_id = model_id
        self.out_path = str(out_path)
        self.context = dict(context or {})
        self.dsn = dsn
        self.recorded = False
        self._last_beat = 0.0

    def submitted(self, receipt: dict) -> None:
        """Right after the submit, before the first poll."""
        try:
            init(self.dsn)
            now = _now()
            with db.connect(self.dsn) as conn:
                conn.execute(
                    """
                    INSERT INTO fal_requests (account_id, ref, hold_id, held, model,
                        model_id, request_id, status_url, response_url, cancel_url,
                        out_path, context_json, submitted_at, beat_at)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (account_id, ref) DO UPDATE SET
                        hold_id = EXCLUDED.hold_id, held = EXCLUDED.held,
                        model = EXCLUDED.model, model_id = EXCLUDED.model_id,
                        request_id = EXCLUDED.request_id,
                        status_url = EXCLUDED.status_url,
                        response_url = EXCLUDED.response_url,
                        cancel_url = EXCLUDED.cancel_url,
                        out_path = EXCLUDED.out_path,
                        context_json = EXCLUDED.context_json,
                        submitted_at = EXCLUDED.submitted_at,
                        beat_at = EXCLUDED.beat_at,
                        resolved_at = NULL, outcome = NULL, generation_id = NULL
                    """,
                    (self.account_id, self.ref, self.hold_id, self.held, self.model,
                     self.model_id, receipt.get("request_id"), receipt["status_url"],
                     receipt["response_url"], receipt.get("cancel_url"),
                     self.out_path, json.dumps(self.context, default=str), now, now),
                )
            self.recorded = True
            self._last_beat = time.monotonic()
        except Exception as e:
            _log(f"COULD NOT RECORD fal request {receipt.get('request_id')} "
                 f"(ref={self.ref}, account {self.account_id}): {e} -- if this "
                 f"worker dies before the job finishes, nothing can reattach to it")

    def beat(self, *, force: bool = False) -> None:
        """Still alive. Throttled: one write per HEARTBEAT_SECONDS."""
        if not self.recorded:
            return
        if not force and time.monotonic() - self._last_beat < HEARTBEAT_SECONDS:
            return
        self._last_beat = time.monotonic()
        try:
            with db.connect(self.dsn) as conn:
                conn.execute(
                    "UPDATE fal_requests SET beat_at = %s "
                    "WHERE account_id IS NOT DISTINCT FROM %s AND ref = %s "
                    "AND resolved_at IS NULL",
                    (_now(), self.account_id, self.ref))
        except Exception as e:
            _log(f"heartbeat failed for ref={self.ref}: {e}")

    def resolve(self, outcome: str, generation_id: Optional[int] = None) -> None:
        if self.recorded:
            resolve(self.ref, outcome, account_id=self.account_id,
                    generation_id=generation_id, dsn=self.dsn)


def resolve(ref: str, outcome: str, *, account_id: Optional[int],
            generation_id: Optional[int] = None, dsn: Optional[str] = None) -> None:
    """Mark a request finished -- by the live worker or by the sweep.
    NULL-guarded, so the first resolution stands. Never raises."""
    try:
        with db.connect(dsn) as conn:
            if not db.table_exists(conn, "fal_requests"):
                return
            conn.execute(
                "UPDATE fal_requests SET resolved_at = %s, outcome = %s, "
                "generation_id = COALESCE(%s, generation_id) "
                "WHERE account_id IS NOT DISTINCT FROM %s AND ref = %s "
                "AND resolved_at IS NULL",
                (_now(), str(outcome)[:500], generation_id, account_id, str(ref)))
    except Exception as e:
        _log(f"could not resolve ref={ref}: {e}")


def get(ref: str, *, account_id: Optional[int],
        dsn: Optional[str] = None) -> Optional[dict]:
    with db.connect(dsn) as conn:
        if not db.table_exists(conn, "fal_requests"):
            return None
        row = conn.execute(
            "SELECT * FROM fal_requests WHERE account_id IS NOT DISTINCT FROM %s "
            "AND ref = %s", (account_id, str(ref))).fetchone()
    return dict(row) if row else None


def ref_params(ref: str) -> dict:
    return {GENERATION_REF_KEY: str(ref)}


# --------------------------------------------------------------------------
# the sweep
# --------------------------------------------------------------------------

def _claim_stale(account_id: Optional[int], dsn: Optional[str]) -> list[dict]:
    """Every unresolved request whose worker stopped beating, leased to
    this sweep by bumping its beat -- so a second sweeper skips it."""
    cutoff = (datetime.now(timezone.utc) - timedelta(seconds=STALE_SECONDS)).isoformat()
    with db.connect(dsn) as conn:
        if not db.table_exists(conn, "fal_requests"):
            return []
        rows = conn.execute(
            """
            UPDATE fal_requests SET beat_at = %s
            WHERE (%s::bigint IS NULL OR account_id IS NOT DISTINCT FROM %s)
              AND resolved_at IS NULL AND beat_at < %s
            RETURNING *
            """,
            (_now(), account_id, account_id, cutoff),
        ).fetchall()
    return sorted((dict(r) for r in rows), key=lambda r: r["id"])


def _generation_for(row: dict, dsn: Optional[str]) -> Optional[dict]:
    """The generations row this request already produced, if the worker
    got that far before it died."""
    with db.connect(dsn) as conn:
        if not db.table_exists(conn, "generations"):
            return None
        found = conn.execute(
            "SELECT id, output_path FROM generations "
            "WHERE account_id IS NOT DISTINCT FROM %s AND params_json LIKE %s "
            "ORDER BY id DESC LIMIT 1",
            (row["account_id"], f'%"{GENERATION_REF_KEY}": "{row["ref"]}"%'),
        ).fetchone()
    return dict(found) if found else None


def _settle(row: dict, generation_id: Optional[int], dsn: Optional[str]) -> None:
    """Close the hold the way Charge.settle would have: at what was held
    (the quote when there was one, else the estimate's charge -- both are
    `held`), capped at it."""
    if row.get("hold_id") is None:
        return
    try:
        ledger.settle(int(row["hold_id"]), credits=int(row["held"]),
                      cap=int(row["held"]), generation_id=generation_id, dsn=dsn)
    except ledger.LedgerError as e:
        # released by hand before this sweep ran (the 2026-09-26 pair were):
        # the clip is still theirs, the money was already decided
        _log(f"hold {row['hold_id']} (ref={row['ref']}) not settled: {e}")


def _release(row: dict, reason: str, dsn: Optional[str]) -> None:
    if row.get("hold_id") is None:
        return
    try:
        ledger.release(int(row["hold_id"]), reason, dsn=dsn)
    except ledger.LedgerError as e:
        _log(f"hold {row['hold_id']} (ref={row['ref']}) not released: {e}")


def _fail(row: dict, reason: str, dsn: Optional[str]) -> dict:
    """fal answered, and the answer is no: a failed attempt row (every
    attempt is a row), the hold released, the request resolved."""
    from . import fal
    fal._record_recovered_failure(row, reason, dsn=dsn)
    _release(row, f"fal (recovered): {reason}", dsn)
    resolve(row["ref"], f"failed: {reason}", account_id=row["account_id"], dsn=dsn)
    return {"ref": row["ref"], "outcome": "released", "reason": reason}


def _http_code(e: BaseException) -> Optional[int]:
    """fal's HTTP status behind an exception, however it was wrapped.
    `fal._request` re-raises an HTTPError as a RuntimeError carrying fal's
    body (2026-09-26, #69) with the original as __cause__; a test's `http`
    may raise the HTTPError bare. Both must classify the same way, or a
    404 through the real transport reads as "no answer" and is retried
    forever instead of released."""
    seen = set()
    while e is not None and id(e) not in seen:
        seen.add(id(e))
        if isinstance(e, urllib.error.HTTPError):
            return int(e.code)
        e = e.__cause__ or e.__context__
    return None


def _age_seconds(row: dict) -> float:
    submitted = datetime.fromisoformat(row["submitted_at"])
    if submitted.tzinfo is None:
        submitted = submitted.replace(tzinfo=timezone.utc)
    return (datetime.now(timezone.utc) - submitted).total_seconds()


def _recover_one(row: dict, *, http, dsn: Optional[str]) -> dict:
    from . import fal
    ref, account_id = row["ref"], row["account_id"]

    # The worker may have died AFTER it wrote the row. Then the render is
    # already recorded, and only the tail (settle, attach) might be missing.
    existing = _generation_for(row, dsn)
    known_id = int(existing["id"]) if existing else None
    if existing and existing.get("output_path") and Path(existing["output_path"]).is_file():
        return fal._finish_recovered(row, Path(existing["output_path"]),
                                     generation_id=known_id, dsn=dsn)

    call = http or (lambda u, p=None: fal._request(u, p, account_id=account_id))
    try:
        state = call(row["status_url"])
        failed = fal._error_in(state)
        if failed:
            return _fail(row, failed, dsn)
        status = str(state.get("status") or "").upper()
        if status != fal.STATUS_DONE:
            if _age_seconds(row) > GIVE_UP_SECONDS:
                return _fail(row, f"still {status or 'pending'} "
                                  f"{int(_age_seconds(row))}s after submit", dsn)
            return {"ref": ref, "outcome": "pending", "status": status}
        result = call(row["response_url"])
        failed = fal._error_in(result)
        if failed:
            return _fail(row, failed, dsn)
        skip = {row["status_url"], row["response_url"], row.get("cancel_url")}
        url = fal._output_url(result, skip)
        if not url:
            return _fail(row, "completed with no output URL", dsn)
        out_path = Path(row["out_path"])
        fal._download(url, out_path)
    except Exception as e:
        code = _http_code(e)
        reason = fal._safe_error(e, account_id)
        if code in GONE_CODES:
            # 404/410: fal has no such job. 422: fal refused its input --
            # validation errors surface on the RESULT fetch (verified live
            # 2026-09-26). Either way fal has answered, and the answer is no.
            return _fail(row, f"fal said HTTP {code}: {reason}", dsn)
        # not an answer from fal -- the network, a 5xx, a 429, a missing
        # key. Never a release: fal may have rendered and billed this job.
        _log(f"ref={ref}: {reason}; left for the next sweep")
        return {"ref": ref, "outcome": "retry", "reason": reason}

    return fal._finish_recovered(row, out_path, generation_id=known_id, dsn=dsn)


def recover(*, account_id: Optional[int] = None, http=None,
            dsn: Optional[str] = None) -> dict[str, Any]:
    """One sweep. Returns {"rendered": [...], "released": [...],
    "pending": [...], "retry": [...]} of refs. Never raises."""
    out: dict[str, list] = {"rendered": [], "released": [], "pending": [], "retry": []}
    try:
        rows = _claim_stale(account_id, dsn)
    except Exception as e:
        _log(f"sweep could not read fal_requests: {e}")
        return out
    for row in rows:
        try:
            result = _recover_one(row, http=http, dsn=dsn)
        except Exception as e:
            _log(f"ref={row['ref']}: recovery raised {type(e).__name__}: {e}")
            result = {"ref": row["ref"], "outcome": "retry"}
        out.setdefault(result["outcome"], []).append(row["ref"])
        if result["outcome"] in ("rendered", "released"):
            _log(f"ref={row['ref']} (account {row['account_id']}): "
                 f"{result['outcome']}{' -- ' + result['reason'] if result.get('reason') else ''}")
    return out


def open_count(account_id: Optional[int] = None, dsn: Optional[str] = None) -> int:
    """Unresolved requests (every account's when None) -- whether a sweep
    loop still has anything to wait for."""
    with db.connect(dsn) as conn:
        if not db.table_exists(conn, "fal_requests"):
            return 0
        row = conn.execute(
            "SELECT COUNT(*) AS n FROM fal_requests "
            "WHERE (%s::bigint IS NULL OR account_id IS NOT DISTINCT FROM %s) "
            "AND resolved_at IS NULL", (account_id, account_id)).fetchone()
    return int(row["n"])


def in_flight_count(within: float = GIVE_UP_SECONDS, account_id: Optional[int] = None,
                    dsn: Optional[str] = None) -> int:
    """Renders fal may still be working on: unresolved requests submitted
    within `within` seconds. What a deploy should wait for. A row older
    than that is one the sweep has given up on (GIVE_UP_SECONDS), and it
    must not hold every future deploy hostage -- `open_count` still sees
    it, for the CLI and reap."""
    with db.connect(dsn) as conn:
        if not db.table_exists(conn, "fal_requests"):
            return 0
        # every account's when None: a deploy restarts everyone's renders
        rows = conn.execute(
            "SELECT submitted_at FROM fal_requests "
            "WHERE (%s::bigint IS NULL OR account_id IS NOT DISTINCT FROM %s) "
            "AND resolved_at IS NULL", (account_id, account_id)).fetchall()
    return sum(1 for r in rows if _age_seconds(r) <= within)


def _sweep_until_quiet(dsn: Optional[str], every: float) -> None:
    """Sweep now, then every `every` seconds while anything is still open.

    A worker killed by a deploy was beating a moment ago, so the first
    sweep usually finds it not yet stale; the loop is what catches it
    STALE_SECONDS later. It ends once nothing is open: a render started
    after boot has a live worker, and only another restart -- which runs
    this again -- can orphan it. Bounded too: a row that can never be
    finished (its concept deleted under it) must not keep a thread polling
    fal for the life of the process; it stays open for the CLI and reap."""
    stop = time.monotonic() + STALE_SECONDS + GIVE_UP_SECONDS + every
    while True:
        recover(dsn=dsn)
        try:
            if open_count(dsn=dsn) == 0:
                return
        except Exception as e:
            _log(f"sweep loop stopping: {e}")
            return
        if time.monotonic() > stop:
            _log("sweep loop stopping with requests still open -- "
                 "run `python -m src.fal_requests` to see them")
            return
        time.sleep(every)


def start_background(dsn: Optional[str] = None,
                     every: float = SWEEP_EVERY_SECONDS) -> threading.Thread:
    """The app lifespan's call: the sweep on a daemon thread, so boot is
    never held up by fal's latency."""
    thread = threading.Thread(target=_sweep_until_quiet, args=(dsn, every),
                              name="fal-recover", daemon=True)
    thread.start()
    return thread


def main(argv: Optional[list[str]] = None) -> int:
    """`python -m src.fal_requests` -- one sweep, by hand, printed.
    `--open` sweeps nothing: it prints how many renders are in flight (a
    submitted clip with no answer yet) and exits, which is what the deploy
    workflow asks before it restarts the machine (2026-09-28: a deploy at
    15:40 killed #384's three-shot render after shot 1)."""
    import argparse
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("--account", type=int, default=None)
    parser.add_argument("--open", action="store_true",
                        help="print the number of unresolved requests and exit; changes nothing")
    args = parser.parse_args(argv)
    if args.open:
        print(in_flight_count())
        return 0
    print(json.dumps(recover(account_id=args.account), indent=2))
    return 0


__all__ = ["GENERATION_REF_KEY", "Tracker", "init", "resolve", "get",
           "ref_params", "recover", "open_count", "in_flight_count", "start_background"]


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
