"""
Tracking for AI-generated clips. Postgres since 2026-09-03 (step 4 of
docs/tasks/task-postgres-migration.md); every function takes `dsn`
(None = DATABASE_URL) where it took `path`.

An extension to the core spine in db.py, kept in its own module so it can
be removed cleanly if it does not earn its place.

Two tables:

    shots       - what the edit needed that the footage library did not have
    generations - each attempt at making it, and whether you kept the result

The measurement that matters is not "is the prompt good". It is **how many
attempts before a usable clip**. Generative video is a slot machine, and
attempts-to-keeper is the number that tells you whether a prompt change,
or a different tool, actually helped. A prompt that lands in 2 tries beats
one that lands in 9 no matter how it reads.

Same labelling pattern as pitch selection: you already decide keep or
discard. This records the decision instead of losing it.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Optional

from . import account_keys
from .db import _now, connect, own_table
from .shot import TOOLS, Shot

# The generations-log vocabulary: every video tool from the Shot
# registry, plus the still-image connectors (midjourney.py,
# nano_banana.py) that log attempts here but never render a Shot --
# they must not join shot.PLATFORMS or they'd be offered as AI-shot
# video tools in concepts.
#
# "fal" is here for fal.py's FLUX stills ONLY. fal's video renders log
# under the PLATFORM they rendered for (kling / ltx / wan / seedance,
# already in TOOLS), because the scoreboard's question is which model
# makes keepable clips and "fal" would average four models that cost
# $0.30 and $1.51 into one meaningless row. The split is also what keeps
# fal's video daily cap from moving when someone renders a still.
IMAGE_TOOLS = ("midjourney", "nano", "fal")
LOG_TOOLS = TOOLS + IMAGE_TOOLS

SCHEMA = """
CREATE TABLE IF NOT EXISTS shots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TEXT    NOT NULL,
    idea_id     BIGINT REFERENCES ideas(id) ON DELETE SET NULL,
    slot_index  INTEGER,
    spec_json   TEXT    NOT NULL,
    subject     TEXT    NOT NULL,
    camera      TEXT,
    size        TEXT,
    duration_s  DOUBLE PRECISION,
    resolved    INTEGER NOT NULL DEFAULT 0,
    notes       TEXT,
    account_id  BIGINT
);

CREATE TABLE IF NOT EXISTS generations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shot_id     BIGINT  NOT NULL REFERENCES shots(id) ON DELETE CASCADE,
    created_at  TEXT    NOT NULL,
    tool        TEXT    NOT NULL,
    attempt     INTEGER NOT NULL,
    prompt      TEXT    NOT NULL,
    params_json TEXT,
    output_path TEXT,
    cost_usd    DOUBLE PRECISION,
    kept        INTEGER NOT NULL DEFAULT 0,
    reject_reason TEXT,
    notes       TEXT,
    account_id  BIGINT
);

CREATE INDEX IF NOT EXISTS idx_shots_idea      ON shots (idea_id);
CREATE INDEX IF NOT EXISTS idx_gen_shot        ON generations (shot_id);
CREATE INDEX IF NOT EXISTS idx_gen_tool_kept   ON generations (tool, kept);
"""


def init(dsn: Optional[str] = None) -> None:
    """Create the generative tables. Run after db.init_db()."""
    with connect(dsn) as conn:
        conn.execute(SCHEMA)
        # tenancy: generations is what the daily render caps count, so an
        # unowned row here is a cap another account pays for
        own_table(conn, "shots")
        own_table(conn, "generations")
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_gen_account_tool "
            "ON generations (account_id, tool, created_at)"
        )


def add_shot(
    shot: Shot,
    idea_id: Optional[int] = None,
    slot_index: Optional[int] = None,
    notes: Optional[str] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> int:
    """
    Record a gap in the footage that a generated clip will fill.

    idea_id links it to the pitch it serves, slot_index to its position in
    that edit's cut list.
    """
    with connect(dsn) as conn:
        if idea_id is not None:
            if not conn.execute("SELECT 1 FROM ideas WHERE id = %s", (idea_id,)).fetchone():
                raise ValueError(f"no idea with id {idea_id}")
        row = conn.execute(
            """
            INSERT INTO shots
                (created_at, idea_id, slot_index, spec_json, subject,
                 camera, size, duration_s, notes, account_id)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (_now(), idea_id, slot_index, json.dumps(shot.as_dict()),
             shot.subject, shot.camera, shot.size, shot.duration_s, notes,
             account_id),
        ).fetchone()
        return int(row["id"])


# --------------------------------------------------------------------------
# the daily spend wall
# --------------------------------------------------------------------------

def _billed_to_operator(params_json) -> bool:
    """Whether this generation was paid for on the INSTALLATION's key.

    True for an unlabelled row, and that default is the whole safety
    property: `key_source` has only been written since BYOK, midjourney
    does not write it at all, and a row we cannot read is a row we cannot
    prove somebody else paid for. Counting it toward the operator's
    ceiling errs toward refusing a render; the other default errs toward
    spending money that was never budgeted."""
    if not params_json:
        return True
    try:
        source = json.loads(params_json).get("key_source")
    except (TypeError, ValueError):
        return True
    return source != account_keys.SOURCE_ACCOUNT


def used_today(tool: str, dsn: Optional[str] = None, *,
               account_id: Optional[int] = None, everyone: bool = False,
               operator_billed_only: bool = False) -> int:
    """Generations logged for `tool` since UTC midnight.

    Reads the same generations table the scoreboards do, so a cap cannot
    drift from the log. `everyone=True` ignores ownership on purpose --
    that is the installation-wide count, and it is the only query here
    allowed to.

    `operator_billed_only` (2026-09-14) narrows that installation-wide
    count to the renders the OPERATOR actually paid for: rows whose
    `key_source` is not `account`. See cap_error for why the ceiling
    wants this and the per-account wall does not.

    The key_source filter is applied in Python, not SQL, deliberately.
    `params_json` is a TEXT column and predates any guarantee that it
    holds valid JSON, so `params_json::jsonb ->> 'key_source'` would
    raise on one malformed legacy row and take the whole cap check with
    it -- turning "I cannot read the log" into "you may spend", which is
    the wrong way for this particular function to fail. A day's rows for
    one tool are tens at most.
    """
    today = datetime.now(timezone.utc).date().isoformat()
    with connect(dsn) as conn:
        if everyone and operator_billed_only:
            rows = conn.execute(
                "SELECT params_json FROM generations "
                "WHERE tool = %s AND created_at >= %s", (tool, today)).fetchall()
            return sum(1 for r in rows if _billed_to_operator(r["params_json"]))
        if everyone:
            row = conn.execute(
                "SELECT COUNT(*) FROM generations WHERE tool = %s AND created_at >= %s",
                (tool, today),
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT COUNT(*) FROM generations "
                "WHERE tool = %s AND created_at >= %s AND account_id IS NOT DISTINCT FROM %s",
                (tool, today, account_id),
            ).fetchone()
        return int(row[0])


def cap_error(tool: str, n: int = 1, *, account_id: Optional[int],
              per_account: int, ceiling: int, dsn: Optional[str] = None,
              env_prefix: str, phrase: str = "generations used",
              used: Optional[int] = None,
              used_everywhere: Optional[int] = None) -> Optional[str]:
    """The message to refuse with, or None to go ahead.

    TWO walls, and both are needed. The per-account cap is fairness: it
    stops whoever logs in first from spending everyone's day. The global
    ceiling is the credit card: per-account alone means ten pilot users
    times six renders is sixty renders billed to one person, and each of
    them is inside their limit the whole time.

    WHAT CHANGED 2026-09-14, and why the sentence above still holds. The
    ceiling was counting EVERY render on the installation, so a user who
    brought their own key -- paying their own bill, costing the operator
    nothing -- still consumed the operator's ceiling and could lock
    everyone else out of a budget that was never spent. That was right
    while Gemini and the renderers read the operator's key no matter who
    asked; it stopped being right when account_keys resolved them per
    account. So the ceiling now counts only what the operator actually
    PAID for (`key_source` != account). Its job is unchanged -- it is
    still the credit card -- it has just stopped charging the card for
    other people's money.

    A row we cannot read still counts: see _billed_to_operator.

    AND THE CEILING IS OFF BY DEFAULT, 2026-09-14 (Mike's call). Every
    *_GLOBAL_DAILY_CAP now defaults to 0, which means no ceiling: the
    check is skipped entirely and only the per-account wall applies. The
    paragraph above is still the argument FOR a ceiling, and it is still
    true -- keyless accounts fall back to the operator's key, and N
    accounts times their per-account cap is what he is now exposed to.
    He accepted that to stop users blocking each other, and setting any
    *_GLOBAL_DAILY_CAP to a positive number turns the wall back on with
    no code change.

    Checked per-account first so the error a user sees names the limit
    they can actually do something about.
    """
    # `used` is passed in by each tool module, from its own
    # generations_today(). That keeps one seam per tool for tests to patch
    # -- a cap check that quietly stopped calling the function the tests
    # stub is how a "capped" render makes a real billed API call.
    if used is None:
        used = used_today(tool, dsn, account_id=account_id)
    if used + n > per_account:
        more = f", {n} more would exceed it" if n > 1 else ""
        return (f"daily cap: {used}/{per_account} {phrase} today{more} "
                f"({env_prefix}_DAILY_CAP to raise)")
    # 0 (or anything non-positive) means NO ceiling -- not a ceiling of
    # zero that refuses everything. Read it before counting, so an
    # installation with the wall off does not pay for the query either.
    if ceiling is None or ceiling <= 0:
        return None
    everyone = (used_everywhere if used_everywhere is not None
                else used_today(tool, dsn, everyone=True,
                                operator_billed_only=True))
    if everyone + n > ceiling:
        return (f"daily ceiling: {everyone}/{ceiling} {phrase} across "
                f"all accounts today ({env_prefix}_GLOBAL_DAILY_CAP to raise)")
    return None


def get_shot(shot_id: int, dsn: Optional[str] = None, *,
             account_id: int) -> Optional[dict[str, Any]]:
    """Fetch a shot with its spec parsed back out -- if it is this
    account's. None for someone else's, same as for a missing id."""
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM shots WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (shot_id, account_id),
        ).fetchone()
    if not row:
        return None
    data = dict(row)
    data["spec"] = json.loads(data.pop("spec_json"))
    return data


def record_generation(
    shot_id: int,
    tool: str,
    prompt: str,
    params: Optional[dict] = None,
    output_path: Optional[str] = None,
    cost_usd: Optional[float] = None,
    notes: Optional[str] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> int:
    """
    Log one attempt. Attempt number is assigned automatically, counting per
    shot and tool, so two runway attempts on the same shot coexist.
    """
    if tool not in LOG_TOOLS:
        raise ValueError(f"tool must be one of {LOG_TOOLS}, got {tool!r}")
    if not prompt.strip():
        raise ValueError("prompt cannot be empty")

    with connect(dsn) as conn:
        owned = conn.execute(
            "SELECT 1 FROM shots WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (shot_id, account_id),
        ).fetchone()
        if not owned:
            raise ValueError(f"no shot with id {shot_id}")
        # attempt numbering is per shot, per tool, per account -- a shared
        # counter would leak how often the other account is retrying
        prior = conn.execute(
            "SELECT COALESCE(MAX(attempt), 0) FROM generations "
            "WHERE shot_id = %s AND tool = %s AND account_id IS NOT DISTINCT FROM %s",
            (shot_id, tool, account_id),
        ).fetchone()[0]
        row = conn.execute(
            """
            INSERT INTO generations
                (shot_id, created_at, tool, attempt, prompt, params_json,
                 output_path, cost_usd, notes, account_id)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (shot_id, _now(), tool, prior + 1, prompt,
             json.dumps(params) if params else None,
             output_path, cost_usd, notes, account_id),
        ).fetchone()
        return int(row["id"])


def mark_kept(
    generation_id: int,
    output_path: Optional[str] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> None:
    """
    The one you used. Marks its shot resolved.

    This is the label. Everything in tool_scoreboard and
    attempts_to_keeper depends on you calling it.
    """
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT shot_id FROM generations WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (generation_id, account_id),
        ).fetchone()
        if not row:
            raise ValueError(f"no generation with id {generation_id}")
        conn.execute(
            "UPDATE generations SET kept = 1, output_path = COALESCE(%s, output_path) "
            "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (output_path, generation_id, account_id),
        )
        conn.execute(
            "UPDATE shots SET resolved = 1 WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (row["shot_id"], account_id),
        )


def mark_rejected(
    generation_id: int,
    reason: str,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> None:
    """
    Why a take failed. Free text, but keep the vocabulary tight — "morphing
    hands", "wrong lighting", "camera ignored the move". Grouping these is
    how you learn which failure your prompts keep inviting.
    """
    with connect(dsn) as conn:
        cur = conn.execute(
            "UPDATE generations SET reject_reason = %s "
            "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (reason, generation_id, account_id),
        )
        if cur.rowcount == 0:
            raise ValueError(f"no generation with id {generation_id}")


# --------------------------------------------------------------------------
# what this is all for
# --------------------------------------------------------------------------


def attempts_to_keeper(
    tool: Optional[str] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> list[dict[str, Any]]:
    """
    For each resolved shot, how many attempts it took on the tool that won.

    This is the headline number. Track it over time and a prompt change
    that drops the median from 6 to 3 is a measured improvement, not a
    feeling.
    """
    sql = """
        SELECT g.shot_id, s.subject, s.camera, s.size,
               g.tool, g.attempt AS attempts, g.cost_usd,
               (SELECT COUNT(*) FROM generations x
                 WHERE x.shot_id = g.shot_id
                   AND x.account_id IS NOT DISTINCT FROM g.account_id) AS total_attempts_all_tools,
               (SELECT COALESCE(SUM(x.cost_usd), 0) FROM generations x
                 WHERE x.shot_id = g.shot_id
                   AND x.account_id IS NOT DISTINCT FROM g.account_id) AS total_cost
        FROM generations g
        JOIN shots s ON s.id = g.shot_id
        WHERE g.kept = 1 AND g.account_id IS NOT DISTINCT FROM %s
        {tool_clause}
        ORDER BY g.shot_id
    """.format(tool_clause="AND g.tool = %s" if tool else "")
    params = (account_id, tool) if tool else (account_id,)
    with connect(dsn) as conn:
        return [dict(r) for r in conn.execute(sql, params)]


def subscription_rendered(dsn: Optional[str] = None, *,
                          account_id: Optional[int] = None) -> set[int]:
    """Concept ids whose clip came off a SUBSCRIPTION rather than a
    metered API call -- the manual lanes' rows (`ops/render_queue.py`).

    Provenance a human can see. A hand-rendered clip and an API-rendered
    one are the same mp4 in the same folder with the same `media_url`
    shape; the only thing that separates them is `params.source`, which
    until now lived nowhere anyone looks. That matters because the two
    were paid for by different things -- one by a subscription with terms
    of its own, one by credit somebody was billed for -- and a person
    about to use a clip somewhere those terms bite has no other way to
    tell.

    Read off `params_json` rather than a new column on purpose: the fact
    is already on the row, for every row ever written including the ones
    imported before this function existed, and a column would have to be
    backfilled from exactly this query anyway. `::jsonb` is safe because
    every value in that column is `json.dumps` output; a NULL params or a
    row with no concept_id simply does not match.
    """
    from . import manual_lane
    rows = _subscription_rows(dsn, account_id, list(manual_lane.SUBSCRIPTION_SOURCES))
    out = set()
    for row in rows:
        try:
            out.add(int(row["concept_id"]))
        except (TypeError, ValueError):
            continue
    return out


def _subscription_rows(dsn, account_id, sources) -> list:
    """The query behind `subscription_rendered`, and the one place it is
    allowed to give up.

    NEVER RAISES, deliberately, unlike everything else that reads this
    table: this is a LABEL on a card, and a database that has never
    rendered anything has no `generations` table at all. The board 500ing
    because nothing has ever been billed on it is the wrong failure --
    the same degrade `_runway_state` makes for the daily count. An
    unlabelled card is honest; a dead board is not.
    """
    try:
        with connect(dsn) as conn:
            return list(conn.execute(
                "SELECT DISTINCT (params_json::jsonb->>'concept_id') AS concept_id "
                "FROM generations "
                "WHERE account_id IS NOT DISTINCT FROM %s AND params_json IS NOT NULL "
                "AND params_json::jsonb->>'source' = ANY(%s) "
                "AND params_json::jsonb->>'concept_id' IS NOT NULL",
                (account_id, sources),
            ).fetchall())
    except Exception:
        return []


def tool_scoreboard(dsn: Optional[str] = None, *,
                    account_id: int) -> list[dict[str, Any]]:
    """
    Per tool: attempts made, clips kept, hit rate, spend.

    Only counts shots where something was eventually kept, so a shot you
    abandoned entirely does not silently punish whichever tool you tried
    first.
    """
    with connect(dsn) as conn:
        rows = conn.execute(
            """
            SELECT g.tool,
                   COUNT(*)                    AS attempts,
                   SUM(g.kept)                 AS kept,
                   COALESCE(SUM(g.cost_usd),0) AS spend
            FROM generations g
            WHERE g.account_id IS NOT DISTINCT FROM %s
              AND g.shot_id IN (SELECT shot_id FROM generations
                                 WHERE kept = 1 AND account_id IS NOT DISTINCT FROM %s)
            GROUP BY g.tool
            ORDER BY g.tool
            """,
            (account_id, account_id),
        ).fetchall()
    out = []
    for r in rows:
        kept = r["kept"] or 0
        out.append({
            "tool": r["tool"],
            "attempts": r["attempts"],
            "kept": kept,
            "hit_rate": round(kept / r["attempts"], 3) if r["attempts"] else None,
            "spend": round(r["spend"], 2),
            "cost_per_keeper": round(r["spend"] / kept, 2) if kept else None,
        })
    return out


def failure_reasons(
    tool: Optional[str] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> list[dict[str, Any]]:
    """
    What goes wrong, grouped. Tells you which failure your prompts keep
    inviting, which is more actionable than a hit rate on its own.
    """
    sql = """
        SELECT reject_reason AS reason, COUNT(*) AS n
        FROM generations
        WHERE reject_reason IS NOT NULL AND account_id IS NOT DISTINCT FROM %s {tool_clause}
        GROUP BY reject_reason
        ORDER BY n DESC
    """.format(tool_clause="AND tool = %s" if tool else "")
    params = (account_id, tool) if tool else (account_id,)
    with connect(dsn) as conn:
        return [dict(r) for r in conn.execute(sql, params)]


def winning_prompts(
    limit: int = 10,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> list[dict[str, Any]]:
    """
    Prompts that produced a keeper, fewest attempts first.

    Feed these to the writer as examples. This is the retrieval step for
    generative prompts, and it works the same way as pulling past pitch
    picks — your own record, not general advice.
    """
    with connect(dsn) as conn:
        return [
            dict(r)
            for r in conn.execute(
                """
                SELECT g.tool, g.attempt AS attempts, g.prompt,
                       s.subject, s.camera, s.size, s.spec_json
                FROM generations g
                JOIN shots s ON s.id = g.shot_id
                WHERE g.kept = 1 AND g.account_id IS NOT DISTINCT FROM %s
                ORDER BY g.attempt ASC, g.created_at DESC
                LIMIT %s
                """,
                (account_id, limit),
            )
        ]


def open_shots(dsn: Optional[str] = None, *,
               account_id: int) -> list[dict[str, Any]]:
    """Shots with no keeper yet — this account's working queue."""
    with connect(dsn) as conn:
        return [
            dict(r)
            for r in conn.execute(
                """
                SELECT s.*, COUNT(g.id) AS attempts_so_far
                FROM shots s
                LEFT JOIN generations g
                       ON g.shot_id = s.id AND g.account_id IS NOT DISTINCT FROM s.account_id
                WHERE s.resolved = 0 AND s.account_id IS NOT DISTINCT FROM %s
                GROUP BY s.id
                ORDER BY s.created_at DESC
                """,
                (account_id,),
            )
        ]


def summary(dsn: Optional[str] = None, *, account_id: int) -> dict[str, int]:
    with connect(dsn) as conn:
        return {
            t: conn.execute(
                f"SELECT COUNT(*) FROM {t} WHERE account_id IS NOT DISTINCT FROM %s", (account_id,)
            ).fetchone()[0]
            for t in ("shots", "generations")
        }
