"""
The prepaid credit ledger: what an account has, what it has committed,
and what it actually consumed.

WHY THIS EXISTS, AND WHY IT DOES NOT LOOK LIKE ITS NEIGHBOURS
(docs/CREDIT_LEDGER_DESIGN.md, written 2026-09-08 before a line of this).
`src/spend.py` and `src/costs.py` already meter, and they are
deliberately never-raises: a lost `llm_calls` row costs a number on a
dashboard and nothing else. This module is the opposite promise. A
ledger write that silently fails costs MONEY -- either the customer's,
by charging twice, or yours, by rendering for free -- so **every write
here raises**. Do not copy `record_call`'s swallow-everything shape into
this file; it is the single most important difference between the two
modules that otherwise look alike.

THE UNIT IS AN INTEGER. One credit is one US cent. `BIGINT`, no
`NUMERIC`, no floats anywhere on the ledger path. The `cost_usd` columns
on `generations` and `llm_calls` stay floats -- they are estimates for a
page and are not this. Dollars become credits at exactly one place,
`credits_for_usd()`, which rounds UP, so rounding never quietly favours
the customer at your expense across thousands of renders.

CREDIT ARRIVES IN LOTS, NOT AS A BALANCE. An allowance granted by a plan
and a credit bought with cash are different promises even when they
expire on the same clock, so each grant is its own row carrying its own
expiry and its own lapse policy, and consumption is SOONEST-EXPIRY-FIRST
across them. That is what makes "your monthly allowance burns before the
credit you paid for" true without anyone having to remember it, and it
is what lets the two kinds be governed differently later without a
migration.

THE HOLD IS THE POINT OF THE WHOLE EXERCISE. The irreversible commit is
the single HTTP submit inside each adapter (see `hold_for_render` for
the exact sites), and today the `generations` row is written *after* it,
across a poll loop that can run for minutes. So the ledger writes
BEFORE the submit: hold -> submit -> settle or release. And the hold
takes a per-account advisory lock, because `generative.cap_error` is
already read-then-act with no lock -- which is why two simultaneous
approvals can both pass a cap of six -- and money must not inherit that.

Postgres, like every table since 2026-09-03: `%s` placeholders,
`IS NOT DISTINCT FROM` for the nullable owner (a plain `=` silently
drops every unowned row), `RETURNING id`, `GENERATED BY DEFAULT AS
IDENTITY`, and `dsn` where a `path` used to be.

Both tables are OWNED (`db.OWNED_TABLES`). Every literal that names one
carries `account_id` in the SAME string, because the scanner in
tests/test_tenancy.py cannot see a predicate assembled next door.

THREE THINGS THAT LOOK WRONG AND ARE KNOWN, so the next reader spends
their afternoon on something else:

- `credit_lots.credits_remaining` IS A DENORMALISATION. The entries are
  the truth; that column is the running figure the lot-picking queries
  read, and `reconcile()` plus a test assert the two never disagree.
  Nothing at the database level enforces it, which is the real gap --
  a trigger, or dropping the column and reading `SUM(delta)` off an
  index, would make the invariant unfalsifiable rather than merely
  tested. Left as it is on purpose: the check has teeth today and the
  fix is cheap the day it does not.

- THE RECONCILIATION FIGURE THE DESIGN DOC DESCRIBES IS CIRCULAR while
  settle runs on the same estimate `generations.cost_usd` records --
  "settled vs metered drift" compares a number against itself and will
  read ~0 forever. It is a consistency check, not a financial one, and
  should not be shown as reassurance until a real per-render invoice
  exists (fal publishes per-second rates; Runway and Higgsfield do
  not). `reconcile()` here is the honest one: entries against the
  running figure, both of them this module's own.

- `LAPSE_POLICY["purchase"] = True` VOIDS CREDIT SOMEBODY PAID CASH
  FOR. That is flagged in the design doc as the entry to revisit, and
  it is the owner's call, not this module's. It is a constant here
  precisely so softening it is one line and no migration.
"""
from __future__ import annotations

import math
import sys
from datetime import datetime, timedelta, timezone
from decimal import Decimal, InvalidOperation
from typing import Any, Optional

from . import account_keys, db

# --------------------------------------------------------------------------
# the vocabulary
# --------------------------------------------------------------------------

# Where credit came from. `adjustment` is the operator's correction --
# a goodwill top-up, a botched night made good -- and is deliberately
# NOT in LAPSE_POLICY's True set below.
LOT_KINDS = ("subscription", "purchase", "refund", "promo", "adjustment")

# Every movement. Nothing is ever updated or deleted; a correction is
# another row.
ENTRY_KINDS = ("grant", "hold", "settle", "release", "expire")

# Changed 2026-09-08 (design doc, "Expiry and lapse"): two months from
# grant, not the twelve the first draft carried.
EXPIRY_MONTHS = 2

# Which lot kinds die when the subscription lapses. A dict rather than a
# hardcoded rule because THE `purchase` ENTRY IS THE ONE TO REVISIT:
# voiding credit a customer paid cash for, because a separate
# subscription ended, is the shape that draws chargebacks -- and prepaid
# balances fall under gift-card and escheatment law in many states, with
# minimum honor periods measured in years rather than months. Softening
# it should be an edit to this line after an accountant has looked at
# it, not a migration. `refund` is False because refunded credit is
# money you already owed back; `adjustment` is absent (and therefore
# False) for the same reason -- an operator's correction should not be
# undone by a billing event.
LAPSE_POLICY: dict[str, bool] = {
    "subscription": True,
    "purchase": True,
    "promo": True,
    "refund": False,
}

# The key an adapter puts in its `generations.params_json` so the reaper
# can find the row a hold was taken for. See `ref_params` and `reap`.
GENERATION_REF_KEY = "ledger_ref"

# How old an unsettled hold has to be before the nightly reaper touches
# it. Well past the longest provider poll loop in the repo (Veo's
# timeout_s is 600s) -- reaping a hold whose render is merely slow would
# settle or release a render that is still running.
DEFAULT_REAP_AGE = timedelta(hours=6)


class LedgerError(RuntimeError):
    """Anything the ledger refuses to do. Raised, never swallowed."""


class InsufficientCredit(LedgerError):
    """`hold()` could not fit the request inside the available balance.

    Carries the numbers so a caller can say what it needs rather than
    "payment required": both are integer credits, both are the truth at
    the moment the advisory lock was held.
    """

    def __init__(self, account_id: Optional[int], requested: int, available: int):
        self.account_id = account_id
        self.requested = int(requested)
        self.available = int(available)
        super().__init__(
            f"account {account_id} has {self.available} credits available, "
            f"needs {self.requested}"
        )


# --------------------------------------------------------------------------
# the one conversion site
# --------------------------------------------------------------------------

def credits_for_usd(usd) -> int:
    """USD -> integer credits, ALWAYS ROUNDING UP. One credit = one cent.

    The only place in the codebase where a float becomes a credit, and
    it rounds up on purpose: a provider estimate of $0.4501 is 46
    credits, not 45. Rounded down, the half-cent you eat on each of ten
    thousand renders is $50 you cannot see in any row.

    Via Decimal(str(usd)) rather than `usd * 100`, because
    `0.29 * 100 == 28.999999999999996` and `math.ceil` of that is 29 by
    luck rather than by rule -- while `2.675 * 100` is 267.49999999999997
    and ceils to 268 correctly only because the error happened to fall
    the right way. str() takes the shortest repr, which is the number the
    caller meant.
    """
    if usd is None:
        raise LedgerError("cannot price None")
    try:
        cents = Decimal(str(usd)) * 100
    except (InvalidOperation, ValueError) as e:
        raise LedgerError(f"not a price: {usd!r}") from e
    if cents < 0:
        raise LedgerError(f"negative price: {usd!r}")
    return int(math.ceil(cents))


def ref_params(ref: str) -> dict:
    """The fragment an adapter merges into its `generations` params so a
    hold can be matched back to the render it paid for.

    `record_generation(..., params={**ledger.ref_params(ref), ...})` is
    the whole contract. The reaper matches on it as a string; the value
    is written by `json.dumps` on the way in, so it is exactly
    `"ledger_ref": "<ref>"` in the stored text.
    """
    return {GENERATION_REF_KEY: str(ref)}


# --------------------------------------------------------------------------
# BYOK -- one place, because every caller would get it wrong differently
# --------------------------------------------------------------------------

# What `account_keys.key_and_source` returns when the account rendered on
# its own stored credential rather than on the installation's env key.
BYOK_KEY_SOURCE = account_keys.SOURCE_ACCOUNT


def is_billable(key_source: Optional[str]) -> bool:
    """Whether a render on this credential may be debited. THE ONE PLACE
    that rule lives.

    A render whose credential resolved to `key_source == "account"` --
    the BYOK case `src/account_keys.py` made visible on 2026-09-07 --
    takes no hold and no debit: the customer's card was charged by the
    provider directly, and billing them again is charging twice for one
    clip. Every adapter already writes `key_source` into
    `generations.params_json`, so the fact is on the row; what must not
    happen is four call sites each deciding what to do with it, because
    the one that spells the constant wrong bills a BYOK customer and
    nothing fails.

    An UNKNOWN source (None -- no credential resolved at all, or
    `key_source()` swallowed a decrypt error) reads as billable. That is
    the deliberate direction to be wrong in: it holds credit for a
    render that may not happen, which `release()` and the reaper give
    back, rather than rendering for free on the installation's key and
    finding out at the invoice.
    """
    return key_source != BYOK_KEY_SOURCE


# --------------------------------------------------------------------------
# schema
# --------------------------------------------------------------------------

# account_id is NOT here: db.own_table adds the column and the FOREIGN
# KEY to accounts(id) as its own step, because accounts.SCHEMA lives in
# the module that imports db. Every owned table in the repo is built
# this way.
SCHEMA = """
CREATE TABLE IF NOT EXISTS credit_lots (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind              TEXT   NOT NULL,
    credits_granted   BIGINT NOT NULL,
    credits_remaining BIGINT NOT NULL,
    granted_at        TEXT   NOT NULL,
    expires_at        TEXT,
    source_ref        TEXT,
    note              TEXT
);

CREATE TABLE IF NOT EXISTS credit_entries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id        BIGINT,
    delta         BIGINT NOT NULL,
    kind          TEXT   NOT NULL,
    ref           TEXT,
    generation_id BIGINT,
    -- the reaper's other half. The design doc says "hold carries the
    -- provider and the estimate: without them it cannot tell a dead
    -- render from a slow one" -- the ESTIMATE needs no column, it is
    -- the hold's own `delta` in credits, which also keeps the promise
    -- that no float is ever stored on this path.
    provider      TEXT,
    -- The ONE column in this table that is ever written twice, and it is
    -- deliberately not a money field: NULL at hold time, stamped once by
    -- `mark_submitted` in the instant before the provider call. It is
    -- what separates "the render never happened" from "the render was
    -- paid for and nothing recorded it" -- two states that otherwise
    -- look identical to the reaper and have opposite correct answers.
    -- Guarded to go NULL -> timestamp and never back; delta, kind, ref
    -- and lot_id remain immutable, so the append-only rule that matters
    -- (nothing about the MONEY is ever updated) still holds.
    submitted_at  TEXT,
    created_at    TEXT   NOT NULL
);
"""

# Written after own_table, because both name account_id and the column
# does not exist until then.
#
# The lots index is the webhook guard: Stripe delivers at least once, so
# a payment intent replayed an hour later must not grant a second time.
# NULLS NOT DISTINCT (Postgres 15+) is what makes it hold for the
# unowned pool too -- with the default, two grants with a NULL
# account_id and the same source_ref are "different" rows and both land.
#
# The entries index is the belt to `hold`'s braces: the advisory lock is
# what actually makes a retried hold idempotent, and this is what still
# refuses a duplicate if some future caller writes an entry without
# taking it. (account_id, kind, ref, lot_id) rather than
# (account_id, kind, ref) because ONE hold may span several lots.
INDEXES = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_lots_source
    ON credit_lots (account_id, kind, source_ref)
    NULLS NOT DISTINCT
    WHERE source_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_credit_lots_account
    ON credit_lots (account_id, expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_entries_ref
    ON credit_entries (account_id, kind, ref, lot_id)
    NULLS NOT DISTINCT
    WHERE ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_credit_entries_account
    ON credit_entries (account_id, lot_id);
"""


def init(dsn: Optional[str] = None) -> None:
    """Create both tables, own them, index them. Safe to run repeatedly.

    `add_nightly_runs_table`'s idempotent shape: every statement is
    CREATE ... IF NOT EXISTS, so the dev server's re-import on save runs
    this a hundred times a day for free. Registered in app/main.py's
    lifespan and in tests/test_tenancy.py::_init_everything -- without
    both, the schema audit never sees these tables and cannot tell you
    they were never decided about.
    """
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA)
        # submitted_at landed a day after the tables did and no database
        # in the world had shipped them yet -- but the dev server had
        # already run init() a hundred times, so the additive ALTER is
        # here for the same reason db.add_legacy_column is: the CREATE
        # above covers a fresh database and this covers the one on the
        # machine you are typing on.
        if "submitted_at" not in db.columns(conn, "credit_entries"):
            conn.execute("ALTER TABLE credit_entries ADD COLUMN submitted_at TEXT")
        db.own_table(conn, "credit_lots")
        db.own_table(conn, "credit_entries")
        conn.execute(INDEXES)


# --------------------------------------------------------------------------
# time
# --------------------------------------------------------------------------

def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _parse(stamp: str) -> datetime:
    dt = datetime.fromisoformat(stamp)
    return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)


def _plus_months(stamp: str, months: int) -> str:
    """`granted_at + EXPIRY_MONTHS`, clamping the day.

    Hand-rolled rather than dateutil because nothing else in this repo
    pulls that in for one call, and the only hard case is the one
    everybody gets wrong: the 31st of a month whose successor is
    shorter. 31 December + 2 months is 28 February, not 3 March -- a
    lot must never expire LATER than the month arithmetic says, or an
    account keeps credit it was told it would lose.
    """
    dt = _parse(stamp)
    month_index = dt.month - 1 + months
    year = dt.year + month_index // 12
    month = month_index % 12 + 1
    # the last day of the target month, without calendar.monthrange's import
    next_month = datetime(year + (month == 12), month % 12 + 1, 1, tzinfo=timezone.utc)
    last_day = (next_month - timedelta(days=1)).day
    return dt.replace(year=year, month=month, day=min(dt.day, last_day)).isoformat()


# --------------------------------------------------------------------------
# the lock
# --------------------------------------------------------------------------

def _lock(conn, account_id: Optional[int]) -> None:
    """Serialise every balance-changing operation on ONE account.

    Transaction-scoped, so it releases on commit *or* rollback: a worker
    that dies holding it cannot wedge an account's balance forever,
    which a `FOR UPDATE` on a balance row would also give but only if
    every future writer remembers to take it. Keyed per account, so two
    customers never contend, and the critical section is one SELECT and
    one INSERT.

    COALESCE, and the reason is not cosmetic: `'credit:' || NULL` is
    NULL, and `pg_advisory_xact_lock(NULL)` returns NULL having locked
    NOTHING -- so on the unowned pool (account_id NULL, which is every
    row on a database that has not been seeded) the lock would silently
    not exist and the concurrency test would pass for the wrong reason.
    """
    conn.execute(
        "SELECT pg_advisory_xact_lock(hashtext('credit:' || COALESCE(%s::text, '-')))",
        (account_id,),
    )


# --------------------------------------------------------------------------
# reads
# --------------------------------------------------------------------------

def _available(conn, account_id: Optional[int], now: Optional[str] = None) -> int:
    """The available balance, from the entries -- the truth, not the
    denormalised `credits_remaining`.

    Two rules in one query. Per lot, `SUM(delta)` is what that lot has
    left: a grant, minus its holds, plus its releases, adjusted by its
    settles. Then a lot PAST ITS EXPIRY DATE contributes nothing --
    enforced on read, so a balance is right in the window between the
    date passing and `expire_due()` sweeping.

    The `LEAST(..., 0)` is the part worth reading twice. An expired lot
    is clamped to zero from ABOVE only: its unspent credit is gone, but
    an overdraft sitting on it (a settle that exceeded its estimate --
    money that WAS spent) survives its expiry. Clamp both ways and a
    customer who overdrew simply waits two months for the debt to
    evaporate.
    """
    now = now or _now()
    row = conn.execute(
        """
        SELECT COALESCE(SUM(net), 0) AS available FROM (
            SELECT CASE
                     WHEN l.expires_at IS NOT NULL AND l.expires_at <= %s
                     THEN LEAST(SUM(e.delta), 0)
                     ELSE SUM(e.delta)
                   END AS net
            FROM credit_entries e
            LEFT JOIN credit_lots l
                   ON l.id = e.lot_id
                  AND l.account_id IS NOT DISTINCT FROM e.account_id
            WHERE e.account_id IS NOT DISTINCT FROM %s
            GROUP BY e.lot_id, l.expires_at
        ) per_lot
        """,
        (now, account_id),
    ).fetchone()
    return int(row["available"] or 0)


def available(account_id: Optional[int], dsn: Optional[str] = None) -> int:
    """What this account can spend right now, in integer credits.

    Can be NEGATIVE: `settle()` is allowed to overdraw when the actual
    cost beat the estimate, because the money is already spent and
    pretending otherwise is the lie that breaks reconciliation. A
    negative balance is what refuses the next `hold`.
    """
    with db.connect(dsn) as conn:
        return _available(conn, account_id)


def lots(account_id: Optional[int], dsn: Optional[str] = None,
         *, include_expired: bool = True) -> list[dict[str, Any]]:
    """This account's lots, soonest-expiry first -- the order credit is
    consumed in, so the list reads as the burn-down it is."""
    now = _now()
    with db.connect(dsn) as conn:
        rows = conn.execute(
            "SELECT * FROM credit_lots WHERE account_id IS NOT DISTINCT FROM %s "
            "AND (%s OR expires_at IS NULL OR expires_at > %s) "
            "ORDER BY expires_at ASC NULLS LAST, id ASC",
            (account_id, bool(include_expired), now),
        ).fetchall()
        return [dict(r) for r in rows]


def entries(account_id: Optional[int], dsn: Optional[str] = None,
            *, ref: Optional[str] = None) -> list[dict[str, Any]]:
    """The audit trail, oldest first. `ref` narrows it to one hold's
    whole lifecycle -- the hold, its settle or its release."""
    with db.connect(dsn) as conn:
        if ref is None:
            rows = conn.execute(
                "SELECT * FROM credit_entries WHERE account_id IS NOT DISTINCT FROM %s "
                "ORDER BY id ASC", (account_id,)).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM credit_entries WHERE account_id IS NOT DISTINCT FROM %s "
                "AND ref = %s ORDER BY id ASC", (account_id, ref)).fetchall()
        return [dict(r) for r in rows]


def outstanding(account_id: Optional[int], dsn: Optional[str] = None) -> int:
    """Credits this account is holding against renders in flight --
    the part of its balance that is committed but not yet consumed."""
    with db.connect(dsn) as conn:
        row = conn.execute(
            """
            SELECT COALESCE(-SUM(h.delta), 0) AS held
            FROM credit_entries h
            WHERE h.account_id IS NOT DISTINCT FROM %s AND h.kind = 'hold'
              AND NOT EXISTS (
                    SELECT 1 FROM credit_entries d
                    WHERE d.account_id IS NOT DISTINCT FROM h.account_id
                      AND d.ref = h.ref AND d.kind IN ('settle', 'release'))
            """,
            (account_id,),
        ).fetchone()
        return int(row["held"] or 0)


def outstanding_everyone(dsn: Optional[str] = None) -> int:
    """Every account's outstanding holds, added up: YOUR LIABILITY.

    The one deliberately installation-wide read in this module, and it
    is in tests/test_tenancy.py::UNSCOPED_ALLOWED with that reason.
    `generative.used_today(everyone=True)` and
    `spend.spent_today_everyone` are its two siblings: a number about
    the installation's own books is not a number about anybody's rows,
    and scoping it to an account would make it a different, useless
    number.
    """
    with db.connect(dsn) as conn:
        row = conn.execute(
            """
            SELECT COALESCE(-SUM(h.delta), 0) AS held
            FROM credit_entries h
            WHERE h.kind = 'hold' AND NOT EXISTS (
                    SELECT 1 FROM credit_entries d
                    WHERE d.ref = h.ref AND d.kind IN ('settle', 'release'))
            """
        ).fetchone()
        return int(row["held"] or 0)


def reconcile(account_id: Optional[int], dsn: Optional[str] = None) -> list[dict[str, Any]]:
    """Per lot: `SUM(delta)` from the entries against the denormalised
    `credit_lots.credits_remaining`, and the drift between them.

    The entries are the truth and `credits_remaining` is a running
    figure kept for the queries that pick lots to spend from. They must
    agree; a test asserts they do after every operation in this module.
    An empty result from a non-empty account means someone wrote a lot
    without its grant entry.
    """
    with db.connect(dsn) as conn:
        rows = conn.execute(
            """
            SELECT l.id, l.kind, l.credits_remaining,
                   COALESCE((SELECT SUM(e.delta) FROM credit_entries e
                             WHERE e.lot_id = l.id
                               AND e.account_id IS NOT DISTINCT FROM l.account_id), 0)
                   AS entry_sum
            FROM credit_lots l
            WHERE l.account_id IS NOT DISTINCT FROM %s
            ORDER BY l.id
            """,
            (account_id,),
        ).fetchall()
        return [{"lot_id": r["id"], "kind": r["kind"],
                 "credits_remaining": int(r["credits_remaining"]),
                 "entry_sum": int(r["entry_sum"]),
                 "drift": int(r["credits_remaining"]) - int(r["entry_sum"])}
                for r in rows]


# --------------------------------------------------------------------------
# the write primitive
# --------------------------------------------------------------------------

def _entry(conn, *, account_id: Optional[int], lot_id: Optional[int], delta: int,
           kind: str, ref: Optional[str], generation_id: Optional[int] = None,
           provider: Optional[str] = None) -> int:
    """One append-only movement, plus the lot's running figure.

    The pair is deliberately inseparable and deliberately in the same
    transaction as its caller: an entry without its
    `credits_remaining` update is a drift `reconcile()` would find
    tomorrow, and an update without its entry is a balance with no audit
    trail behind it.
    """
    if kind not in ENTRY_KINDS:
        raise LedgerError(f"entry kind must be one of {ENTRY_KINDS}, got {kind!r}")
    row = conn.execute(
        "INSERT INTO credit_entries "
        "(account_id, lot_id, delta, kind, ref, generation_id, provider, created_at) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
        (account_id, lot_id, int(delta), kind, ref, generation_id, provider, _now()),
    ).fetchone()
    if lot_id is not None:
        conn.execute(
            "UPDATE credit_lots SET credits_remaining = credits_remaining + %s "
            "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (int(delta), lot_id, account_id),
        )
    return int(row["id"])


def _debit(conn, *, account_id: Optional[int], amount: int, kind: str, ref: str,
           generation_id: Optional[int] = None, provider: Optional[str] = None,
           overdraft_lot_id: Optional[int] = None) -> None:
    """Take `amount` credits soonest-expiry-first, overdrawing if it does
    not fit. The ordinary consumption order, in one place.

    `hold` does its own allocation because it must refuse rather than
    overdraw and it has already computed the balance under the lock.
    This is the other kind of debit -- `settle`'s adjustment, where the
    money is spent and refusing is not one of the options -- so what
    does not fit lands on `overdraft_lot_id` and the balance goes
    negative. Same order either way, which is the point: a customer
    should not be able to tell where a debit came from by looking at
    which lot it drained.
    """
    now = _now()
    wanted = int(amount)
    rows = conn.execute(
        "SELECT id, credits_remaining FROM credit_lots "
        "WHERE account_id IS NOT DISTINCT FROM %s AND credits_remaining > 0 "
        "AND (expires_at IS NULL OR expires_at > %s) "
        "ORDER BY expires_at ASC NULLS LAST, id ASC",
        (account_id, now),
    ).fetchall()
    for row in rows:
        if wanted <= 0:
            break
        take = min(wanted, int(row["credits_remaining"]))
        _entry(conn, account_id=account_id, lot_id=int(row["id"]), delta=-take,
               kind=kind, ref=ref, generation_id=generation_id, provider=provider)
        wanted -= take
    if wanted > 0:
        _entry(conn, account_id=account_id, lot_id=overdraft_lot_id, delta=-wanted,
               kind=kind, ref=ref, generation_id=generation_id, provider=provider)


# --------------------------------------------------------------------------
# grant
# --------------------------------------------------------------------------

def grant(account_id: Optional[int], credits: int, kind: str, *,
          source_ref: Optional[str] = None, note: Optional[str] = None,
          granted_at: Optional[str] = None, expires_at: Optional[str] = None,
          dsn: Optional[str] = None) -> int:
    """Add a lot of credit. Returns the lot id. RAISES on anything wrong.

    `source_ref` is the Stripe payment intent or the subscription period
    id, and it is the webhook guard: a second delivery of the same event
    hits the unique index on (account_id, kind, source_ref) and returns
    THE EXISTING LOT rather than granting twice. That check is done by
    reading first -- inside the account's advisory lock, so two
    deliveries racing each other cannot both find nothing.

    `expires_at` defaults to EXPIRY_MONTHS after the grant. Pass it
    explicitly only where a plan really does say something else; the
    default is the policy.
    """
    credits = int(credits)
    if credits <= 0:
        raise LedgerError(f"a grant must be positive, got {credits}")
    if kind not in LOT_KINDS:
        raise LedgerError(f"lot kind must be one of {LOT_KINDS}, got {kind!r}")
    granted_at = granted_at or _now()
    if expires_at is None:
        expires_at = _plus_months(granted_at, EXPIRY_MONTHS)

    with db.connect(dsn) as conn:
        _lock(conn, account_id)
        if source_ref is not None:
            existing = conn.execute(
                "SELECT id FROM credit_lots WHERE account_id IS NOT DISTINCT FROM %s "
                "AND kind = %s AND source_ref = %s",
                (account_id, kind, source_ref),
            ).fetchone()
            if existing:
                return int(existing["id"])
        lot_id = conn.execute(
            "INSERT INTO credit_lots (account_id, kind, credits_granted, "
            "credits_remaining, granted_at, expires_at, source_ref, note) "
            "VALUES (%s, %s, %s, 0, %s, %s, %s, %s) RETURNING id",
            (account_id, kind, credits, granted_at, expires_at, source_ref, note),
        ).fetchone()["id"]
        # credits_remaining starts at 0 and the grant ENTRY is what puts
        # the credit in it, so the invariant reconcile() checks holds
        # from the lot's first instant rather than from its second.
        _entry(conn, account_id=account_id, lot_id=int(lot_id), delta=credits,
               kind="grant", ref=source_ref or f"grant:lot:{lot_id}")
        return int(lot_id)


# --------------------------------------------------------------------------
# hold -- the atomic one
# --------------------------------------------------------------------------

def _hold_group(conn, hold_id: int) -> tuple[Optional[int], str, list[dict]]:
    """(account_id, ref, the hold's entries in the order they were
    taken) for a hold id. Raises if it is not a hold."""
    head = conn.execute(
        "SELECT id, account_id, ref FROM credit_entries WHERE id = %s AND kind = 'hold'",
        (hold_id,),
    ).fetchone()
    if not head:
        raise LedgerError(f"no hold with id {hold_id}")
    account_id, ref = head["account_id"], head["ref"]
    rows = conn.execute(
        "SELECT * FROM credit_entries WHERE account_id IS NOT DISTINCT FROM %s "
        "AND ref = %s AND kind = 'hold' ORDER BY id ASC",
        (account_id, ref),
    ).fetchall()
    return account_id, ref, [dict(r) for r in rows]


def _resolved(conn, account_id: Optional[int], ref: str) -> Optional[str]:
    """'settle' or 'release' if this hold is already finished, else None."""
    row = conn.execute(
        "SELECT kind FROM credit_entries WHERE account_id IS NOT DISTINCT FROM %s "
        "AND ref = %s AND kind IN ('settle', 'release') LIMIT 1",
        (account_id, ref),
    ).fetchone()
    return row["kind"] if row else None


def hold(account_id: Optional[int], credits: int, *, ref: str, provider: str,
         estimate_usd: Optional[float] = None, dsn: Optional[str] = None) -> int:
    """Commit `credits` against this account, or raise InsufficientCredit.
    Returns a hold id to settle or release. Nothing has been spent yet.

    ONE TRANSACTION, AND THE ORDER INSIDE IT IS THE WHOLE POINT:

        1. pg_advisory_xact_lock on this account
        2. is this `ref` already held?  -> return the existing hold
        3. compute the available balance
        4. insert the negative entries, soonest-expiry lot first
        5. commit, which releases the lock

    Read-then-act is only safe between 1 and 5. `generative.cap_error`
    is the same shape WITHOUT the lock, which is why two simultaneous
    approvals can both pass a cap of six -- an annoyance there, and
    money here. Two concurrent holds on a balance that fits one: exactly
    one commits, the other sees the first's entries and raises.

    `ref` IS THE IDEMPOTENCY KEY. A caller that retries across a network
    blip gets the same hold id back rather than a second debit, and the
    unique index on (account_id, kind, ref, lot_id) is the backstop if
    some future writer skips the lock.

    `provider` and the estimate are the reaper's evidence -- without
    them it cannot tell a dead render from a slow one. The estimate is
    stored as the hold's own `delta`, in credits, rather than as a
    dollars column: no float goes on this path. `estimate_usd` is
    accepted for the caller's convenience (`hold_for_render` converts
    with it) and reconciled against `credits` rather than stored.
    """
    credits = int(credits)
    if credits <= 0:
        raise LedgerError(f"a hold must be positive, got {credits}")
    if not ref:
        raise LedgerError("a hold needs a ref -- it is the idempotency key")
    if estimate_usd is not None and credits_for_usd(estimate_usd) != credits:
        raise LedgerError(
            f"hold of {credits} credits does not match estimate_usd {estimate_usd} "
            f"({credits_for_usd(estimate_usd)} credits) -- convert once, at "
            f"credits_for_usd, and pass the same number to both")

    now = _now()
    with db.connect(dsn) as conn:
        _lock(conn, account_id)

        prior = conn.execute(
            "SELECT MIN(id) AS id FROM credit_entries "
            "WHERE account_id IS NOT DISTINCT FROM %s AND ref = %s AND kind = 'hold'",
            (account_id, ref),
        ).fetchone()
        if prior and prior["id"] is not None:
            return int(prior["id"])

        have = _available(conn, account_id, now)
        if have < credits:
            raise InsufficientCredit(account_id, credits, have)

        rows = conn.execute(
            "SELECT id, credits_remaining FROM credit_lots "
            "WHERE account_id IS NOT DISTINCT FROM %s AND credits_remaining > 0 "
            "AND (expires_at IS NULL OR expires_at > %s) "
            "ORDER BY expires_at ASC NULLS LAST, id ASC",
            (account_id, now),
        ).fetchall()

        wanted, first_id = credits, None
        for row in rows:
            if wanted <= 0:
                break
            take = min(wanted, int(row["credits_remaining"]))
            entry_id = _entry(conn, account_id=account_id, lot_id=int(row["id"]),
                              delta=-take, kind="hold", ref=ref, provider=provider)
            first_id = first_id or entry_id
            wanted -= take
        if wanted > 0:
            # The balance said yes and the lots could not pay it. That is
            # a corrupted ledger, not a poor customer -- raising rolls
            # the whole transaction back, which is why the lot rows are
            # only ever touched inside one.
            raise LedgerError(
                f"account {account_id}: available balance {have} but only "
                f"{credits - wanted} credits found in unexpired lots -- run "
                f"ledger.reconcile()")
        return int(first_id)


def mark_submitted(hold_id: int, dsn: Optional[str] = None) -> str:
    """Stamp a hold the instant before the provider call. Returns the
    stamp. Idempotent: a second call returns the first one's timestamp.

    WHY THIS EXISTS. Without it, "the render never happened" and "the
    render was submitted, the provider billed, and the worker died
    before anything recorded it" are the same observation -- an
    outstanding hold with no `generations` row -- and they have opposite
    correct answers. Releasing the first is right; releasing the second
    gives away a render you paid for and, worse, erases the only
    evidence that it happened.

    It goes between `hold_for_render` and the submit, in the same few
    lines:

        hold_id = ledger.hold_for_render(...)
        ledger.mark_submitted(hold_id)        # <- here
        task = client.image_to_video.create(...)

    The window between the stamp and the HTTP call is the one this
    cannot close, and it is deliberately the safe side to be wrong on:
    a stamp with no submit reads as an orphan a human looks at and
    releases by hand, while a submit with no stamp is money silently
    given back.
    """
    stamp = _now()
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT account_id, ref, submitted_at FROM credit_entries "
            "WHERE id = %s AND kind = 'hold'", (hold_id,)).fetchone()
        if not row:
            raise LedgerError(f"no hold with id {hold_id}")
        if row["submitted_at"]:
            return str(row["submitted_at"])
        # Every entry of the hold, because a hold may span several lots
        # and the fact being recorded is about the RENDER, not the lot.
        # NULL-guarded so a re-stamp can never move a submit time
        # backwards or forwards -- the column goes NULL -> value, once.
        conn.execute(
            "UPDATE credit_entries SET submitted_at = %s "
            "WHERE account_id IS NOT DISTINCT FROM %s AND ref = %s "
            "AND kind = 'hold' AND submitted_at IS NULL",
            (stamp, row["account_id"], row["ref"]),
        )
        return stamp


# --------------------------------------------------------------------------
# settle / release
# --------------------------------------------------------------------------

def settle(hold_id: int, actual_usd, *, generation_id: Optional[int] = None,
           dsn: Optional[str] = None) -> int:
    """Close a hold at what the render ACTUALLY cost. Returns net credits
    debited (which is `credits_for_usd(actual_usd)`).

    Three cases, and only the third is interesting:

    - actual == estimate: a zero-delta `settle` entry, written anyway,
      because the audit trail must record that the hold was closed and
      must carry `generation_id` -- the link from money to the clip.
    - actual < estimate: the difference goes back, to the lots the hold
      took it from, in REVERSE order of consumption, capped at what each
      one gave. Symmetric with the burn-down, so a refund cannot put
      credit back on a lot that never funded it.
    - actual > estimate: THE DIFFERENCE IS DEBITED ANYWAY, even into a
      negative balance. The money is already spent -- the provider
      submitted, billed, and does not care about this table. Clamping
      here would make the ledger disagree with the invoice, which is the
      one thing it exists not to do, and the NEXT `hold()` is refused
      because `available()` is now negative.

    WHERE THE EXTRA DEBIT LANDS is the part that took a second pass.
    It is an ordinary debit and it is taken in the ordinary order --
    soonest-expiry-first across this account's unexpired lots, exactly
    as `hold` allocates. The first version put it all on the LAST lot
    the hold touched, which is the latest-expiring one, so a render
    that beat its estimate drove the customer's PURCHASED credit
    negative while an already-empty subscription lot sat at zero:
    the debt landed on the credit they still owned rather than on the
    credit they were spending.

    When nothing is left anywhere -- the usual case, since the hold had
    just emptied those lots -- the genuine overdraft has no lot with
    credit to sit on, and it goes on the SOONEST-EXPIRING lot the hold
    drew from. That tie-break is not arbitrary: it is where the
    burn-down was, and `_available` clamps an expired lot from above
    only, so a debt parked there survives the lot's expiry instead of
    evaporating with it.
    """
    debit = credits_for_usd(actual_usd)
    with db.connect(dsn) as conn:
        # The hold's own rows are append-only and immutable, so reading
        # them before the lock is safe; everything that could CHANGE
        # (whether it has already been settled or released, and the
        # entries this settle writes) happens after it.
        account_id, ref, holds = _hold_group(conn, hold_id)
        _lock(conn, account_id)
        already = _resolved(conn, account_id, ref)
        if already == "settle":
            return debit
        if already == "release":
            raise LedgerError(f"hold {hold_id} was already released; it cannot settle")

        held = sum(-int(h["delta"]) for h in holds)
        diff = debit - held
        if diff == 0:
            _entry(conn, account_id=account_id, lot_id=holds[0]["lot_id"], delta=0,
                   kind="settle", ref=ref, generation_id=generation_id,
                   provider=holds[0]["provider"])
        elif diff < 0:
            back = -diff
            for h in reversed(holds):
                if back <= 0:
                    break
                give = min(back, -int(h["delta"]))
                _entry(conn, account_id=account_id, lot_id=h["lot_id"], delta=give,
                       kind="settle", ref=ref, generation_id=generation_id,
                       provider=h["provider"])
                back -= give
        else:
            _debit(conn, account_id=account_id, amount=diff, kind="settle", ref=ref,
                   generation_id=generation_id, provider=holds[0]["provider"],
                   overdraft_lot_id=holds[0]["lot_id"])
        return debit


def release(hold_id: int, reason: str, dsn: Optional[str] = None) -> int:
    """Give the whole hold back. Returns the credits restored.

    A provider error, a timeout, or a QC failure: the customer pays
    nothing and the cost lands in `waste_usd` -- the number that makes
    "we refund failed renders" a real line on your books rather than a
    slogan. Reversed entry by entry rather than as one lump, so each
    lot gets back exactly what it gave and the expiry clock it was
    granted under still governs the credit.

    `reason` is required and is deliberately NOT stored: the entries
    table has no free-text column and should not grow one -- a reason
    field on an append-only money table becomes the place people put
    the thing they should have modelled. It belongs in the caller's log
    and on the hold row the Queue shows. It is still an argument,
    because a release nobody can say the reason for is the one that
    turns out to have been a bug.
    """
    if not reason:
        raise LedgerError("a release needs a reason")
    with db.connect(dsn) as conn:
        account_id, ref, holds = _hold_group(conn, hold_id)
        _lock(conn, account_id)
        already = _resolved(conn, account_id, ref)
        if already == "release":
            return sum(-int(h["delta"]) for h in holds)
        if already == "settle":
            raise LedgerError(f"hold {hold_id} was already settled; it cannot release")
        restored = 0
        for h in holds:
            give = -int(h["delta"])
            _entry(conn, account_id=account_id, lot_id=h["lot_id"], delta=give,
                   kind="release", ref=ref, provider=h["provider"])
            restored += give
        return restored


# --------------------------------------------------------------------------
# expiry and lapse
# --------------------------------------------------------------------------

def _expire_lot(conn, account_id: Optional[int], lot: dict) -> int:
    """Write the `expire` entry for one lot. Returns credits expired.

    NEVER ZEROES THE LOT IN PLACE. The design doc's open question --
    whether credit expired by lapse is restored when somebody
    resubscribes -- is answerable either way only while the movement is
    a row: an `expire` entry of -400 can be reversed by a +400 grant
    that cites it, whereas an UPDATE that set credits_remaining = 0
    has destroyed the number it would have to restore.

    A lot with nothing left, or one already overdrawn, gets no entry:
    there is nothing to take, and taking a NEGATIVE remainder would
    write a POSITIVE delta -- expiry handing a customer who overdrew a
    gift.
    """
    remaining = int(lot["credits_remaining"])
    if remaining <= 0:
        return 0
    _entry(conn, account_id=account_id, lot_id=int(lot["id"]), delta=-remaining,
           kind="expire", ref=f"expire:lot:{lot['id']}")
    return remaining


def expire_due(account_id: Optional[int] = None, *, now: Optional[str] = None,
               dsn: Optional[str] = None) -> int:
    """Sweep every lot past its expiry date. Returns credits expired.

    `account_id=None` sweeps the whole installation, which is what the
    nightly walk wants; pass one to sweep a single account. The
    predicate is in the SQL either way -- `%s IS NULL OR account_id IS
    NOT DISTINCT FROM %s` -- so this is a scoped query the operator is
    allowed to widen, not an unscoped one with an excuse.

    Expiry is ALSO enforced on read (`_available`), so this sweep is
    about the audit trail, not about correctness of the balance: it is
    what makes the ledger say where the credit went instead of leaving
    a lot that silently stopped counting.
    """
    now = now or _now()
    expired = 0
    with db.connect(dsn) as conn:
        if account_id is not None:
            _lock(conn, account_id)
        rows = conn.execute(
            "SELECT id, account_id, credits_remaining FROM credit_lots "
            "WHERE (%s::bigint IS NULL OR account_id IS NOT DISTINCT FROM %s) "
            "AND expires_at IS NOT NULL AND expires_at <= %s AND credits_remaining > 0 "
            "ORDER BY id ASC",
            (account_id, account_id, now),
        ).fetchall()
        for row in rows:
            # One lock per account touched, taken inside the same
            # transaction so they all release together on commit. The
            # installation-wide sweep must not serialise on one global
            # key: two customers expiring have nothing to do with each
            # other, and a lock they share is a lock that will one day
            # be held while somebody's hold waits behind it.
            if account_id is None:
                _lock(conn, row["account_id"])
            expired += _expire_lot(conn, row["account_id"], dict(row))
    return expired


def on_subscription_lapsed(account_id: Optional[int], dsn: Optional[str] = None) -> int:
    """The subscription ended: expire every lot whose kind says it dies.
    Returns credits expired.

    Called by whatever owns subscription state -- Stripe's webhook,
    later. The policy is LAPSE_POLICY and it is read here rather than
    written into the SQL, so softening `purchase` (which the design doc
    flags as the entry that draws chargebacks) is a one-line change with
    no migration behind it.

    A lot whose kind is not in LAPSE_POLICY survives, deliberately:
    `adjustment` -- the operator's own correction -- should not be undone
    by a billing event, and a kind added later defaults to surviving,
    which is the safe direction for something nobody has decided about.
    """
    dying = tuple(k for k, dies in LAPSE_POLICY.items() if dies)
    if not dying:
        return 0
    expired = 0
    with db.connect(dsn) as conn:
        _lock(conn, account_id)
        rows = conn.execute(
            "SELECT id, credits_remaining FROM credit_lots "
            "WHERE account_id IS NOT DISTINCT FROM %s AND kind = ANY(%s) "
            "AND credits_remaining > 0 ORDER BY id ASC",
            (account_id, list(dying)),
        ).fetchall()
        for row in rows:
            expired += _expire_lot(conn, account_id, dict(row))
    return expired


# --------------------------------------------------------------------------
# the reaper -- the thing that will actually go wrong
# --------------------------------------------------------------------------

def _log(message: str) -> None:
    print(f"[ledger] {message}", file=sys.stderr)


def _outstanding_holds(conn, account_id: Optional[int], cutoff: str) -> list[dict]:
    rows = conn.execute(
        """
        SELECT MIN(h.id) AS hold_id, h.account_id, h.ref, h.provider,
               -SUM(h.delta) AS held, MIN(h.created_at) AS created_at,
               MIN(h.submitted_at) AS submitted_at
        FROM credit_entries h
        WHERE (%s::bigint IS NULL OR h.account_id IS NOT DISTINCT FROM %s)
          AND h.kind = 'hold' AND h.created_at < %s
          AND NOT EXISTS (
                SELECT 1 FROM credit_entries d
                WHERE d.account_id IS NOT DISTINCT FROM h.account_id
                  AND d.ref = h.ref AND d.kind IN ('settle', 'release'))
        GROUP BY h.account_id, h.ref, h.provider
        ORDER BY MIN(h.id)
        """,
        (account_id, account_id, cutoff),
    ).fetchall()
    return [dict(r) for r in rows]


def _generation_for(conn, account_id: Optional[int], ref: str) -> Optional[dict]:
    """The `generations` row the render would have written, found by the
    `ledger_ref` an adapter puts in its params (see `ref_params`).

    Matched as a string rather than by casting params_json to jsonb:
    the column is TEXT written by json.dumps at several call sites, and
    one malformed row would make the cast raise for every hold in the
    sweep. A LIKE that finds nothing is the same answer as a row that
    is not there, which is exactly how the reaper should read it.
    """
    if not db.table_exists(conn, "generations"):
        return None
    row = conn.execute(
        "SELECT id, cost_usd, output_path, reject_reason FROM generations "
        "WHERE account_id IS NOT DISTINCT FROM %s AND params_json LIKE %s "
        "ORDER BY id DESC LIMIT 1",
        (account_id, f'%"{GENERATION_REF_KEY}": "{ref}"%'),
    ).fetchone()
    return dict(row) if row else None


def reap(older_than=DEFAULT_REAP_AGE, *, account_id: Optional[int] = None,
         dsn: Optional[str] = None) -> dict[str, Any]:
    """Close holds that outlived their renders. Runs on the nightly's
    schedule. Returns {"settled": [...], "released": [...], "orphaned": [...]}.

    A worker dies between submit and settle and the hold is a
    customer's balance held hostage forever. So for each outstanding
    hold past its age, look for the `generations` row the render would
    have written -- and, when it is not there, at whether the hold was
    ever stamped by `mark_submitted`:

    - found and usable (an output path, no reject reason) -> SETTLE at
      its `cost_usd`, falling back to the estimate the hold carries when
      the row was never priced.
    - found and failed -> RELEASE. The customer pays nothing; the cost
      lands in `waste_usd`.
    - absent, and NEVER SUBMITTED -> RELEASE, quietly. The render did
      not happen: the process died between the hold and the provider
      call, or the caller raised before it. Nothing was billed, so
      giving the credit back is simply correct and needs no attention.
    - absent, but SUBMITTED -> **ORPHANED.** Money was spent and
      nothing recorded it. The hold is LEFT OUTSTANDING, deliberately,
      and logged loudly.

    WHY AN ORPHAN IS NOT RELEASED. Releasing it would return the
    customer's credit for a render the provider really did bill you
    for, and -- the worse half -- it would erase the only trace that
    the discrepancy ever existed: an outstanding hold is visible in
    `outstanding()` and in every sweep from here on, while a released
    one is a closed pair of rows that looks exactly like a refunded
    failure. So an orphan stays open until a person decides, and it is
    reported on every subsequent run, on purpose, because a real-money
    discrepancy that stops being mentioned is one nobody fixes. The
    two ways to close one by hand, once somebody has looked at the
    provider's dashboard:

        settle(hold_id, actual_usd, generation_id=...)   # it did render
        release(hold_id, "orphan: provider has no record")

    `older_than` takes a timedelta (an age, the usual call) or a
    datetime (a cutoff, for a test that does not want to sleep).
    """
    if isinstance(older_than, timedelta):
        cutoff = (datetime.now(timezone.utc) - older_than).isoformat()
    elif isinstance(older_than, datetime):
        cutoff = older_than.isoformat()
    else:
        cutoff = str(older_than)

    settled: list[int] = []
    released: list[int] = []
    orphaned: list[int] = []
    with db.connect(dsn) as conn:
        pending = _outstanding_holds(conn, account_id, cutoff)
        found = {h["hold_id"]: _generation_for(conn, h["account_id"], h["ref"])
                 for h in pending}

    for h in pending:
        hold_id = int(h["hold_id"])
        gen = found.get(hold_id)
        usable = bool(gen and gen.get("output_path") and not gen.get("reject_reason"))
        if usable:
            actual = gen.get("cost_usd")
            actual_usd = float(actual) if actual is not None else int(h["held"]) / 100
            settle(hold_id, actual_usd, generation_id=int(gen["id"]), dsn=dsn)
            settled.append(hold_id)
            continue
        if gen is None:
            if h.get("submitted_at"):
                _log(f"ORPHAN HOLD {hold_id} ({h['provider']}, ref={h['ref']}, "
                     f"{h['held']} credits, submitted {h['submitted_at']}): the "
                     f"provider was submitted and NO generations row exists. That "
                     f"render was paid for and nothing recorded it. The hold is "
                     f"left outstanding on purpose -- releasing it would hand back "
                     f"credit for a render you were billed for and erase the only "
                     f"evidence of the loss. Check the provider's dashboard, then "
                     f"settle() or release() it by hand.")
                orphaned.append(hold_id)
                continue
            reason = "reaped: never submitted"
        else:
            reason = f"reaped: render failed ({gen.get('reject_reason') or 'no output'})"
        release(hold_id, reason, dsn=dsn)
        released.append(hold_id)
    return {"settled": settled, "released": released, "orphaned": orphaned}


# --------------------------------------------------------------------------
# the seam the render path will call
# --------------------------------------------------------------------------

def hold_for_render(account_id: Optional[int], *, ref: str, provider: str,
                    estimate_usd, key_source: Optional[str] = None,
                    dsn: Optional[str] = None) -> Optional[int]:
    """Take the hold for one render, or None when the render is not
    billable. THE SEAM -- NOTHING CALLS IT YET, ON PURPOSE.

    WHERE THIS CALL GOES, when the wiring pass happens (this pass builds
    the module and its tests only; the adapters keep working exactly as
    they do today):

    - `src/runway.py::generate_video`, immediately before
      `client.image_to_video.create(...)` -- the single irreversible
      submit, currently around line 243, after the spend gate and after
      the client is built.
    - `src/higgsfield.py::_submit_and_wait`, immediately before
      `http(HOST + path, body)` -- the submit that every higgsfield
      render (video, soul, the lot) funnels through.
    - `src/veo.py::generate_video`, immediately before
      `client.models.generate_videos(...)`.

    BEFORE the submit, never after: everything before that HTTP call is
    intention and everything after it is bookkeeping the provider does
    not care about. Today the `generations` row -- the only record that
    a render happened -- is written after the call returns, across a
    poll loop that can run for minutes, so a crash in that window means
    the provider billed and nothing here knows. If this raises,
    InsufficientCredit or otherwise, no HTTP call is made and no money
    moves.

    The caller owes three things, and the reaper covers only the third:

        ledger.mark_submitted(hold_id)                   # LAST line before the submit
        ...the provider call...
        settle(hold_id, actual_usd, generation_id=...)   # delivered, passed QC
        release(hold_id, "provider error: ...")          # failed, timed out, QC'd out

    and must pass `ledger.ref_params(ref)` into the render's
    `generations` params, or the reaper cannot match the hold to the row.

    `mark_submitted` is not optional bookkeeping. It is what lets the
    reaper tell a render that never happened (release it, quietly) from
    one the provider billed for and nothing recorded (leave it
    outstanding, shout about it). Skip it and every dead worker looks
    like a free refund.

    `key_source` is what `account_keys.key_source(account_id, provider)`
    returned for this render -- the same value the adapter already
    writes into `generations.params_json`. On "account" this returns
    None and takes NO hold: see `is_billable`.
    """
    if not is_billable(key_source):
        return None
    return hold(account_id, credits_for_usd(estimate_usd), ref=ref,
                provider=provider, estimate_usd=estimate_usd, dsn=dsn)


__all__ = [
    "EXPIRY_MONTHS", "LAPSE_POLICY", "LOT_KINDS", "ENTRY_KINDS",
    "GENERATION_REF_KEY", "BYOK_KEY_SOURCE",
    "LedgerError", "InsufficientCredit",
    "credits_for_usd", "is_billable", "ref_params",
    "init", "grant", "available", "lots", "entries", "outstanding",
    "outstanding_everyone", "reconcile",
    "hold", "mark_submitted", "settle", "release", "expire_due",
    "on_subscription_lapsed",
    "reap", "hold_for_render",
]
