"""
Who has connected Claude to their studio, and when it was last used
(2026-10-08, Mike's call: "I want to be able to access the MCP from the
studio page at the bottom near profile").

WHAT THE STUDIO CAN AND CANNOT KNOW. A connector is added FROM claude.ai
(or Claude Code), and nothing here can ask claude.ai what a person has
connected. What this app does see is both ends of ITS OWN half of the
flow, and those are the only two writers:

- **Allow.** The person presses Allow on /oauth/consent and Supabase
  answers with the client's redirect (`app/oauth_consent.consent_decision`).
  That is `record_approval`: the client's name and the redirect HOST the
  page showed them, stamped `approved_at`.
- **Use.** A request through the listed MCP door, after the caller has
  been resolved to an account (`app/mcp_mount.guarded`). That is `touch`,
  throttled IN THE MOUNT to once per person per account per window, so it
  never becomes a database write per MCP call. A use with no approval on
  file -- a connection made before this table existed, or one whose
  consent Supabase remembered and so never showed the page -- writes a
  row with no client name: a working token is proof of a connection.

The operator's static key never reaches either writer: it is a key on
Mike's machine, not a connection anybody made.

DISCONNECT IS CLAUDE'S. Removing the connector in claude.ai tells this
app nothing, and Supabase's grant list needs the person's own token,
which is never kept here. So a row is never deleted by a disconnect; the
panel shows `last_used_at` beside "connected" and says where to remove it.

One row per (account, person, client), so claude.ai and Claude Code are
two rows. OWNED (db.OWNED_TABLES): a connection is one account's.
Nothing here spends or reads the board.
"""
from __future__ import annotations

from typing import Any, Optional

from . import db

SCHEMA = """
CREATE TABLE IF NOT EXISTS mcp_connections (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT NOT NULL,
    user_id       TEXT   NOT NULL,
    client_name   TEXT   NOT NULL DEFAULT '',
    redirect_host TEXT,
    approved_at   TIMESTAMPTZ,
    last_used_at  TIMESTAMPTZ
);
"""

# '' rather than NULL for "a use before any approval named the client":
# a NULL would never collide in this index, and every untimed use would
# then be a new row.
INDEXES = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_mcp_connections_who
    ON mcp_connections (account_id, user_id, client_name);
"""

MAX_NAME = 200


def init(dsn: Optional[str] = None) -> None:
    """Create and own the table. Idempotent; the app lifespan runs it."""
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA)
        db.own_table(conn, "mcp_connections")
        conn.execute(INDEXES)


def record_approval(account_id: int, user_id: str, client_name: str,
                    redirect_host: str = "", dsn: Optional[str] = None) -> None:
    """The person pressed Allow for this client. A second Allow for the
    same client (removed in claude.ai and added again) moves approved_at."""
    name = (client_name or "").strip()[:MAX_NAME]
    host = (redirect_host or "").strip()[:MAX_NAME] or None
    with db.connect(dsn) as conn:
        conn.execute(
            "INSERT INTO mcp_connections (account_id, user_id, client_name, redirect_host, approved_at) "
            "VALUES (%s, %s, %s, %s, now()) "
            "ON CONFLICT (account_id, user_id, client_name) "
            "DO UPDATE SET approved_at = now(), redirect_host = EXCLUDED.redirect_host",
            (int(account_id), str(user_id), name, host))


def touch(account_id: int, user_id: str, dsn: Optional[str] = None) -> None:
    """The person's token was just used through the listed door.

    Stamps every client this person connected to this account -- the
    token names the person, and whether it also names the client is not
    something this app has verified, so it does not guess which -- and
    writes the client-less row when there is nothing to stamp."""
    with db.connect(dsn) as conn:
        cur = conn.execute(
            "UPDATE mcp_connections SET last_used_at = now() "
            "WHERE account_id = %s AND user_id = %s",
            (int(account_id), str(user_id)))
        if cur.rowcount:
            return
        conn.execute(
            "INSERT INTO mcp_connections (account_id, user_id, client_name, last_used_at) "
            "VALUES (%s, %s, '', now()) "
            "ON CONFLICT (account_id, user_id, client_name) DO UPDATE SET last_used_at = now()",
            (int(account_id), str(user_id)))


def status(account_id: int, user_id: str, dsn: Optional[str] = None) -> dict[str, Any]:
    """What the panel says: whether this person has connected Claude to
    this account, when they allowed it, when it was last used, and the
    name of the client they used most recently."""
    with db.connect(dsn) as conn:
        rows = conn.execute(
            "SELECT client_name, approved_at, last_used_at FROM mcp_connections "
            "WHERE account_id = %s AND user_id = %s "
            "ORDER BY COALESCE(last_used_at, approved_at) DESC NULLS LAST, id DESC",
            (int(account_id), str(user_id))).fetchall()
    approved = [r["approved_at"] for r in rows if r["approved_at"]]
    used = [r["last_used_at"] for r in rows if r["last_used_at"]]
    named = next((r["client_name"] for r in rows if r["client_name"]), None)
    return {
        "connected": bool(rows),
        "approved_at": max(approved) if approved else None,
        "last_used_at": max(used) if used else None,
        "client_name": named,
    }
