"""
Pre-production: places you could shoot, and concepts you haven't shot.

Everything else in this pipeline starts from footage that already
exists -- manifest.json is a record of what was filmed. This module
covers the phase before that: photograph the spaces available to you,
have them described, and generate concepts grounded in those real
spaces rather than in a script written blind.

An extension to db.py in its own module, same as generative.py: own
SCHEMA, own init(), run after db.init_db().

`shot_done` is the label worth having. You generate several concepts
and go shoot some of them; that choice is ground truth about what's
actually worth making, in exactly the way ideas.selected is for
pitches, and it costs one column to keep.

Postgres since 2026-09-03, step 3 of docs/tasks/task-postgres-migration.md.
The SQLite-era migration that used to be a third of this file -- the
locations rebuild from UNIQUE(name) to UNIQUE(account_id, name), the
concept_locations FK repair for tables rewritten to `locations_old`,
the dangling-REFERENCES scan, and eight ALTER-if-missing column adds --
is gone (Mike's call): no Postgres database will ever be in the
pre-tenancy shape, so SCHEMA below IS the final shape, every column
inline with the comment that explains it. What those migrations
protected is pinned in tests/test_tenancy.py as properties instead:
two accounts can each own a Garage, one account cannot own two,
ownerless rows still collide, the cascade still fires.
"""
from __future__ import annotations

import json
import re
from typing import Any, Optional

from .db import _hash, _now, connect, own_table

BRANDS = ("antihero", "zeropage")

SCHEMA = """
CREATE TABLE IF NOT EXISTS locations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TEXT    NOT NULL,
    -- Not UNIQUE on its own: two accounts can each own a place called
    -- "Garage". Uniqueness is the expression index below.
    name        TEXT    NOT NULL,
    photo_count INTEGER,
    description_json TEXT,
    notes       TEXT,
    -- Nullable: NULL is the unowned pool (see db.add_account_column,
    -- which also declares the FK to accounts(id)).
    account_id  BIGINT
);

CREATE TABLE IF NOT EXISTS shoot_concepts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TEXT    NOT NULL,
    brand       TEXT    NOT NULL,
    client      TEXT,
    spark       TEXT,
    title       TEXT    NOT NULL,
    hook        TEXT,
    logline     TEXT,
    -- The board's one-line label, separate from `logline` ON PURPOSE
    -- (2026-09-02). scene_brief_prompt.txt makes logline 2-4 sentences
    -- -- "where the IDEA survives", the want/obstacle/turn a one-action
    -- prompt cannot hold. That is the idea record; this is the card.
    -- Trimming the first to make the second threw the idea away.
    card_line   TEXT,
    duration    TEXT,
    shots_json  TEXT    NOT NULL,
    ai_json     TEXT,
    edit_note   TEXT,
    grade_note  TEXT,
    shot_done   INTEGER NOT NULL DEFAULT 0,
    prompt_hash TEXT,
    warnings_json TEXT,
    use_pov     INTEGER NOT NULL DEFAULT 1,
    notes       TEXT,
    -- taste + performance judge scores (BACKLOG #5): a manual,
    -- history-based ranking. Gates nothing.
    judge_overall DOUBLE PRECISION,
    judge_taste   DOUBLE PRECISION,
    judge_perf    DOUBLE PRECISION,
    judge_reason  TEXT,
    -- `format` is the skeleton the concept rides (Zero Page).
    format        TEXT,
    -- Zero Page's on-brand (uncanny) gate: a fixed-rubric pass/fail that
    -- decides whether a concept may auto-post. Separate from the taste
    -- judge above -- this one gates.
    uncanny_overall DOUBLE PRECISION,
    uncanny_passed  INTEGER,
    uncanny_reason  TEXT,
    -- the pick: which of the several scenes one idea produced is worth
    -- rendering (see set_picked / pick_rate). Timestamped so a rate can
    -- be windowed.
    picked_at   TEXT,
    -- the board clears itself: a concept you resolved (picked and sent
    -- to render, or passed over) stops being a card without stopping
    -- being a row. The row is the label -- pick_rate needs the ones you
    -- did NOT pick as much as the ones you did -- and it stays in the
    -- Dev Studio's ungraded pool until it is graded. Archiving is the
    -- board's memory, not the database's.
    archived_at TEXT,
    -- WHY a reason and not just a timestamp (2026-08-31). archived_at
    -- records THAT a concept was passed over; it cannot record what was
    -- wrong with it. Thirteen of the first fifteen concepts were
    -- rejected and the system learned nothing from any of them, because
    -- nothing ever asked. An unpicked row is the ONLY negative signal
    -- this pipeline collects at volume, and a rejection with no reason
    -- can never reach avoid_guidance.
    archive_reason TEXT,
    account_id  BIGINT
);

CREATE TABLE IF NOT EXISTS concept_locations (
    concept_id  BIGINT NOT NULL REFERENCES shoot_concepts(id) ON DELETE CASCADE,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    UNIQUE (concept_id, location_id)
);

CREATE TABLE IF NOT EXISTS scene_briefs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    brand      TEXT NOT NULL,
    spark      TEXT,
    title      TEXT NOT NULL,
    brief      TEXT NOT NULL,
    account_id BIGINT
);

CREATE INDEX IF NOT EXISTS idx_concepts_shot ON shoot_concepts (shot_done);
CREATE INDEX IF NOT EXISTS idx_cl_concept    ON concept_locations (concept_id);
-- the shape every board query uses: this account's, newest first
CREATE INDEX IF NOT EXISTS idx_concepts_account ON shoot_concepts (account_id, id DESC);
"""

# Uniqueness of a location's name is an expression index, not a table
# constraint, and the COALESCE is load-bearing: Postgres, like SQLite,
# treats NULLs as distinct inside a UNIQUE, so a plain
# UNIQUE(account_id, name) lets two ownerless rows named "hallway" both
# exist -- which is exactly what add_location's upsert relies on NOT
# happening. Folding NULL to 0 keeps an unowned row behaving the way it
# did before tenancy, so nothing changes for a caller that has not been
# given an account yet, while two real accounts can still each own a
# Garage. add_location's ON CONFLICT names the same expressions, which
# is how Postgres finds this index.
LOCATIONS_UNIQUE = (
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_locations_owner_name "
    "ON locations (COALESCE(account_id, 0), name)"
)


def init(dsn: Optional[str] = None) -> None:
    """Create the pre-production tables. Run after db.init_db()."""
    with connect(dsn) as conn:
        conn.execute(SCHEMA)
        conn.execute(LOCATIONS_UNIQUE)
        # tenancy: the FK to accounts(id) on each owned table, and the
        # claim of any ownerless rows once there is an account to claim
        # them for (db.own_table)
        own_table(conn, "locations")
        own_table(conn, "shoot_concepts")
        own_table(conn, "scene_briefs")


def save_judge_score(concept_id: int, judge: dict, dsn: Optional[str] = None, *,
                     account_id: int) -> None:
    """Store the taste + performance judge's verdict on a concept so the UI
    can show and rank by it. `judge` is taste_judge.score_concept()'s dict."""
    with connect(dsn) as conn:
        conn.execute(
            "UPDATE shoot_concepts SET judge_overall=%s, judge_taste=%s, "
            "judge_perf=%s, judge_reason=%s WHERE id=%s AND account_id IS NOT DISTINCT FROM %s",
            (judge.get("overall"), judge.get("taste_fit"), judge.get("performance"),
             " · ".join(judge.get("reasons") or [])[:500], concept_id, account_id),
        )


def save_uncanny_score(concept_id: int, score: dict, dsn: Optional[str] = None, *,
                       account_id: int) -> None:
    """Store Zero Page's on-brand gate verdict on a concept so the UI can show
    the PASS/HOLD and autopilot can check it. `score` is
    uncanny_judge.score_concept()'s dict."""
    with connect(dsn) as conn:
        conn.execute(
            "UPDATE shoot_concepts SET uncanny_overall=%s, uncanny_passed=%s, "
            "uncanny_reason=%s WHERE id=%s AND account_id IS NOT DISTINCT FROM %s",
            (score.get("overall"), 1 if score.get("passed") else 0,
             " · ".join(score.get("reasons") or [])[:500], concept_id, account_id),
        )


def delete_concept(concept_id: int, dsn: Optional[str] = None, *,
                   account_id: int) -> None:
    """Discard a concept for good -- if it is yours. concept_locations
    rows cascade via the FK.

    Deleting someone else's is silently a no-op rather than an error,
    for the same reason get_concept returns None: an error would confirm
    the row exists."""
    with connect(dsn) as conn:
        conn.execute(
            "DELETE FROM shoot_concepts WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (concept_id, account_id),
        )


def delete_all_concepts(brand: Optional[str] = None, dsn: Optional[str] = None, *,
                        account_id: int) -> int:
    """Clear ONE ACCOUNT's concept slate -- all of it, or just one of its
    brands. Returns how many were removed. concept_locations cascades.

    `account_id` is required here above all: this used to be
    `DELETE FROM shoot_concepts` with no argument at all, which wiped the
    whole table. With a second account on the database that is not a
    reset, it is someone else's work gone."""
    with connect(dsn) as conn:
        if brand:
            cur = conn.execute(
                "DELETE FROM shoot_concepts WHERE brand = %s AND account_id IS NOT DISTINCT FROM %s",
                (brand, account_id),
            )
        else:
            cur = conn.execute(
                "DELETE FROM shoot_concepts WHERE account_id IS NOT DISTINCT FROM %s", (account_id,)
            )
        return cur.rowcount


# --------------------------------------------------------------------------
# scene briefs -- one cohesive whole-scene prompt (the winning skeleton)
# --------------------------------------------------------------------------
def save_scene_brief(brand: str, title: str, brief: str,
                     spark: Optional[str] = None, dsn: Optional[str] = None, *,
                     account_id: int) -> int:
    with connect(dsn) as conn:
        row = conn.execute(
            "INSERT INTO scene_briefs (created_at, brand, spark, title, brief, "
            "account_id) VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
            (_now(), brand, (spark or "").strip() or None,
             (title or "Untitled scene").strip(), brief.strip(), account_id),
        ).fetchone()
        return int(row["id"])


def list_scene_briefs(brand: Optional[str] = None,
                      dsn: Optional[str] = None, *,
                      account_id: int) -> list[dict[str, Any]]:
    """This account's briefs. `brand` still narrows within them -- it is
    a label on the row now, not the thing that decides who may see it."""
    sql = "SELECT * FROM scene_briefs WHERE account_id IS NOT DISTINCT FROM %s"
    params: list[Any] = [account_id]
    if brand:
        sql += " AND brand = %s"
        params.append(brand)
    sql += " ORDER BY id DESC"
    with connect(dsn) as conn:
        return [dict(r) for r in conn.execute(sql, params)]


def delete_scene_brief(brief_id: int, dsn: Optional[str] = None, *,
                       account_id: int) -> None:
    with connect(dsn) as conn:
        conn.execute(
            "DELETE FROM scene_briefs WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (brief_id, account_id),
        )


# --------------------------------------------------------------------------
# locations
# --------------------------------------------------------------------------


def add_location(
    name: str,
    description: Optional[dict] = None,
    photo_count: Optional[int] = None,
    notes: Optional[str] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> int:
    """
    Record (or re-record) a place you can shoot. Keyed by name, so
    re-describing a location after adding photos updates it instead of
    creating a second row -- names are how you refer to a space out
    loud, and two rows for one hallway would be a bug, not a feature.
    """
    if not name or not name.strip():
        raise ValueError("a location needs a name")
    name = name.strip()

    with connect(dsn) as conn:
        # RETURNING id is right on both paths of the upsert -- the row
        # inserted, or the row DO UPDATE touched -- which lastrowid never
        # was. The conflict target has to spell out the expressions of
        # LOCATIONS_UNIQUE for Postgres to pick that index.
        row = conn.execute(
            """
            INSERT INTO locations (created_at, name, photo_count, description_json,
                                   notes, account_id)
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT ((COALESCE(account_id, 0)), name) DO UPDATE SET
                photo_count      = excluded.photo_count,
                description_json = excluded.description_json,
                notes            = COALESCE(excluded.notes, locations.notes)
            RETURNING id
            """,
            (_now(), name, photo_count,
             json.dumps(description) if description is not None else None, notes,
             account_id),
        ).fetchone()
        return int(row["id"])


def _location_row(row) -> dict[str, Any]:
    data = dict(row)
    raw = data.pop("description_json", None)
    data["description"] = json.loads(raw) if raw else None
    return data


def get_location(location_id: int, dsn: Optional[str] = None, *,
                 account_id: int) -> Optional[dict[str, Any]]:
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM locations WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (location_id, account_id),
        ).fetchone()
    return _location_row(row) if row else None


def get_location_by_name(name: str, dsn: Optional[str] = None, *,
                         account_id: int) -> Optional[dict[str, Any]]:
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM locations WHERE name = %s AND account_id IS NOT DISTINCT FROM %s",
            (name, account_id),
        ).fetchone()
    return _location_row(row) if row else None


def list_locations(dsn: Optional[str] = None, *,
                   account_id: int) -> list[dict[str, Any]]:
    with connect(dsn) as conn:
        return [
            _location_row(r)
            for r in conn.execute(
                "SELECT * FROM locations WHERE account_id IS NOT DISTINCT FROM %s ORDER BY name ASC",
                (account_id,),
            )
        ]


# --------------------------------------------------------------------------
# concepts
# --------------------------------------------------------------------------


def save_concept(
    concept: dict,
    brand: str,
    client: Optional[str] = None,
    spark: Optional[str] = None,
    location_ids: Optional[list] = None,
    prompt_template: Optional[str] = None,
    warnings: Optional[list] = None,
    use_pov: bool = False,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> int:
    """
    Store one generated concept, warnings and all. Returns its id.

    `account_id` is stamped from the caller's session, never taken from
    a request parameter -- a client that can name the owner of a row it
    is creating can create rows in someone else's account.

    Warnings are stored rather than just counted: a concept that broke a
    rule is worth looking at and deciding on, and a number in a flash
    message that disappears on the next page load is not "attached".

    prompt_template is hashed rather than stored, same as pitch_runs --
    enough to tell which prompt version produced which shoot rate,
    without keeping a copy of every prompt ever used.
    """
    title = (concept.get("title") or "").strip()
    if not title:
        raise ValueError("concept has no title")
    if brand not in BRANDS:
        raise ValueError(f"brand must be one of {BRANDS}, got {brand!r}")

    with connect(dsn) as conn:
        row = conn.execute(
            """
            INSERT INTO shoot_concepts
                (created_at, brand, client, spark, title, hook, logline, card_line,
                 duration, shots_json, ai_json, edit_note, grade_note, prompt_hash,
                 warnings_json, use_pov, format, account_id)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (_now(), brand, client, spark, title,
             concept.get("hook"), concept.get("logline"),
             concept.get("card_line"), concept.get("duration"),
             json.dumps(concept.get("shots") or []),
             json.dumps(concept["ai"]) if concept.get("ai") else None,
             concept.get("edit"), concept.get("grade"), _hash(prompt_template),
             json.dumps(warnings) if warnings else None, 1 if use_pov else 0,
             concept.get("format"), account_id),
        ).fetchone()
        concept_id = int(row["id"])

        for location_id in location_ids or []:
            # a concept may only be pinned to a location the same account
            # owns -- otherwise a guessed id links you to a stranger's room
            owned = conn.execute(
                "SELECT 1 FROM locations WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
                (location_id, account_id),
            ).fetchone()
            if not owned:
                continue
            conn.execute(
                "INSERT INTO concept_locations (concept_id, location_id) VALUES (%s, %s) "
                "ON CONFLICT (concept_id, location_id) DO NOTHING",
                (concept_id, location_id),
            )
        return concept_id


# --- the one line a card shows -----------------------------------------------
# The board's whole job is choosing between several concepts, and a
# scene prompt is ~1200 characters of camera, grade and beats -- reading
# four of those to find out what happens is what the summary line
# replaces (2026-08-31). The writer supplies it as `logline`; these two
# helpers are the safety net for a row that has none (every concept
# written before the prompt asked for one) and the hard cap that keeps
# it to ONE line whatever the model returned.

# Measured, not guessed (2026-08-31). .scenegrid is
# repeat(auto-fill,minmax(380px,1fr)) capped at 1680px, so the NARROWEST
# a card ever gets is a 4-column row on a wide screen: a 349px text box,
# which fits ~54 average characters at 14.5px. Budget under that and cut
# on a word boundary -- a line trimmed at a word reads as a short
# summary, where the CSS ellipsis mid-word reads as broken.
SUMMARY_WORDS = 8
SUMMARY_CHARS = 52

# Camera-craft openers the beats almost always start with. Stripping
# them is what turns "Open on an extreme macro of a pale membrane pinned
# over a hole" into "a pale membrane pinned over a hole" -- the summary
# is meant to say what happens, and framing is not what happens.
_OPENERS = re.compile(
    r"""^\s*(?:the\s+(?:scene|video|clip|film)\s+)?(?:
        (?:begin|begins|open|opens|start|starts|starting|opening)
        (?:\s+(?:on|with|in))?\s+
        (?:an?\s+|the\s+)?
        (?:(?:extreme\s+|low[- ]angle\s+|high[- ]angle\s+|wide\s+|close\s+|macro\s+|tight\s+|
             handheld\s+|static\s+|slow\s+)*
           (?:shot|macro|angle|close[- ]up|frame|framing|push[- ]in|pan|tilt)
           (?:\s+(?:of|on|at))?\s+)?
      | the\s+camera\s+\w+(?:s)?(?:\s+(?:on|to|in|at|from))?\s+
    )""",
    re.IGNORECASE | re.VERBOSE,
)


def derive_logline(prompt: str) -> str:
    """A summary read out of the prompt itself, for a concept the writer
    gave no logline. First sentence of the BEATS block with the camera
    direction taken off the front -- coarse on purpose: this is the
    fallback, and a concept written today carries a real logline."""
    text = (prompt or "").strip()
    if not text:
        return ""
    beats = re.split(r"\bbeats?\s*:", text, maxsplit=1, flags=re.IGNORECASE)
    # No BEATS header: skip the open line and the style block, which are
    # boilerplate in every prompt this pipeline writes.
    body = beats[1] if len(beats) > 1 else re.split(
        r"\bstyle\s*:[^.]*\.", text, maxsplit=1, flags=re.IGNORECASE)[-1]
    sentence = re.split(r"(?<=[.!?])\s+", body.strip(), maxsplit=1)[0]
    return _OPENERS.sub("", sentence).strip()


def concept_summary(card_line: str = "", logline: str = "", prompt: str = "",
                    words: int = SUMMARY_WORDS,
                    chars: int = SUMMARY_CHARS) -> str:
    """The line the card prints, capped so it stays ONE line at the
    narrowest a card gets. Three sources, best first: the purpose-written
    `card_line`; a `logline`, which on the nightly path is 2-4 sentences
    of idea record and so gets trimmed; and failing both, a clause read
    out of the prompt. Every cap falls on a word boundary."""
    line = " ".join((card_line or "").split())
    if not line:
        line = " ".join((logline or "").split())
    if not line:
        line = " ".join(derive_logline(prompt).split())
    if not line:
        return ""
    line = line.rstrip(" .,;:—-")
    parts = line.split(" ")
    cut = len(parts) > words
    if cut:
        parts = parts[:words]
    while len(" ".join(parts)) > chars and len(parts) > 1:
        parts.pop()
        cut = True
    line = " ".join(parts).rstrip(" .,;:—-") + ("…" if cut else "")
    return line[:1].upper() + line[1:]


def _concept_row(row, conn) -> dict[str, Any]:
    data = dict(row)
    data["shots"] = json.loads(data.pop("shots_json") or "[]")
    ai_raw = data.pop("ai_json", None)
    data["ai"] = json.loads(ai_raw) if ai_raw else None
    warn_raw = data.pop("warnings_json", None)
    data["warnings"] = json.loads(warn_raw) if warn_raw else []
    # Derived, not stored: an idea that hasn't been planned yet simply
    # has no shots. Storing a flag as well would let the two disagree.
    data["has_shot_list"] = bool(data["shots"])
    # Derived the same way: the AI shots are the shots whose source says
    # so. Rows written before the de-cap carried one concept-level ai
    # dict instead -- surface it here too, so old concepts keep
    # rendering wherever ai_shots is read.
    data["ai_shots"] = [s for s in data["shots"] if s.get("source") == "AI"]
    if not data["ai_shots"] and data["ai"]:
        data["ai_shots"] = [data["ai"]]
    data["use_pov"] = bool(data.get("use_pov", 1))
    # Derived for the same reason: a concept IS one scene when it holds
    # exactly one shot, and it is picked when it carries a pick time.
    # Two stored flags could disagree with the rows they describe.
    data["is_scene"] = len(data["shots"]) == 1
    data["picked"] = bool(data.get("picked_at"))
    data["archived"] = bool(data.get("archived_at"))
    data["archive_reason"] = data.get("archive_reason") or ""
    # graded is what finally retires an archived concept: the Dev
    # Studio's grade queue draws on judge_overall IS NULL, so a row
    # archived off the board is still waiting to teach something.
    data["graded"] = data.get("judge_overall") is not None
    # the reference photos this scene was written against, carried on
    # the shot itself -- shots_json was always one flexible JSON column,
    # so plural references cost no schema change
    data["refs"] = (data["shots"][0].get("refs") or []) if data["shots"] else []
    # parked: the chain got this scene as far as it can go without
    # spending, and it is sitting in the Queue. Stored on the shot
    # rather than derived from reference_image, which the Director
    # canvas also writes -- see set_shot_parked.
    first = data["shots"][0] if data["shots"] else {}
    data["parked"] = bool(first.get("parked_at"))
    data["park_reason"] = first.get("park_reason") or ""

    data["locations"] = [
        dict(r)
        for r in conn.execute(
            """
            SELECT l.id, l.name FROM locations l
            JOIN concept_locations cl ON cl.location_id = l.id
            WHERE cl.concept_id = %s AND l.account_id IS NOT DISTINCT FROM %s
            ORDER BY l.name
            """,
            (data["id"], data.get("account_id")),
        )
    ]
    return data


def get_concept(concept_id: int, dsn: Optional[str] = None, *,
                account_id: int) -> Optional[dict[str, Any]]:
    """One concept, if it is this account's.

    Returns None for a concept that belongs to someone else -- the same
    answer as for a concept that does not exist. The distinction would
    be an enumeration oracle: ids are sequential integers, so "not
    yours" and "not found" have to be indistinguishable or anyone can
    map the whole table by counting.

    `account_id` is keyword-only and has no default. An optional
    ownership argument is a leak waiting for the one call site that
    forgets it; this way a forgotten one is a TypeError at the call.
    """
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM shoot_concepts WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (concept_id, account_id),
        ).fetchone()
        return _concept_row(row, conn) if row else None


def list_concepts(limit: int = 100, dsn: Optional[str] = None, *,
                  account_id: int, brand: Optional[str] = None) -> list[dict[str, Any]]:
    """This account's concepts, newest first -- the ones you just
    generated are the ones you're deciding about.

    `brand` filters in SQL, and that is the point of it (2026-09-02).
    The board has always been per-brand, but it filtered the rows in
    Python AFTER this function had already cut the newest 100 across
    the whole account. Two brands sharing one account means the LIMIT
    is spent on whichever one was generated for most recently: at 100+
    concepts, the other brand's board starts silently losing its oldest
    cards, and it looks exactly like a board that is just showing you
    less than you made. Filtering here spends the limit on the brand
    being asked for.

    An unknown brand is ignored rather than returning nothing -- callers
    pass a cookie value, and a stale cookie should show the board, not
    empty it."""
    scoped = brand if brand in BRANDS else None
    with connect(dsn) as conn:
        rows = conn.execute(
            "SELECT * FROM shoot_concepts WHERE account_id IS NOT DISTINCT FROM %s "
            + ("AND brand = %s " if scoped else "")
            + "ORDER BY id DESC LIMIT %s",
            (account_id, scoped, limit) if scoped else (account_id, limit),
        ).fetchall()
        return [_concept_row(r, conn) for r in rows]


def save_concept_ideas(
    ideas: list,
    brand: str,
    client: Optional[str] = None,
    spark: Optional[str] = None,
    prompt_template: Optional[str] = None,
    use_pov: bool = False,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> list:
    """
    Stage one: save a batch of cheap ideas, no shot lists yet. Returns
    their ids in order. Which of these later gets a shot list is the
    pick worth measuring.
    """
    return [
        save_concept(idea, brand=brand, client=client, spark=spark,
                     prompt_template=prompt_template, use_pov=use_pov, dsn=dsn,
                     account_id=account_id)
        for idea in ideas
    ]


def update_concept_shots(
    concept_id: int,
    plan: dict,
    location_ids: Optional[list] = None,
    warnings: Optional[list] = None,
    dsn: Optional[str] = None,
    *,
    account_id: int,
) -> None:
    """
    Stage two: attach a shot list to an idea you chose. Leaves the
    idea's own fields (title, hook, logline) alone -- those were the
    thing you picked, and rewriting them here would quietly change
    what you agreed to.
    """
    with connect(dsn) as conn:
        exists = conn.execute(
            "SELECT 1 FROM shoot_concepts WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (concept_id, account_id),
        ).fetchone()
        if not exists:
            raise ValueError(f"no concept with id {concept_id}")

        conn.execute(
            """
            UPDATE shoot_concepts
               SET duration   = COALESCE(%s, duration),
                   shots_json = %s,
                   ai_json    = %s,
                   edit_note  = COALESCE(%s, edit_note),
                   grade_note = COALESCE(%s, grade_note),
                   warnings_json = %s
             WHERE id = %s AND account_id IS NOT DISTINCT FROM %s
            """,
            (plan.get("duration"),
             json.dumps(plan.get("shots") or []),
             json.dumps(plan["ai"]) if plan.get("ai") else None,
             plan.get("edit"), plan.get("grade"),
             # replaced, not merged: planning re-validates from scratch,
             # so an idea-stage warning must not linger as if still true
             json.dumps(warnings) if warnings else None,
             concept_id, account_id),
        )

        for location_id in location_ids or []:
            owned = conn.execute(
                "SELECT 1 FROM locations WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
                (location_id, account_id),
            ).fetchone()
            if not owned:
                continue
            conn.execute(
                "INSERT INTO concept_locations (concept_id, location_id) VALUES (%s, %s) "
                "ON CONFLICT (concept_id, location_id) DO NOTHING",
                (concept_id, location_id),
            )


def set_shot_media_url(concept_id: int, shot_n, media_url: str,
                        dsn: Optional[str] = None, *,
                        account_id: int) -> None:
    """
    Attach a rendered clip's public URL to one shot in a concept's shot
    list -- the one field autopilot.build_plan() checks before it will
    ever emit a post action (see autopilot.py). Rewrites just the
    matching shot's media_url in place; everything else in the shot
    list -- other shots, prompts, camera notes -- is left untouched.

    Raises if the concept or the shot (by its "n") doesn't exist,
    rather than silently no-op'ing -- storage.publish_shot_media()
    catches this and turns it into a result dict.
    """
    if not (media_url or "").strip():
        raise ValueError("media_url is required")

    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT shots_json FROM shoot_concepts WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (concept_id, account_id),
        ).fetchone()
        if not row:
            raise ValueError(f"no concept with id {concept_id}")

        shots = json.loads(row["shots_json"] or "[]")
        for shot in shots:
            if shot.get("n") == shot_n:
                shot["media_url"] = media_url.strip()
                break
        else:
            raise ValueError(f"concept {concept_id} has no shot n={shot_n!r}")

        conn.execute(
            "UPDATE shoot_concepts SET shots_json = %s WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (json.dumps(shots), concept_id, account_id),
        )


def set_shot_reference_image(concept_id: int, shot_n, reference_url,
                             dsn: Optional[str] = None, *,
                             account_id: int) -> None:
    """
    Attach a real capture -- the acting take or room plate Michael
    filmed -- to one shot as the reference image its AI generation
    anchors on. Shots live as dicts inside shots_json, so this rewrites
    just the matching shot's reference_image in place, exactly the
    set_shot_media_url() shape above.

    Unlike media_url, empty is legal here and CLEARS the reference: a
    reference is an enhancement to a shot, never a gate on it, so
    detaching one must be as easy as attaching it. Raises if the
    concept or the shot (by its "n") doesn't exist.
    """
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT shots_json FROM shoot_concepts WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (concept_id, account_id),
        ).fetchone()
        if not row:
            raise ValueError(f"no concept with id {concept_id}")

        shots = json.loads(row["shots_json"] or "[]")
        for shot in shots:
            if shot.get("n") == shot_n:
                cleaned = (reference_url or "").strip()
                if cleaned:
                    shot["reference_image"] = cleaned
                else:
                    # absent, not empty-string: a shot carries the key
                    # only while a reference is actually attached
                    shot.pop("reference_image", None)
                break
        else:
            raise ValueError(f"concept {concept_id} has no shot n={shot_n!r}")

        conn.execute(
            "UPDATE shoot_concepts SET shots_json = %s WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (json.dumps(shots), concept_id, account_id),
        )


def set_shot_parked(concept_id: int, shot_n, reason: str = "",
                    dsn: Optional[str] = None, *,
                    account_id: int) -> None:
    """
    Mark a shot as finished with the automatic half and waiting on a
    human to approve the spend -- what the Studio chain writes when it
    has a concept, an enhanced prompt and (usually) a keyframe, and the
    next step is the one that costs money.

    An explicit marker, not an inference. The obvious shortcut is to
    treat "has a reference_image" as "waiting in the Queue", but that
    field is also written by the Director canvas mid-work
    (POST /concepts/{id}/shots/{n}/reference), so inferring would drag
    every scene anyone has ever keyframed into the spend queue. Stored
    on the shot like refs / reference_image / media_url -- shots_json
    was always one flexible JSON column, so no migration.

    Empty reason is legal (parked, nothing to say). Passing parked=False
    is not a thing: leaving the queue is approving or archiving, both of
    which already have their own timestamps. Raises if the concept or
    the shot (by its "n") doesn't exist.
    """
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT shots_json FROM shoot_concepts WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (concept_id, account_id),
        ).fetchone()
        if not row:
            raise ValueError(f"no concept with id {concept_id}")

        shots = json.loads(row["shots_json"] or "[]")
        for shot in shots:
            if shot.get("n") == shot_n:
                shot["parked_at"] = _now()
                cleaned = (reason or "").strip()
                if cleaned:
                    shot["park_reason"] = cleaned
                else:
                    shot.pop("park_reason", None)
                break
        else:
            raise ValueError(f"concept {concept_id} has no shot n={shot_n!r}")

        conn.execute(
            "UPDATE shoot_concepts SET shots_json = %s WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (json.dumps(shots), concept_id, account_id),
        )


def set_picked(concept_id: int, picked: bool = True,
               dsn: Optional[str] = None, *,
               account_id: int) -> None:
    """The label, moved to fit the unit (2026-08-26).

    shortlist_rate asked "was this idea worth planning a shot list for",
    derived from `shots != []`. Now that a concept IS one scene with one
    shot, every concept has shots the moment it exists and that question
    has no answer left in it. The decision actually being made is "is
    this scene worth rendering", so THAT is what gets recorded -- picking
    one of the several a single idea produced.

    Timestamped rather than a flag: a rate you cannot window by date
    stops being useful the moment the prompt changes.
    """
    with connect(dsn) as conn:
        cur = conn.execute(
            "UPDATE shoot_concepts SET picked_at = %s WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (_now() if picked else None, concept_id, account_id),
        )
        if cur.rowcount == 0:
            raise ValueError(f"no concept {concept_id}")


# The vocabulary the Grade tab offers as buttons. Short and closed: a
# free-text box gets skipped, and words that can be COUNTED are worth
# more than a paragraph nobody writes.
#
# "weak concept" replaced "other" (2026-09-02). It was never an edge
# case -- it was Mike's commonest verdict, 10 of the first 13, meaning
# "I just didn't like the idea". Called "other" that reads as unsorted
# noise; called what it is, it is the single clearest signal the board
# produces about generation quality. A catch-all has to be NAMED
# honestly or it hides the thing it is measuring.
#
# "no turn" and "no stake" sit beside it deliberately: they are the two
# fields the digest prompt now demands of every spark (situation, turn,
# stake), so a rejection tagged with one points straight at the prompt
# field that failed. "weak concept" stays for when the honest answer is
# just no -- forcing a category when none fits collects noise, which is
# how "other" got to 10 in the first place.
ARCHIVE_REASONS = ("weak concept", "no turn", "no stake", "off-brand",
                   "unshootable", "seen it")


def set_archived(concept_id: int, archived: bool = True,
                 dsn: Optional[str] = None, *,
                 account_id: int, reason: str = "") -> None:
    """Take a concept off the board without taking it out of the data.

    The board is a decision surface: once you have picked one of the
    several an idea produced and sent it to render, the others have been
    decided about and standing there they are just noise. But an
    unpicked row is the only negative signal this system collects --
    pick_rate is generated-vs-picked, and deleting the ones you passed
    over would make the rate 100% forever and unfalsifiable.

    So archiving hides, it does not delete. The row keeps counting in
    pick_rate and keeps sitting in the Dev Studio's ungraded pool
    (judge_overall IS NULL), which is where it finally earns its keep by
    teaching the RAG shelves what a miss looks like.
    """
    with connect(dsn) as conn:
        cur = conn.execute(
            "UPDATE shoot_concepts SET archived_at = %s, archive_reason = %s "
            "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (_now() if archived else None,
             ((reason or "").strip() or None) if archived else None,
             concept_id, account_id),
        )
        if cur.rowcount == 0:
            raise ValueError(f"no concept {concept_id}")


def archive_batch(spark: str, keep_ids: list[int] | None = None,
                  brand: Optional[str] = None,
                  dsn: Optional[str] = None, *,
                  account_id: int) -> int:
    """Archive every unresolved concept written from one idea, except
    the ones named in keep_ids. Returns how many were archived.

    A batch is "the concepts one idea produced", and the idea is stored
    on each row as `spark` -- generate_scene_concepts writes all N with
    the same one. That is the grouping the human is actually deciding
    within: pick from these four, the other three are answered.
    """
    keep = set(keep_ids or [])
    with connect(dsn) as conn:
        rows = conn.execute(
            "SELECT id FROM shoot_concepts "
            "WHERE spark = %s AND archived_at IS NULL AND account_id IS NOT DISTINCT FROM %s"
            + (" AND brand = %s" if brand else ""),
            (spark, account_id, brand) if brand else (spark, account_id),
        ).fetchall()
        targets = [r["id"] for r in rows if r["id"] not in keep]
        for concept_id in targets:
            conn.execute(
                "UPDATE shoot_concepts SET archived_at = %s WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
                (_now(), concept_id, account_id),
            )
    return len(targets)


def posted_outcomes(dsn: Optional[str] = None, *,
                    account_id: int) -> list[dict[str, Any]]:
    """Concepts that reached an audience, with their latest numbers.

    The join that closes the loop (2026-08-31). `videos.concept_id` is
    the link; `metrics` snapshots the numbers over time, so the LATEST
    snapshot per video is the one worth reading -- metrics is a growth
    curve on purpose (see db.py), and averaging it would throw the curve
    away.

    Empty until something is posted with a concept behind it, which is
    the honest state: the ten rows already in `videos` are pre-pipeline
    uploads with no concept to point at.
    """
    with connect(dsn) as conn:
        rows = conn.execute(
            """
            SELECT c.id AS concept_id, c.title, c.brand, c.archive_reason,
                   v.id AS video_id, v.platform, v.posted_at, v.url,
                   m.views, m.likes, m.comments, m.saves, m.shares
            FROM shoot_concepts c
            JOIN videos v ON v.concept_id = c.id
            LEFT JOIN metrics m ON m.id = (
                SELECT id FROM metrics WHERE video_id = v.id
                ORDER BY captured_at DESC, id DESC LIMIT 1
            )
            WHERE c.account_id IS NOT DISTINCT FROM %s
            ORDER BY v.posted_at DESC
            """,
            (account_id,),
        ).fetchall()
    return [dict(r) for r in rows]


def reason_counts(dsn: Optional[str] = None, *,
                  account_id: int) -> list[dict[str, Any]]:
    """How many concepts were passed on for each reason, commonest first.

    The payoff that makes the Grade tab worth opening. Working a queue
    with no visible result is a chore; a tally that shifts as you go is
    a scoreboard. It is also the first idea-level signal this pipeline
    has ever had -- avoid_guidance holds craft notes about PROMPTS, and
    nothing anywhere held "you keep rejecting these for being boring".
    """
    with connect(dsn) as conn:
        rows = conn.execute(
            "SELECT archive_reason AS reason, COUNT(*) AS n "
            "FROM shoot_concepts "
            "WHERE archived_at IS NOT NULL AND archive_reason IS NOT NULL "
            "AND account_id IS NOT DISTINCT FROM %s "
            "GROUP BY archive_reason ORDER BY n DESC, reason",
            (account_id,),
        ).fetchall()
    return [{"reason": r["reason"], "n": r["n"]} for r in rows]


def pick_rate(dsn: Optional[str] = None, *, account_id: int) -> dict[str, Any]:
    """Of the scenes generated, how many were worth rendering.

    shortlist_rate's successor, same shape and same per-prompt-hash
    breakdown -- derived from the rows rather than stored, so it cannot
    drift from what it describes. Counts only ONE-SHOT concepts: a
    legacy multi-shot concept was never a single scene to pick, and
    mixing the two would compare different decisions.
    """
    with connect(dsn) as conn:
        rows = conn.execute(
            """
            SELECT prompt_hash,
                   COUNT(*) AS generated,
                   SUM(CASE WHEN picked_at IS NOT NULL THEN 1 ELSE 0 END) AS picked
            FROM shoot_concepts
            WHERE json_array_length(shots_json::json) = 1 AND account_id IS NOT DISTINCT FROM %s
            GROUP BY prompt_hash
            """,
            (account_id,),
        ).fetchall()

    by_prompt = [
        {
            "prompt_hash": r["prompt_hash"],
            "generated": r["generated"],
            "picked": r["picked"] or 0,
            "rate": round((r["picked"] or 0) / r["generated"], 3),
        }
        for r in rows
    ]
    generated = sum(b["generated"] for b in by_prompt)
    picked = sum(b["picked"] for b in by_prompt)
    return {
        "generated": generated,
        "picked": picked,
        "rate": round(picked / generated, 3) if generated else None,
        "by_prompt": by_prompt,
    }


def mark_shot(concept_id: int, shot: bool = True, dsn: Optional[str] = None, *,
              account_id: int) -> None:
    """Record that you actually went and shot this one -- the label."""
    with connect(dsn) as conn:
        cur = conn.execute(
            "UPDATE shoot_concepts SET shot_done = %s WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (1 if shot else 0, concept_id, account_id),
        )
        if cur.rowcount == 0:
            raise ValueError(f"no concept with id {concept_id}")


def shoot_rate(dsn: Optional[str] = None, *, account_id: int) -> dict[str, Any]:
    """
    How many generated concepts you actually shoot, overall and per
    prompt version. The pre-production equivalent of selection_rate.
    """
    with connect(dsn) as conn:
        rows = conn.execute(
            """
            SELECT prompt_hash,
                   COUNT(*)        AS generated,
                   SUM(shot_done)  AS shot
            FROM shoot_concepts
            WHERE account_id IS NOT DISTINCT FROM %s
            GROUP BY prompt_hash
            """,
            (account_id,),
        ).fetchall()

    by_prompt = [
        {
            "prompt_hash": r["prompt_hash"],
            "generated": r["generated"],
            "shot": r["shot"] or 0,
            "rate": round((r["shot"] or 0) / r["generated"], 3),
        }
        for r in rows
    ]
    generated = sum(b["generated"] for b in by_prompt)
    shot = sum(b["shot"] for b in by_prompt)
    return {
        "generated": generated,
        "shot": shot,
        "rate": round(shot / generated, 3) if generated else None,
        "by_prompt": by_prompt,
    }


def summary(dsn: Optional[str] = None, *, account_id: int) -> dict[str, int]:
    """Counts for one account. An unscoped COUNT here would have been a
    quiet cross-account leak -- small, but it is still telling you how
    much work everyone else has done."""
    with connect(dsn) as conn:
        return {
            t: conn.execute(
                f"SELECT COUNT(*) FROM {t} WHERE account_id IS NOT DISTINCT FROM %s", (account_id,)
            ).fetchone()[0]
            for t in ("locations", "shoot_concepts")
        }
