"""Studio projects: one brief and one memory per piece of work (2026-09-28).

Mike's call, the day ANTIHERO was folded into Zero Page: the studio has no
house channel any more, so the direction a scene is written against comes
from the PROJECT it belongs to -- a client's ad, a filmmaker's short, a
product launch. "It's only by project basis so it's able to keep
consistency with renders across the project."

A project carries four things, and only the first three are typed:

- `brief`  -- who it is for, the look, the must-haves and the nevers.
  Written by hand, or drafted by the model from three answers
  (`draft_brief`) and then edited.
- `look`   -- the style every prompt in the project is held to (2026-10-02,
  Mike's call: the look belongs to the project, the studio has none).
  Read only through `looks.look_block`, never here; "" -- the default --
  means the project imposes no look at all, NOT "use the brand's".
- `memory` -- what the project has LEARNED: every pick, every pass with its
  reason, every hand edit of a prompt made inside it. Appended by the routes
  that already record those decisions, newest last, capped at MEMORY_MAX.
  It is per-project on purpose: a lesson from a perfume ad must not steer a
  horror short. (The shared brain -- winning_prompts, the RAG shelves --
  still learns from everything, as decided 2026-09-01; this is the addressed
  half, not a replacement for it.)
- the concepts written inside it, by `shoot_concepts.project_id`.

At generation time `brief_block` turns the project into text that
`shootgen.load_brand` appends under the studio's neutral block, through
`project_context.active(...)`.

Owned like every other table a person looks at (db.OWNED_TABLES): every
query carries the account predicate.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Optional

from .db import connect, own_table

MEMORY_MAX = 60          # entries kept per project; the oldest fall off
PROMPT_MEMORY = 14       # how many of the newest reach a prompt
EXCERPT = 320            # characters of a scene prompt kept per pick
LOOK_MAX = 4000          # characters of a project's look

# The three questions the brief is drafted from. The keys are the form
# fields; the wording is what the Projects page shows.
QUESTIONS = (
    ("for", "Who is it for, and what is it? (brand, product, film, audience)"),
    ("look", "What should it look and feel like? (references, mood, palette)"),
    ("rules", "What must it always have — and never show?"),
)

KINDS = ("pick", "pass", "edit", "note")

SCHEMA = """
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT,
    title TEXT NOT NULL,
    brief TEXT NOT NULL DEFAULT '',
    memory_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    archived_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS projects_owner ON projects(account_id, updated_at DESC);
"""

# THE CHAT HISTORY (2026-10-07, Mike's call: "a project keeps its chat
# history until the project is deleted"). One row per turn of the Guide
# inside a project, written as it happens by the /creative-guide route,
# and read back when the project's workspace opens so the pill carries
# on where it left off. OWNED like `projects`: a conversation is user
# content, read and written under the account predicate, never shared
# across projects or accounts, and never fed to the shared RAG shelves.
# `tool_calls_json` holds what the reply carried beside its words -- the
# read tools it looked at, a proposal, chips, directions -- so a reopened
# conversation draws the same cards. Deleting the project deletes these
# (in the same transaction, `delete`); archiving keeps them.
MESSAGES_SCHEMA = """
CREATE TABLE IF NOT EXISTS project_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    account_id BIGINT,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    tool_calls_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS project_messages_order
    ON project_messages(project_id, created_at, id);
"""

MESSAGE_ROLES = ("user", "assistant")
MESSAGE_MAX = 20000          # characters of one turn (creative_guide.Message)
MESSAGES_PAGE = 40           # turns loaded when a workspace opens
TOOL_CALLS_MAX = 60_000      # bytes of extras kept beside one turn


def init(dsn: Optional[str] = None) -> None:
    """The tables, and `project_id` on shoot_concepts. Run after
    preprod.init (it ALTERs shoot_concepts). Idempotent."""
    with connect(dsn) as conn:
        conn.execute(SCHEMA)
        own_table(conn, "projects")
        # the look (2026-10-02) -- additive, and "" for every row that
        # existed before it, which is exactly "no look imposed"
        conn.execute("ALTER TABLE projects ADD COLUMN IF NOT EXISTS look "
                     "TEXT NOT NULL DEFAULT ''")
        conn.execute("ALTER TABLE shoot_concepts ADD COLUMN IF NOT EXISTS project_id BIGINT")
        conn.execute("CREATE INDEX IF NOT EXISTS shoot_concepts_project "
                     "ON shoot_concepts(project_id)")
        conn.execute(MESSAGES_SCHEMA)
        own_table(conn, "project_messages")


def _row(row) -> dict[str, Any]:
    data = dict(row)
    try:
        data["memory"] = json.loads(data.pop("memory_json") or "[]")
    except (TypeError, ValueError):
        data["memory"] = []
    data["archived"] = bool(data.get("archived_at"))
    for key in ("created_at", "updated_at", "archived_at"):
        if isinstance(data.get(key), datetime):
            data[key] = data[key].isoformat()
    return data


def create(title: str, brief: str = "", dsn: Optional[str] = None, *,
           account_id: int, look: str = "") -> dict[str, Any]:
    title = (title or "").strip()[:120]
    if not title:
        raise ValueError("a project needs a name")
    with connect(dsn) as conn:
        row = conn.execute(
            "INSERT INTO projects (account_id, title, brief, look) VALUES (%s, %s, %s, %s) "
            "RETURNING *", (account_id, title, (brief or "").strip()[:8000],
                            (look or "").strip()[:LOOK_MAX])).fetchone()
        return _row(row)


def get(project_id: int, dsn: Optional[str] = None, *,
        account_id: int) -> Optional[dict[str, Any]]:
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM projects WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (project_id, account_id)).fetchone()
        return _row(row) if row else None


def list_projects(dsn: Optional[str] = None, *, account_id: int,
                  include_archived: bool = False) -> list[dict[str, Any]]:
    """Newest-touched first, each with its concept counts -- written,
    picked, rendered -- so the Projects page can say where each one is."""
    with connect(dsn) as conn:
        rows = conn.execute(
            "SELECT p.*, "
            "  COUNT(c.id) AS concepts, "
            "  COUNT(c.picked_at) AS picked, "
            "  COUNT(c.id) FILTER (WHERE c.shots_json LIKE '%%\"media_url\": \"http%%') AS rendered "
            "FROM projects p "
            "LEFT JOIN shoot_concepts c ON c.project_id = p.id "
            "  AND c.account_id IS NOT DISTINCT FROM p.account_id "
            "WHERE p.account_id IS NOT DISTINCT FROM %s "
            + ("" if include_archived else "AND p.archived_at IS NULL ")
            + "GROUP BY p.id ORDER BY p.updated_at DESC LIMIT 200",
            (account_id,)).fetchall()
        items = [_row(r) for r in rows]
        found = _covers(conn, [p["id"] for p in items], account_id)
    for p in items:
        p["cover"] = found.get(p["id"])
    return items


def _shot_cover(shot: dict) -> Optional[str]:
    """What a scene card would draw first: its still, else the first
    reference. A clip is not an <img>; its still IS its first frame."""
    if not isinstance(shot, dict):
        return None
    still = shot.get("reference_image")
    if still:
        return str(still)
    timeline = shot.get("timeline") if isinstance(shot.get("timeline"), dict) else {}
    for part in timeline.get("parts") or []:
        if isinstance(part, dict) and part.get("reference_image"):
            return str(part["reference_image"])
    refs = shot.get("refs") or []
    return str(refs[0]) if refs else None


def _covers(conn, project_ids: list, account_id: int) -> dict[int, Optional[str]]:
    """One cover per project: the newest scene's still, else its first
    reference, else None. ONE query for the whole board (the lean-listing
    rule, 2026-09-25): the newest concept per project, its shots only."""
    ids = [int(i) for i in project_ids if i]
    if not ids:
        return {}
    rows = conn.execute(
        "SELECT DISTINCT ON (project_id) project_id, shots_json FROM shoot_concepts "
        "WHERE project_id = ANY(%s) AND account_id IS NOT DISTINCT FROM %s "
        "ORDER BY project_id, created_at DESC, id DESC",
        (ids, account_id)).fetchall()
    out: dict[int, Optional[str]] = {}
    for r in rows:
        try:
            shots = json.loads(r["shots_json"] or "[]")
        except (TypeError, ValueError):
            shots = []
        out[int(r["project_id"])] = _shot_cover(shots[0]) if shots else None
    return out


def for_concepts(concept_ids, dsn: Optional[str] = None, *,
                 account_id: int) -> dict[int, dict[str, Any]]:
    """{concept_id: {id, title}} for the concepts that sit inside a
    project -- one query, for a board or a media wall to say where each
    row belongs. A concept outside any project is simply absent."""
    ids = sorted({int(i) for i in (concept_ids or []) if i})
    if not ids:
        return {}
    with connect(dsn) as conn:
        rows = conn.execute(
            "SELECT c.id AS concept_id, p.id, p.title FROM shoot_concepts c "
            "JOIN projects p ON p.id = c.project_id "
            "WHERE c.id = ANY(%s) AND c.account_id IS NOT DISTINCT FROM %s "
            "AND p.account_id IS NOT DISTINCT FROM %s",
            (ids, account_id, account_id)).fetchall()
    return {int(r["concept_id"]): {"id": int(r["id"]), "title": r["title"]} for r in rows}


def update(project_id: int, dsn: Optional[str] = None, *, account_id: int,
           title: Optional[str] = None, brief: Optional[str] = None,
           look: Optional[str] = None) -> dict[str, Any]:
    sets, args = [], []
    if title is not None:
        if not title.strip():
            raise ValueError("a project needs a name")
        sets.append("title = %s")
        args.append(title.strip()[:120])
    if brief is not None:
        sets.append("brief = %s")
        args.append(brief.strip()[:8000])
    if look is not None:                  # "" clears it: no look imposed
        sets.append("look = %s")
        args.append(look.strip()[:LOOK_MAX])
    if not sets:
        found = get(project_id, dsn, account_id=account_id)
        if not found:
            raise ValueError(f"no project {project_id}")
        return found
    with connect(dsn) as conn:
        row = conn.execute(
            f"UPDATE projects SET {', '.join(sets)}, updated_at = now() "
            "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s RETURNING *",
            (*args, project_id, account_id)).fetchone()
        if not row:
            raise ValueError(f"no project {project_id}")
        return _row(row)


def set_archived(project_id: int, archived: bool, dsn: Optional[str] = None, *,
                 account_id: int) -> None:
    """Archiving hides a project from the page; it never deletes it, or
    its concepts, or what it learned."""
    with connect(dsn) as conn:
        cur = conn.execute(
            "UPDATE projects SET archived_at = CASE WHEN %s THEN now() ELSE NULL END, "
            "updated_at = now() WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (bool(archived), project_id, account_id))
        if cur.rowcount == 0:
            raise ValueError(f"no project {project_id}")


def scenes_to_detach(project_id: int, dsn: Optional[str] = None, *,
                     account_id: int) -> list[dict[str, Any]]:
    """What deleting this project would leave behind: its scenes, each
    with whether it carries a rendered clip. The confirm dialog lists the
    UNRENDERED ones, since a detached scene with no clip has no board to
    appear on any more (2026-10-07)."""
    with connect(dsn) as conn:
        rows = conn.execute(
            "SELECT id, title, shots_json FROM shoot_concepts "
            "WHERE project_id = %s AND account_id IS NOT DISTINCT FROM %s "
            "ORDER BY created_at DESC, id DESC",
            (project_id, account_id)).fetchall()
    out = []
    for r in rows:
        try:
            shots = json.loads(r["shots_json"] or "[]")
        except (TypeError, ValueError):
            shots = []
        first = shots[0] if shots and isinstance(shots[0], dict) else {}
        out.append({"id": int(r["id"]), "title": r["title"] or "",
                    "rendered": bool(first.get("media_url"))})
    return out


def delete(project_id: int, dsn: Optional[str] = None, *,
           account_id: int) -> dict[str, int]:
    """Delete a project FOR GOOD (2026-10-07, Mike's call). The one
    exception to "archiving never deletes", and it is scoped exactly:

    - the project row goes, with its brief, its look and its memory;
    - its chat history goes with it (`project_messages`, same transaction);
    - its scenes are DETACHED, never deleted (`project_id` set NULL), so a
      rendered clip, its generated_assets row and the Assets wall are
      untouched -- a paid output is never thrown away. A scene with no clip
      is left detached too, which is why the confirm dialog lists them.

    Returns the counts, per table. Someone else's project is "no project".
    """
    with connect(dsn) as conn:
        owned = conn.execute(
            "SELECT 1 FROM projects WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (project_id, account_id)).fetchone()
        if not owned:
            raise ValueError(f"no project {project_id}")
        detached = conn.execute(
            "UPDATE shoot_concepts SET project_id = NULL "
            "WHERE project_id = %s AND account_id IS NOT DISTINCT FROM %s",
            (project_id, account_id)).rowcount
        messages = conn.execute(
            "DELETE FROM project_messages WHERE project_id = %s "
            "AND account_id IS NOT DISTINCT FROM %s",
            (project_id, account_id)).rowcount
        conn.execute(
            "DELETE FROM projects WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (project_id, account_id))
    return {"detached": int(detached), "messages": int(messages)}


# -- the chat history ---------------------------------------------------------

def _message(row) -> dict[str, Any]:
    out = {"id": int(row["id"]), "role": row["role"], "content": row["content"],
           "created_at": row["created_at"].isoformat()
           if isinstance(row["created_at"], datetime) else row["created_at"]}
    try:
        out["tool_calls"] = json.loads(row["tool_calls_json"] or "null")
    except (TypeError, ValueError):
        out["tool_calls"] = None
    return out


def append_message(project_id: int, role: str, content: str, dsn: Optional[str] = None, *,
                   account_id: int, tool_calls: Optional[dict] = None) -> Optional[dict]:
    """One turn into the project's history. Never raises past a bad
    argument: history is bookkeeping on top of a turn that already
    happened, and a project that is not this account's takes nothing."""
    if role not in MESSAGE_ROLES:
        raise ValueError(f"role must be one of {MESSAGE_ROLES}")
    content = str(content or "")[:MESSAGE_MAX]
    if not content.strip():
        return None
    blob = None
    if tool_calls:
        blob = json.dumps(tool_calls, default=str)
        if len(blob) > TOOL_CALLS_MAX:
            blob = None
    with connect(dsn) as conn:
        owned = conn.execute(
            "SELECT 1 FROM projects WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (project_id, account_id)).fetchone()
        if not owned:
            return None
        row = conn.execute(
            "INSERT INTO project_messages (project_id, account_id, role, content, tool_calls_json) "
            "VALUES (%s, %s, %s, %s, %s) RETURNING *",
            (project_id, account_id, role, content, blob)).fetchone()
        conn.execute("UPDATE projects SET updated_at = now() WHERE id = %s "
                     "AND account_id IS NOT DISTINCT FROM %s", (project_id, account_id))
    return _message(row)


def messages(project_id: int, dsn: Optional[str] = None, *, account_id: int,
             limit: int = MESSAGES_PAGE, before: Optional[int] = None) -> dict[str, Any]:
    """The newest `limit` turns, oldest first, and whether older ones
    exist. `before` (a message id) pages back: the turns older than it.
    The account predicate is on the query itself, not only on the
    project lookup -- a message id is sequential."""
    limit = max(1, min(int(limit or MESSAGES_PAGE), 200))
    with connect(dsn) as conn:
        if before is not None:
            rows = conn.execute(
                "SELECT * FROM project_messages WHERE project_id = %s "
                "AND account_id IS NOT DISTINCT FROM %s AND id < %s "
                "ORDER BY id DESC LIMIT %s",
                (project_id, account_id, int(before), limit + 1)).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM project_messages WHERE project_id = %s "
                "AND account_id IS NOT DISTINCT FROM %s "
                "ORDER BY id DESC LIMIT %s",
                (project_id, account_id, limit + 1)).fetchall()
    more = len(rows) > limit
    rows = list(reversed(rows[:limit]))
    return {"items": [_message(r) for r in rows], "has_more": more}


def copy_messages(project_id: int, turns, dsn: Optional[str] = None, *,
                  account_id: int) -> int:
    """`save_as_project`: the conversation that was had BEFORE the project
    existed, filed into it in order. Turns are {role, content, tool_calls?};
    anything else is skipped. Returns how many were written."""
    n = 0
    for t in list(turns or [])[-200:]:
        if not isinstance(t, dict) or t.get("role") not in MESSAGE_ROLES:
            continue
        tool_calls = t.get("tool_calls") if isinstance(t.get("tool_calls"), dict) else None
        if append_message(project_id, t["role"], t.get("content") or "", dsn,
                          account_id=account_id, tool_calls=tool_calls):
            n += 1
    return n


# -- memory -------------------------------------------------------------------

def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def remember(project_id: int, kind: str, text: str, dsn: Optional[str] = None, *,
             account_id: int, concept_id: Optional[int] = None) -> Optional[dict]:
    """Append one lesson. A later entry of the same kind for the same
    concept REPLACES the earlier one (re-picking, re-editing), and a pick
    and a pass on one concept cancel each other -- the memory holds what
    was decided last, not every click. Never raises: memory is
    bookkeeping on top of a decision that already happened."""
    if kind not in KINDS or not (text or "").strip():
        return None
    try:
        with connect(dsn) as conn:
            row = conn.execute(
                "SELECT memory_json FROM projects WHERE id = %s "
                "AND account_id IS NOT DISTINCT FROM %s FOR UPDATE",
                (project_id, account_id)).fetchone()
            if not row:
                return None
            try:
                memory = json.loads(row["memory_json"] or "[]")
            except (TypeError, ValueError):
                memory = []
            if concept_id is not None:
                rivals = {kind} | ({"pick", "pass"} if kind in ("pick", "pass") else set())
                memory = [m for m in memory
                          if not (m.get("concept_id") == concept_id and m.get("kind") in rivals)]
            entry = {"kind": kind, "text": " ".join(text.split())[:600],
                     "concept_id": concept_id, "at": _now()}
            memory.append(entry)
            memory = memory[-MEMORY_MAX:]
            conn.execute(
                "UPDATE projects SET memory_json = %s, updated_at = now() "
                "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
                (json.dumps(memory), project_id, account_id))
            return entry
    except Exception:
        return None


def forget(project_id: int, at: str, dsn: Optional[str] = None, *,
           account_id: int) -> bool:
    """Drop one memory entry, identified by its timestamp. A lesson the
    person disagrees with must be removable, or it steers forever."""
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT memory_json FROM projects WHERE id = %s "
            "AND account_id IS NOT DISTINCT FROM %s FOR UPDATE",
            (project_id, account_id)).fetchone()
        if not row:
            raise ValueError(f"no project {project_id}")
        memory = json.loads(row["memory_json"] or "[]")
        kept = [m for m in memory if m.get("at") != at]
        conn.execute(
            "UPDATE projects SET memory_json = %s, updated_at = now() "
            "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (json.dumps(kept), project_id, account_id))
        return len(kept) != len(memory)


# -- concepts -----------------------------------------------------------------

def tag_concepts(concept_ids: list, project_id: Optional[int], dsn: Optional[str] = None, *,
                 account_id: int) -> int:
    """File concepts under a project (None takes them out of one)."""
    ids = [int(i) for i in concept_ids or [] if i]
    if not ids:
        return 0
    with connect(dsn) as conn:
        if project_id is not None:
            owned = conn.execute(
                "SELECT 1 FROM projects WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
                (project_id, account_id)).fetchone()
            if not owned:
                raise ValueError(f"no project {project_id}")
        cur = conn.execute(
            "UPDATE shoot_concepts SET project_id = %s "
            "WHERE id = ANY(%s) AND account_id IS NOT DISTINCT FROM %s",
            (project_id, ids, account_id))
        conn.execute(
            "UPDATE projects SET updated_at = now() WHERE id = %s "
            "AND account_id IS NOT DISTINCT FROM %s", (project_id, account_id))
        return cur.rowcount


def project_for_concept(concept_id: int, dsn: Optional[str] = None, *,
                        account_id: int) -> Optional[dict[str, Any]]:
    """The project a concept belongs to, or None. Never raises -- the
    callers are hooks on routes whose own work already succeeded."""
    try:
        with connect(dsn) as conn:
            row = conn.execute(
                "SELECT p.* FROM projects p JOIN shoot_concepts c ON c.project_id = p.id "
                "WHERE c.id = %s AND c.account_id IS NOT DISTINCT FROM %s "
                "AND p.account_id IS NOT DISTINCT FROM %s",
                (concept_id, account_id, account_id)).fetchone()
            return _row(row) if row else None
    except Exception:
        return None


def _scene_text(concept: dict) -> str:
    shots = concept.get("shots") or []
    prompt = (shots[0].get("prompt") if shots else "") or ""
    return " ".join(prompt.split())[:EXCERPT]


def remember_decision(concept: dict, kind: str, dsn: Optional[str] = None, *,
                      account_id: int, reason: str = "",
                      edited_prompt: str = "") -> None:
    """The hook the pick / pass / edit routes call with the concept they
    just decided on. A concept outside any project teaches nothing here."""
    try:
        project = project_for_concept(concept["id"], dsn, account_id=account_id)
        if not project:
            return
        title = concept.get("title") or f"#{concept['id']}"
        if kind == "pick":
            text = f"PICKED “{title}” — {_scene_text(concept)}"
        elif kind == "pass":
            text = f"PASSED ON “{title}”" + (f" ({reason})" if reason else "") \
                + f" — {_scene_text(concept)[:160]}"
        elif kind == "edit":
            text = f"HAND-EDITED the prompt of “{title}” to: " \
                + " ".join((edited_prompt or "").split())[:EXCERPT]
        else:
            return
        remember(project["id"], kind, text, dsn, account_id=account_id,
                 concept_id=concept["id"])
    except Exception:
        return


def withdraw_decision(concept: dict, kind: str, dsn: Optional[str] = None, *,
                      account_id: int) -> None:
    """Un-pick / un-archive: the lesson that click wrote goes with it."""
    try:
        project = project_for_concept(concept["id"], dsn, account_id=account_id)
        if not project:
            return
        for m in project.get("memory") or []:
            if m.get("concept_id") == concept["id"] and m.get("kind") == kind:
                forget(project["id"], m.get("at"), dsn, account_id=account_id)
    except Exception:
        return


# -- into the prompt ----------------------------------------------------------

def brief_block(project: dict) -> str:
    """The project as the writer reads it, under the studio's block."""
    lines = [f"THIS RUN BELONGS TO THE PROJECT “{project.get('title') or 'untitled'}”."]
    brief = (project.get("brief") or "").strip()
    lines.append("PROJECT BRIEF:\n" + (brief or "(no brief written yet — follow the run)"))
    memory = [m for m in (project.get("memory") or []) if m.get("kind") in KINDS]
    if memory:
        lines.append(
            "WHAT THIS PROJECT HAS LEARNED (newest last). Keep new scenes consistent "
            "with what was PICKED and HAND-EDITED — same people, wardrobe, world, grade "
            "and tone — and steer away from what was PASSED ON and why:")
        for m in memory[-PROMPT_MEMORY:]:
            lines.append(f"- {m.get('text')}")
    return "\n".join(lines)


def draft_brief(title: str, answers: dict, gemini_client, *,
                account_id: Optional[int] = None) -> str:
    """A project brief drafted from the three answers. Raises on a model
    failure -- here the draft IS the deliverable, and the page shows the
    error rather than an empty box pretending to be a brief."""
    from . import gemini_utils

    given = "\n".join(f"- {label} {(answers.get(key) or '').strip() or '(not answered)'}"
                      for key, label in QUESTIONS)
    prompt = (
        "You write the standing BRIEF for one project in an AI video production "
        "studio. Every scene written for this project will be generated against it, "
        "so it must be concrete and usable, not marketing copy.\n\n"
        f"PROJECT: {title}\n\nWHAT THE FILMMAKER SAID:\n{given}\n\n"
        "Write the brief as plain text, under 170 words, with these labelled lines "
        "in order:\nFOR: who and what it is for, and the goal.\n"
        "LOOK: palette, light, lens, texture and pace, in cinematography terms.\n"
        "PEOPLE & PRODUCT: who or what appears and how they are held consistent.\n"
        "ALWAYS: what every scene must carry.\nNEVER: what no scene may show.\n"
        "Only use what the filmmaker said or what follows directly from it; where "
        "they said nothing, write one sensible default and keep it short. No preamble, "
        "no markdown.")
    text = gemini_utils.generate_with_retry(
        gemini_client, gemini_utils.FAST_MODEL, prompt,
        stage="creative_guide", account_id=account_id)
    text = gemini_utils.strip_fences(text or "").strip()
    if not text:
        raise RuntimeError("the model returned an empty brief")
    return text[:8000]
