"""Studio projects: one brief and one memory per piece of work (2026-09-28).

Mike's call, the day ANTIHERO was folded into Zero Page: the studio has no
house channel any more, so the direction a scene is written against comes
from the PROJECT it belongs to -- a client's ad, a filmmaker's short, a
product launch. "It's only by project basis so it's able to keep
consistency with renders across the project."

A project carries three things, and only the first two are typed:

- `brief`  -- who it is for, the look, the must-haves and the nevers.
  Written by hand, or drafted by the model from three answers
  (`draft_brief`) and then edited.
- `memory` -- what the project has LEARNED: every pick, every pass with its
  reason, every hand edit of a prompt made inside it. Appended by the routes
  that already record those decisions, newest last, capped at MEMORY_MAX.
  It is per-project on purpose: a lesson from a perfume ad must not steer a
  horror short. (The shared brain -- winning_prompts, the RAG shelves --
  still learns from everything, as decided 2026-09-01; this is the addressed
  half, not a replacement for it.)
- the concepts written inside it, by `shoot_concepts.project_id`.

At generation time `brief_block` turns the project into text that
`shootgen.load_brand` appends under the studio's neutral block, through
`project_context.active(...)`.

Owned like every other table a person looks at (db.OWNED_TABLES): every
query carries the account predicate.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Optional

from .db import connect, own_table

MEMORY_MAX = 60          # entries kept per project; the oldest fall off
PROMPT_MEMORY = 14       # how many of the newest reach a prompt
EXCERPT = 320            # characters of a scene prompt kept per pick

# The three questions the brief is drafted from. The keys are the form
# fields; the wording is what the Projects page shows.
QUESTIONS = (
    ("for", "Who is it for, and what is it? (brand, product, film, audience)"),
    ("look", "What should it look and feel like? (references, mood, palette)"),
    ("rules", "What must it always have — and never show?"),
)

KINDS = ("pick", "pass", "edit", "note")

SCHEMA = """
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT,
    title TEXT NOT NULL,
    brief TEXT NOT NULL DEFAULT '',
    memory_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    archived_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS projects_owner ON projects(account_id, updated_at DESC);
"""


def init(dsn: Optional[str] = None) -> None:
    """The table, and `project_id` on shoot_concepts. Run after
    preprod.init (it ALTERs shoot_concepts). Idempotent."""
    with connect(dsn) as conn:
        conn.execute(SCHEMA)
        own_table(conn, "projects")
        conn.execute("ALTER TABLE shoot_concepts ADD COLUMN IF NOT EXISTS project_id BIGINT")
        conn.execute("CREATE INDEX IF NOT EXISTS shoot_concepts_project "
                     "ON shoot_concepts(project_id)")


def _row(row) -> dict[str, Any]:
    data = dict(row)
    try:
        data["memory"] = json.loads(data.pop("memory_json") or "[]")
    except (TypeError, ValueError):
        data["memory"] = []
    data["archived"] = bool(data.get("archived_at"))
    for key in ("created_at", "updated_at", "archived_at"):
        if isinstance(data.get(key), datetime):
            data[key] = data[key].isoformat()
    return data


def create(title: str, brief: str = "", dsn: Optional[str] = None, *,
           account_id: int) -> dict[str, Any]:
    title = (title or "").strip()[:120]
    if not title:
        raise ValueError("a project needs a name")
    with connect(dsn) as conn:
        row = conn.execute(
            "INSERT INTO projects (account_id, title, brief) VALUES (%s, %s, %s) "
            "RETURNING *", (account_id, title, (brief or "").strip()[:8000])).fetchone()
        return _row(row)


def get(project_id: int, dsn: Optional[str] = None, *,
        account_id: int) -> Optional[dict[str, Any]]:
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM projects WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (project_id, account_id)).fetchone()
        return _row(row) if row else None


def list_projects(dsn: Optional[str] = None, *, account_id: int,
                  include_archived: bool = False) -> list[dict[str, Any]]:
    """Newest-touched first, each with its concept counts -- written,
    picked, rendered -- so the Projects page can say where each one is."""
    with connect(dsn) as conn:
        rows = conn.execute(
            "SELECT p.*, "
            "  COUNT(c.id) AS concepts, "
            "  COUNT(c.picked_at) AS picked, "
            "  COUNT(c.id) FILTER (WHERE c.shots_json LIKE '%%\"media_url\": \"http%%') AS rendered "
            "FROM projects p "
            "LEFT JOIN shoot_concepts c ON c.project_id = p.id "
            "  AND c.account_id IS NOT DISTINCT FROM p.account_id "
            "WHERE p.account_id IS NOT DISTINCT FROM %s "
            + ("" if include_archived else "AND p.archived_at IS NULL ")
            + "GROUP BY p.id ORDER BY p.updated_at DESC LIMIT 200",
            (account_id,)).fetchall()
        return [_row(r) for r in rows]


def update(project_id: int, dsn: Optional[str] = None, *, account_id: int,
           title: Optional[str] = None, brief: Optional[str] = None) -> dict[str, Any]:
    sets, args = [], []
    if title is not None:
        if not title.strip():
            raise ValueError("a project needs a name")
        sets.append("title = %s")
        args.append(title.strip()[:120])
    if brief is not None:
        sets.append("brief = %s")
        args.append(brief.strip()[:8000])
    if not sets:
        found = get(project_id, dsn, account_id=account_id)
        if not found:
            raise ValueError(f"no project {project_id}")
        return found
    with connect(dsn) as conn:
        row = conn.execute(
            f"UPDATE projects SET {', '.join(sets)}, updated_at = now() "
            "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s RETURNING *",
            (*args, project_id, account_id)).fetchone()
        if not row:
            raise ValueError(f"no project {project_id}")
        return _row(row)


def set_archived(project_id: int, archived: bool, dsn: Optional[str] = None, *,
                 account_id: int) -> None:
    """Archiving hides a project from the page; it never deletes it, or
    its concepts, or what it learned."""
    with connect(dsn) as conn:
        cur = conn.execute(
            "UPDATE projects SET archived_at = CASE WHEN %s THEN now() ELSE NULL END, "
            "updated_at = now() WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (bool(archived), project_id, account_id))
        if cur.rowcount == 0:
            raise ValueError(f"no project {project_id}")


# -- memory -------------------------------------------------------------------

def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def remember(project_id: int, kind: str, text: str, dsn: Optional[str] = None, *,
             account_id: int, concept_id: Optional[int] = None) -> Optional[dict]:
    """Append one lesson. A later entry of the same kind for the same
    concept REPLACES the earlier one (re-picking, re-editing), and a pick
    and a pass on one concept cancel each other -- the memory holds what
    was decided last, not every click. Never raises: memory is
    bookkeeping on top of a decision that already happened."""
    if kind not in KINDS or not (text or "").strip():
        return None
    try:
        with connect(dsn) as conn:
            row = conn.execute(
                "SELECT memory_json FROM projects WHERE id = %s "
                "AND account_id IS NOT DISTINCT FROM %s FOR UPDATE",
                (project_id, account_id)).fetchone()
            if not row:
                return None
            try:
                memory = json.loads(row["memory_json"] or "[]")
            except (TypeError, ValueError):
                memory = []
            if concept_id is not None:
                rivals = {kind} | ({"pick", "pass"} if kind in ("pick", "pass") else set())
                memory = [m for m in memory
                          if not (m.get("concept_id") == concept_id and m.get("kind") in rivals)]
            entry = {"kind": kind, "text": " ".join(text.split())[:600],
                     "concept_id": concept_id, "at": _now()}
            memory.append(entry)
            memory = memory[-MEMORY_MAX:]
            conn.execute(
                "UPDATE projects SET memory_json = %s, updated_at = now() "
                "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
                (json.dumps(memory), project_id, account_id))
            return entry
    except Exception:
        return None


def forget(project_id: int, at: str, dsn: Optional[str] = None, *,
           account_id: int) -> bool:
    """Drop one memory entry, identified by its timestamp. A lesson the
    person disagrees with must be removable, or it steers forever."""
    with connect(dsn) as conn:
        row = conn.execute(
            "SELECT memory_json FROM projects WHERE id = %s "
            "AND account_id IS NOT DISTINCT FROM %s FOR UPDATE",
            (project_id, account_id)).fetchone()
        if not row:
            raise ValueError(f"no project {project_id}")
        memory = json.loads(row["memory_json"] or "[]")
        kept = [m for m in memory if m.get("at") != at]
        conn.execute(
            "UPDATE projects SET memory_json = %s, updated_at = now() "
            "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
            (json.dumps(kept), project_id, account_id))
        return len(kept) != len(memory)


# -- concepts -----------------------------------------------------------------

def tag_concepts(concept_ids: list, project_id: Optional[int], dsn: Optional[str] = None, *,
                 account_id: int) -> int:
    """File concepts under a project (None takes them out of one)."""
    ids = [int(i) for i in concept_ids or [] if i]
    if not ids:
        return 0
    with connect(dsn) as conn:
        if project_id is not None:
            owned = conn.execute(
                "SELECT 1 FROM projects WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
                (project_id, account_id)).fetchone()
            if not owned:
                raise ValueError(f"no project {project_id}")
        cur = conn.execute(
            "UPDATE shoot_concepts SET project_id = %s "
            "WHERE id = ANY(%s) AND account_id IS NOT DISTINCT FROM %s",
            (project_id, ids, account_id))
        conn.execute(
            "UPDATE projects SET updated_at = now() WHERE id = %s "
            "AND account_id IS NOT DISTINCT FROM %s", (project_id, account_id))
        return cur.rowcount


def project_for_concept(concept_id: int, dsn: Optional[str] = None, *,
                        account_id: int) -> Optional[dict[str, Any]]:
    """The project a concept belongs to, or None. Never raises -- the
    callers are hooks on routes whose own work already succeeded."""
    try:
        with connect(dsn) as conn:
            row = conn.execute(
                "SELECT p.* FROM projects p JOIN shoot_concepts c ON c.project_id = p.id "
                "WHERE c.id = %s AND c.account_id IS NOT DISTINCT FROM %s "
                "AND p.account_id IS NOT DISTINCT FROM %s",
                (concept_id, account_id, account_id)).fetchone()
            return _row(row) if row else None
    except Exception:
        return None


def _scene_text(concept: dict) -> str:
    shots = concept.get("shots") or []
    prompt = (shots[0].get("prompt") if shots else "") or ""
    return " ".join(prompt.split())[:EXCERPT]


def remember_decision(concept: dict, kind: str, dsn: Optional[str] = None, *,
                      account_id: int, reason: str = "",
                      edited_prompt: str = "") -> None:
    """The hook the pick / pass / edit routes call with the concept they
    just decided on. A concept outside any project teaches nothing here."""
    try:
        project = project_for_concept(concept["id"], dsn, account_id=account_id)
        if not project:
            return
        title = concept.get("title") or f"#{concept['id']}"
        if kind == "pick":
            text = f"PICKED “{title}” — {_scene_text(concept)}"
        elif kind == "pass":
            text = f"PASSED ON “{title}”" + (f" ({reason})" if reason else "") \
                + f" — {_scene_text(concept)[:160]}"
        elif kind == "edit":
            text = f"HAND-EDITED the prompt of “{title}” to: " \
                + " ".join((edited_prompt or "").split())[:EXCERPT]
        else:
            return
        remember(project["id"], kind, text, dsn, account_id=account_id,
                 concept_id=concept["id"])
    except Exception:
        return


def withdraw_decision(concept: dict, kind: str, dsn: Optional[str] = None, *,
                      account_id: int) -> None:
    """Un-pick / un-archive: the lesson that click wrote goes with it."""
    try:
        project = project_for_concept(concept["id"], dsn, account_id=account_id)
        if not project:
            return
        for m in project.get("memory") or []:
            if m.get("concept_id") == concept["id"] and m.get("kind") == kind:
                forget(project["id"], m.get("at"), dsn, account_id=account_id)
    except Exception:
        return


# -- into the prompt ----------------------------------------------------------

def brief_block(project: dict) -> str:
    """The project as the writer reads it, under the studio's block."""
    lines = [f"THIS RUN BELONGS TO THE PROJECT “{project.get('title') or 'untitled'}”."]
    brief = (project.get("brief") or "").strip()
    lines.append("PROJECT BRIEF:\n" + (brief or "(no brief written yet — follow the run)"))
    memory = [m for m in (project.get("memory") or []) if m.get("kind") in KINDS]
    if memory:
        lines.append(
            "WHAT THIS PROJECT HAS LEARNED (newest last). Keep new scenes consistent "
            "with what was PICKED and HAND-EDITED — same people, wardrobe, world, grade "
            "and tone — and steer away from what was PASSED ON and why:")
        for m in memory[-PROMPT_MEMORY:]:
            lines.append(f"- {m.get('text')}")
    return "\n".join(lines)


def draft_brief(title: str, answers: dict, gemini_client, *,
                account_id: Optional[int] = None) -> str:
    """A project brief drafted from the three answers. Raises on a model
    failure -- here the draft IS the deliverable, and the page shows the
    error rather than an empty box pretending to be a brief."""
    from . import gemini_utils

    given = "\n".join(f"- {label} {(answers.get(key) or '').strip() or '(not answered)'}"
                      for key, label in QUESTIONS)
    prompt = (
        "You write the standing BRIEF for one project in an AI video production "
        "studio. Every scene written for this project will be generated against it, "
        "so it must be concrete and usable, not marketing copy.\n\n"
        f"PROJECT: {title}\n\nWHAT THE FILMMAKER SAID:\n{given}\n\n"
        "Write the brief as plain text, under 170 words, with these labelled lines "
        "in order:\nFOR: who and what it is for, and the goal.\n"
        "LOOK: palette, light, lens, texture and pace, in cinematography terms.\n"
        "PEOPLE & PRODUCT: who or what appears and how they are held consistent.\n"
        "ALWAYS: what every scene must carry.\nNEVER: what no scene may show.\n"
        "Only use what the filmmaker said or what follows directly from it; where "
        "they said nothing, write one sensible default and keep it short. No preamble, "
        "no markdown.")
    text = gemini_utils.generate_with_retry(
        gemini_client, gemini_utils.FAST_MODEL, prompt,
        stage="creative_guide", account_id=account_id)
    text = gemini_utils.strip_fences(text or "").strip()
    if not text:
        raise RuntimeError("the model returned an empty brief")
    return text[:8000]
