"""
The LLM meter: one row per Gemini call, priced, attributed, owner-scoped.

WHY THIS EXISTS (docs/tasks/task-cost-tracker.md, 2026-09-04). `generations.
cost_usd` has priced every render since the table was written, but no LLM
call had ever read `usage_metadata` -- concepts, both judges, the prompt
gate, CRAG, captions, the scout: all free, as far as the system knew. The
two numbers BACKLOG #10 could not pick (the global ceilings, the BYOK
split) are bets on a spend profile nobody had measured. This measures it.

WHERE THE METER LIVES. `gemini_utils.generate_with_retry` calls
`record_call` after every answer, because that function falls through
FALLBACK_MODELS and is the only place that knows WHICH model replied --
a caller pricing its own call would price gemini-3-flash-preview for an
answer that came from gemini-pro-latest. The five sites that bypass it
(nano_banana's image call, the scout's two, the orchestrator's evaluate
judge, framebank's captions) and the research agent (a different SDK
entirely) call `record_call` themselves. That is why the pricing and the
write live HERE and not inside gemini_utils: a second SDK wrapper reports
a call without importing the retry helper.

THREE RULES.
- The meter never raises. A metering bug must never cost a render or a
  night: `record_call` swallows everything and returns None
  (SPEND_DEBUG=1 prints what it swallowed).
- Token counts are stored raw beside the derived `cost_usd`, so a wrong
  price table is a re-computation (`reprice`), not a lost measurement.
- `cost_usd` is an ESTIMATE from a price table (`DEFAULT_PRICES`,
  env-overridable), never an invoice. Cached and thinking tokens price
  differently from input; image models price per image. The page says
  "estimate" too. No counts at all = UNPRICED (NULL), never $0.

WHAT IS NOT METERED, on purpose: the embedding path (`gemini-embedding-001`
in src/rag.py) runs on a different API surface and is left out; the page
says so. Renders are metered by the tools themselves in `generations`.

`llm_calls` is OWNED (db.OWNED_TABLES): every read carries an account
predicate, the way every other owned table does. The one deliberate
exception is `spent_today_everyone` -- the installation-wide number the
ceilings are measured against -- allowed by name in the tenancy test.
Postgres, like every table since 2026-09-03: `%s`, `IS NOT DISTINCT FROM`,
`RETURNING id`, `dsn` where a `path` used to be.
"""
from __future__ import annotations

import contextvars
import json
import os
from datetime import datetime, timezone
from typing import Any, Optional

from . import db

# One list, validated on write -- a free-text stage turns into fifteen
# spellings of "judge" within a month. `unknown` is the default so every
# existing caller keeps working; the labelling pass names them.
STAGES = (
    "concepts",        # scene / concept generation (shootgen, rework's slate)
    "logline",         # the board's card line
    "shot_prompt",     # promptgen: structure a Shot, refine a tool prompt
    "prompt_gate",     # the orchestrator's credit-gate judge
    "taste_judge",
    "uncanny_judge",
    "evaluate",        # the orchestrator's evaluate-and-retry critique
    "crag",            # the one query rewrite
    "scout",           # research crawl + digest
    "research",        # the research agent (langchain), per model turn
    "caption",         # scheduling.build_caption
    "director",        # director.direct_scene
    "enhance",         # imagery.enhance, the Generate tab, the canvas node
    "location",        # vision descriptions of spaces / cast / props
    "schedule",
    "rework",
    "nano_image",      # the image model
    "answer",          # grounded_answer
    "frame_caption",   # framebank captions
    "unknown",
)

# account_id is added by db.own_table (the column and the FOREIGN KEY to
# accounts(id) as its own constraint, the pattern every owned table uses
# since accounts.SCHEMA lives in the module that imports db).
SCHEMA = """
CREATE TABLE IF NOT EXISTS llm_calls (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TEXT    NOT NULL,
    run_id         TEXT,              -- the orchestrator's uuid4().hex; NULL on the request path
    stage          TEXT    NOT NULL,
    model_asked    TEXT    NOT NULL,
    model_used     TEXT    NOT NULL,  -- differs when the fallback chain fired
    prompt_tokens  INTEGER,
    output_tokens  INTEGER,
    cached_tokens  INTEGER,
    thought_tokens INTEGER,
    images         INTEGER NOT NULL DEFAULT 0,
    cost_usd       DOUBLE PRECISION,
    ok             INTEGER NOT NULL DEFAULT 1,
    ms             INTEGER
);
CREATE INDEX IF NOT EXISTS idx_llm_calls_run ON llm_calls (run_id);
"""

# USD per 1M tokens unless noted; `image` is USD per generated image.
# LITERAL DEFAULTS, READ OFF ai.google.dev/gemini-api/docs/pricing ON
# 2026-09-04 (paid tier, standard context, text input): 3 Flash Preview
# 0.50 / 3.00 / 0.05 cached; 3.1 Flash-Lite 0.25 / 1.50 / 0.025; 2.5 Flash
# 0.30 / 2.50 / 0.03; 2.5 Flash-Lite 0.10 / 0.40 / 0.01; 2.5 Flash Image
# $0.039 per image; 3 Pro Image $0.134 per 1K/2K image ($0.24 at 4K). The
# page says output pricing INCLUDES thinking tokens, so thoughts bill at
# the output rate. `gemini-pro-latest` was NOT on that page: its row is an
# estimate (the 3 Pro tier) and is the reason a fallback answer from it
# reads "estimate" twice over. They drift: override with
# SPEND_PRICES_JSON='{"model": {"input":.., "output":.., "cached":..,
# "image":..}}' rather than editing a call site. A model missing from the
# table prices at None -> cost_usd NULL, which the page counts as UNPRICED,
# never as $0.
DEFAULT_PRICES: dict[str, dict[str, float]] = {
    "gemini-3-flash-preview":   {"input": 0.50, "output": 3.00, "cached": 0.05},
    "gemini-3.1-flash-lite":    {"input": 0.25, "output": 1.50, "cached": 0.025},
    "gemini-pro-latest":        {"input": 2.00, "output": 12.00, "cached": 0.20},   # estimate
    "gemini-2.5-flash":         {"input": 0.30, "output": 2.50, "cached": 0.03},
    "gemini-2.5-flash-lite":    {"input": 0.10, "output": 0.40, "cached": 0.01},
    "gemini-2.5-flash-image":   {"input": 0.30, "output": 2.50, "cached": 0.03, "image": 0.039},
    "gemini-3-pro-image-preview": {"input": 2.00, "output": 12.00, "cached": 0.20, "image": 0.134},
}


def prices() -> dict[str, dict[str, float]]:
    """The price table: literal defaults, SPEND_PRICES_JSON merged over them."""
    table = {k: dict(v) for k, v in DEFAULT_PRICES.items()}
    raw = os.environ.get("SPEND_PRICES_JSON")
    if raw:
        try:
            for model, row in (json.loads(raw) or {}).items():
                table.setdefault(model, {}).update(
                    {k: float(v) for k, v in dict(row).items()})
        except (ValueError, TypeError, AttributeError):
            pass                        # a bad override is the default table, not a crash
    return table


def estimate_cost(model: str, *, prompt_tokens=0, output_tokens=0,
                  cached_tokens=0, thought_tokens=0, images=0) -> Optional[float]:
    """USD for one call, or None when the model is not in the table.
    Cached tokens are a slice of the prompt already counted in
    prompt_tokens (Google reports them that way), so they are priced at
    the cached rate and taken OUT of the input count. An image model's
    OUTPUT tokens ARE the image (a 1024px image reports ~1290 of them,
    measured 2026-09-04): with `images` set they are priced per image and
    not again per token, or one keyframe would bill twice."""
    row = prices().get(model)
    if not row:
        return None
    prompt = max(0, int(prompt_tokens or 0))
    cached = max(0, min(int(cached_tokens or 0), prompt))
    output = max(0, int(output_tokens or 0)) + max(0, int(thought_tokens or 0))
    images = max(0, int(images or 0))
    if images and "image" in row:
        output = max(0, int(thought_tokens or 0))     # the image is priced below
    per_m = 1_000_000
    cost = ((prompt - cached) * row.get("input", 0.0)
            + cached * row.get("cached", row.get("input", 0.0))
            + output * row.get("output", 0.0)) / per_m
    cost += images * row.get("image", 0.0)
    return round(cost, 6)


# --- who is spending: bound once per job / per graph run ------------------

_context: contextvars.ContextVar = contextvars.ContextVar("spend_context", default=None)


def bind(account_id: Optional[int] = None, run_id: Optional[str] = None):
    """Attribute every metered call in this context from here on.
    jobs.start binds the job's account in its worker thread; the
    orchestrator binds the run's uuid in the PARENT context around
    GRAPH.invoke (LangGraph runs each node in a copied context, so a
    bind inside a node reaches nothing after it). Returns a token for
    unbind(); a bind with only one field keeps the other from before."""
    current = dict(_context.get() or {})
    if account_id is not None:
        current["account_id"] = account_id
    if run_id is not None:
        current["run_id"] = run_id
    return _context.set(current)


def unbind(token) -> None:
    try:
        _context.reset(token)
    except Exception:
        pass


def bound() -> dict:
    return dict(_context.get() or {})


# --- the write ------------------------------------------------------------

_ready: set[str] = set()


def init(dsn: Optional[str] = None) -> None:
    """Create the table and, ONCE, claim pre-existing unowned rows for the
    bootstrap account (db.own_table -- the same backfill every owned table
    runs at startup). Once per dsn per process, deliberately: running it
    from every record_call re-claimed each earlier unowned row for the
    bootstrap account at the next write, which turned a CLI run's rows
    into Mike's one call later (found by a test on 2026-09-04)."""
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA)
        db.own_table(conn, "llm_calls")
    _ready.add(db.resolve_dsn(dsn))


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def usage_from_response(response) -> dict:
    """The four counts off a google-genai response, tolerating their
    absence: usage_metadata is missing on some responses and every field
    can be None."""
    meta = getattr(response, "usage_metadata", None)
    if meta is None and isinstance(response, dict):
        meta = response.get("usage_metadata")

    def pick(*names):
        for name in names:
            value = (meta.get(name) if isinstance(meta, dict)
                     else getattr(meta, name, None))
            if value is not None:
                try:
                    return int(value)
                except (TypeError, ValueError):
                    continue
        return None

    return {
        "prompt_tokens": pick("prompt_token_count", "prompt_tokens", "input_tokens"),
        "output_tokens": pick("candidates_token_count", "output_tokens", "completion_tokens"),
        "cached_tokens": pick("cached_content_token_count", "cached_tokens"),
        "thought_tokens": pick("thoughts_token_count", "thought_tokens", "reasoning_tokens"),
    }


def usage_from_langchain(message) -> dict:
    """The same four counts off a langchain AIMessage.usage_metadata."""
    meta = getattr(message, "usage_metadata", None) or {}
    details_in = meta.get("input_token_details") or {}
    details_out = meta.get("output_token_details") or {}
    return {
        "prompt_tokens": meta.get("input_tokens"),
        "output_tokens": meta.get("output_tokens"),
        "cached_tokens": details_in.get("cache_read"),
        "thought_tokens": details_out.get("reasoning"),
    }


_COUNTS = ("prompt_tokens", "output_tokens", "cached_tokens", "thought_tokens")


def record_call(*, stage: str, model_asked: str, model_used: Optional[str] = None,
                response=None, usage: Optional[dict] = None, images: int = 0,
                ok: bool = True, ms: Optional[int] = None,
                account_id: Optional[int] = None, run_id: Optional[str] = None,
                dsn: Optional[str] = None) -> Optional[int]:
    """One llm_calls row. NEVER RAISES -- returns the row id, or None when
    anything at all went wrong, because the accounting must not cost the
    generation it is accounting for. `stage` outside STAGES is stored as
    "unknown" rather than refused, for the same reason."""
    try:
        stage = stage if stage in STAGES else "unknown"
        model_used = model_used or model_asked
        counts = dict(usage) if usage else usage_from_response(response)
        context = bound()
        if account_id is None:
            account_id = context.get("account_id")
        if run_id is None:
            run_id = context.get("run_id")
        # no counts at all and no image: the call happened but its size is
        # unknown -- that is UNPRICED (NULL), never $0.00
        measured = any(counts.get(k) is not None for k in _COUNTS)
        cost = estimate_cost(
            model_used,
            prompt_tokens=counts.get("prompt_tokens") or 0,
            output_tokens=counts.get("output_tokens") or 0,
            cached_tokens=counts.get("cached_tokens") or 0,
            thought_tokens=counts.get("thought_tokens") or 0,
            images=images,
        ) if ok and (measured or images) else None
        if db.resolve_dsn(dsn) not in _ready:
            init(dsn)
        with db.connect(dsn) as conn:
            row = conn.execute(
                "INSERT INTO llm_calls (created_at, account_id, run_id, stage, "
                "model_asked, model_used, prompt_tokens, output_tokens, "
                "cached_tokens, thought_tokens, images, cost_usd, ok, ms) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
                "RETURNING id",
                (_now(), account_id, run_id, stage, str(model_asked), str(model_used),
                 counts.get("prompt_tokens"), counts.get("output_tokens"),
                 counts.get("cached_tokens"), counts.get("thought_tokens"),
                 int(images or 0), cost, 1 if ok else 0,
                 int(ms) if ms is not None else None),
            ).fetchone()
            return int(row["id"])
    except Exception:
        # never raises -- but never silent either when someone is looking:
        # SPEND_DEBUG=1 prints the accounting failure to stderr
        if os.environ.get("SPEND_DEBUG"):
            import traceback
            traceback.print_exc()
        return None


def reprice(dsn: Optional[str] = None, *, account_id: Optional[int]) -> int:
    """Recompute cost_usd for this account's successful rows from their raw
    counts and the CURRENT price table -- the reason the counts are stored
    beside the estimate. Returns rows changed. Rows with no counts stay
    NULL (unpriced); a model no longer in the table becomes NULL too,
    which the page reports rather than hides."""
    changed = 0
    with db.connect(dsn) as conn:
        rows = conn.execute(
            "SELECT id, model_used, prompt_tokens, output_tokens, cached_tokens, "
            "thought_tokens, images, cost_usd FROM llm_calls "
            "WHERE ok = 1 AND account_id IS NOT DISTINCT FROM %s", (account_id,)).fetchall()
        for r in rows:
            measured = any(r[k] is not None for k in _COUNTS)
            cost = estimate_cost(
                r["model_used"], prompt_tokens=r["prompt_tokens"] or 0,
                output_tokens=r["output_tokens"] or 0, cached_tokens=r["cached_tokens"] or 0,
                thought_tokens=r["thought_tokens"] or 0, images=r["images"] or 0,
            ) if (measured or r["images"]) else None
            if cost != r["cost_usd"]:
                conn.execute(
                    "UPDATE llm_calls SET cost_usd = %s "
                    "WHERE id = %s AND account_id IS NOT DISTINCT FROM %s",
                    (cost, r["id"], account_id))
                changed += 1
    return changed


# --- the reads: every one owner-scoped --------------------------------------

def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


_AGG = ("COUNT(*) AS calls, "
        "COUNT(*) FILTER (WHERE ok = 0) AS failed, "
        "COALESCE(SUM(prompt_tokens), 0) AS prompt_tokens, "
        "COALESCE(SUM(output_tokens), 0) AS output_tokens, "
        "COALESCE(SUM(thought_tokens), 0) AS thought_tokens, "
        "COALESCE(SUM(cost_usd), 0) AS cost_usd, "
        "COUNT(*) FILTER (WHERE ok = 1 AND cost_usd IS NULL) AS unpriced, "
        "COALESCE(SUM(ms), 0) AS ms")


def by_stage(dsn: Optional[str] = None, *, account_id: Optional[int],
             run_id: Optional[str] = None, since: Optional[str] = None) -> list[dict[str, Any]]:
    """Per stage: calls, tokens, estimated spend, and how many calls
    carried no price (a model missing from the table) -- those are
    reported, never folded into $0."""
    sql = f"SELECT stage, {_AGG} FROM llm_calls WHERE account_id IS NOT DISTINCT FROM %s"
    params: list = [account_id]
    if run_id:
        sql += " AND run_id = %s"
        params.append(run_id)
    if since:
        sql += " AND created_at >= %s"
        params.append(since)
    # the full expression, not the alias: ordering by a bare `cost_usd`
    # in an aggregate resolves to the input column on SQLite (2026-09-04)
    # and is ambiguous on Postgres -- spell it out
    sql += " GROUP BY stage ORDER BY COALESCE(SUM(cost_usd), 0) DESC, COUNT(*) DESC"
    with db.connect(dsn) as conn:
        return [dict(r) for r in conn.execute(sql, params)]


def by_run(dsn: Optional[str] = None, *, account_id: Optional[int],
           limit: int = 14) -> list[dict[str, Any]]:
    """Per graph run (the orchestrator's uuid), newest first: what a
    night cost, and which stage led it. Request-path calls (run_id NULL)
    are grouped as one row labelled by the day."""
    key = "COALESCE(run_id, 'day:' || substr(created_at, 1, 10))"
    with db.connect(dsn) as conn:
        rows = conn.execute(
            f"SELECT {key} AS run_key, MIN(run_id) AS run_id, "
            "MIN(created_at) AS started, COUNT(*) AS calls, "
            "COALESCE(SUM(cost_usd), 0) AS cost_usd, "
            "COUNT(*) FILTER (WHERE ok = 1 AND cost_usd IS NULL) AS unpriced, "
            "COALESCE(SUM(prompt_tokens), 0) + COALESCE(SUM(output_tokens), 0) "
            "  + COALESCE(SUM(thought_tokens), 0) AS tokens "
            "FROM llm_calls WHERE account_id IS NOT DISTINCT FROM %s "
            f"GROUP BY {key} ORDER BY MIN(created_at) DESC LIMIT %s",
            (account_id, limit),
        ).fetchall()
        out = []
        for r in rows:
            row = dict(r)
            top = conn.execute(
                "SELECT stage, COALESCE(SUM(cost_usd), 0) AS c FROM llm_calls "
                f"WHERE account_id IS NOT DISTINCT FROM %s AND {key} = %s "
                "GROUP BY stage ORDER BY COALESCE(SUM(cost_usd), 0) DESC, COUNT(*) DESC LIMIT 1",
                (account_id, row["run_key"]),
            ).fetchone()
            row["top_stage"] = top["stage"] if top else None
            row["top_stage_cost"] = round(top["c"], 4) if top else 0.0
            row["cost_usd"] = round(row["cost_usd"], 4)
            out.append(row)
        return out


def spent_today(dsn: Optional[str] = None, *, account_id: Optional[int]) -> dict:
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT COUNT(*), COALESCE(SUM(cost_usd), 0), "
            "COUNT(*) FILTER (WHERE ok = 1 AND cost_usd IS NULL) "
            "FROM llm_calls WHERE created_at >= %s AND account_id IS NOT DISTINCT FROM %s",
            (_today(), account_id),
        ).fetchone()
    return {"calls": row[0], "cost_usd": round(row[1], 4), "unpriced": row[2] or 0}


def spent_today_everyone(dsn: Optional[str] = None) -> dict:
    """Installation-wide, on purpose: the number the ceilings are a
    ceiling ON. The only unscoped read in this module; allowed by name
    in tests/test_tenancy.py."""
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT COUNT(*), COALESCE(SUM(cost_usd), 0) FROM llm_calls WHERE created_at >= %s",
            (_today(),),
        ).fetchone()
    return {"calls": row[0], "cost_usd": round(row[1], 4)}


def recent(dsn: Optional[str] = None, *, account_id: Optional[int],
           limit: int = 25) -> list[dict[str, Any]]:
    with db.connect(dsn) as conn:
        return [dict(r) for r in conn.execute(
            "SELECT * FROM llm_calls WHERE account_id IS NOT DISTINCT FROM %s "
            "ORDER BY id DESC LIMIT %s",
            (account_id, limit))]
