"""
Human feedback on prompts -- BOTH directions. The automatic loops can't
capture your hand judgment: promote_winners promotes concepts by
analytics, generative tracks render attempts. This lets you say, by hand,
per prompt:

  - "this WORKED" -> embedded into the RAG 'winning_prompts' shelf so
    future generations imitate your proven phrasing, and
  - "this DIDN'T work (+ why)" -> embedded into the RAG 'avoid_prompts'
    shelf AND surfaced as a negative steer the generator is told to avoid.

add() persists durably in the pipeline database (never lost if the RAG
store is down; Postgres since 2026-09-03, `dsn` where it took `path`);
ingest_to_rag() teaches it to the right shelf by verdict. Same shape as
autonomy.py/entities.py: own SCHEMA, own init(), one shared database.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from . import db

DOMAIN = "winning_prompts"        # the "worked" shelf shootgen grounds on
AVOID_DOMAIN = "avoid_prompts"    # the "didn't work" shelf -> negative steer

SCHEMA = """
CREATE TABLE IF NOT EXISTS winning_prompts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    tool       TEXT NOT NULL DEFAULT 'runway',   -- runway | midjourney
    prompt     TEXT NOT NULL,                     -- the final, edited prompt text
    note       TEXT,                              -- why it worked / why it failed
    video_ref  TEXT,                              -- link/id of the finished piece
    verdict    TEXT NOT NULL DEFAULT 'worked',    -- worked | didnt_work
    pair_id    BIGINT,                            -- the other half of a fix pair
    rag_source TEXT,
    ingested   INTEGER NOT NULL DEFAULT 0
);
"""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _norm_verdict(v) -> str:
    v = str(v or "worked").strip().lower()
    return "didnt_work" if v.startswith(("didn", "no", "fail", "bad")) else "worked"


def init(dsn=None) -> None:
    with db.connect(dsn) as conn:
        conn.execute(SCHEMA)


def add(tool, prompt, note="", video_ref="", verdict="worked", dsn=None) -> int:
    prompt = (prompt or "").strip()
    if not prompt:
        raise ValueError("a prompt cannot be empty")
    init(dsn)   # same on-demand guard list_all and avoid_guidance use
    with db.connect(dsn) as conn:
        row = conn.execute(
            "INSERT INTO winning_prompts (created_at, tool, prompt, note, "
            "video_ref, verdict) VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
            (_now(), (tool or "runway").strip().lower(), prompt,
             (note or "").strip(), (video_ref or "").strip(), _norm_verdict(verdict))
        ).fetchone()
        return int(row["id"])


def get(entry_id, dsn=None):
    with db.connect(dsn) as conn:
        row = conn.execute(
            "SELECT * FROM winning_prompts WHERE id = %s", (entry_id,)).fetchone()
        return dict(row) if row else None


def list_all(dsn=None) -> list:
    # ensure the table exists before querying, same as avoid_guidance:
    # this is read on every Grade/Graded render to work out which
    # concepts carry a verdict, and a database that has not seen a
    # verdict yet should read as "none", not raise (2026-09-02).
    init(dsn)
    with db.connect(dsn) as conn:
        return [dict(r) for r in conn.execute(
            "SELECT * FROM winning_prompts ORDER BY created_at DESC")]


def _render_doc(w: dict, pair: dict | None = None) -> str:
    """One entry as the text that gets embedded. A paired entry carries
    the OTHER half in its own document: the lesson in "this failed, this
    worked instead" is the contrast between them, and a doc holding only
    one side can't teach it -- retrieval hits one chunk, not both."""
    if w.get("verdict") == "didnt_work":
        lines = [f"AVOID -- a {w['tool'].upper()} prompt that DID NOT work. "
                 "Do not imitate this; steer away from what made it fail."]
        if w.get("note"):
            lines.append(f"Why it failed: {w['note']}")
        lines.append(f"Failed prompt: {w['prompt']}")
        if pair:
            lines.append("What was written instead, and DID work -- prefer this "
                         f"shape: {pair['prompt']}")
        return "\n".join(lines)
    lines = [f"WINNING {w['tool'].upper()} PROMPT -- your own proven record; "
             "match this phrasing and style when it fits the shot."]
    if w.get("note"):
        lines.append(f"Why it won: {w['note']}")
    if w.get("video_ref"):
        lines.append(f"Finished piece: {w['video_ref']}")
    lines.append(f"Prompt: {w['prompt']}")
    if pair:
        lines.append("This was the FIX for an attempt that failed. The failed "
                     f"version, for contrast: {pair['prompt']}")
    return "\n".join(lines)


def ingest_to_rag(entry_id, dsn=None, project: Optional[str] = None) -> dict:
    """Embed the entry into the right RAG shelf by verdict (winning_prompts
    or avoid_prompts). Never raises -- if the store is down it stays saved
    and can be re-ingested. `project` is the teaching tenant's slug
    (src/rag.py), so their own lessons rank first for them."""
    w = get(entry_id, dsn=dsn)
    if not w:
        return {"ok": False, "error": "no such entry"}
    pair = get(w["pair_id"], dsn=dsn) if w.get("pair_id") else None
    domain = AVOID_DOMAIN if w.get("verdict") == "didnt_work" else DOMAIN
    try:
        from . import rag
        source = f"{domain}/entry-{entry_id}.txt"
        client = rag.make_client()
        conn = rag.connect()
        try:
            rag.init_store(conn)
            written = rag.ingest_records(
                [{"source": source, "text": _render_doc(w, pair), "domain": domain,
                  "project": project,
                  "source_ref": w.get("video_ref") or None}], client, conn)
        finally:
            conn.close()
        with db.connect(dsn) as c:
            c.execute("UPDATE winning_prompts SET ingested = 1, rag_source = %s "
                      "WHERE id = %s", (source, entry_id))
        return {"ok": True, "chunks": written}
    except Exception as e:
        return {"ok": False, "error": str(e)}


def pending(video_ref: str, dsn=None) -> list[dict]:
    """This subject's recorded-but-not-yet-embedded entries.

    `ingest` was always separable from `add` -- ingest_to_rag takes an id
    and the row carries an `ingested` flag precisely so a store that is
    down loses nothing. This exposes the other half of that contract: a
    verdict can be RECORDED now and TAUGHT later, which is what lets a
    concept sit on the Graded tab carrying your verdict before the
    scoring pass ingests it (2026-09-02).
    """
    init(dsn)   # on-demand guard, same as list_all and add
    with db.connect(dsn) as conn:
        return [dict(r) for r in conn.execute(
            "SELECT * FROM winning_prompts WHERE video_ref = %s AND ingested = 0 "
            "ORDER BY id", ((video_ref or "").strip(),))]


def recorded(video_ref: str, dsn=None) -> list[dict]:
    """Every entry filed against this subject, ingested or not."""
    init(dsn)   # on-demand guard, same as list_all and add
    with db.connect(dsn) as conn:
        return [dict(r) for r in conn.execute(
            "SELECT * FROM winning_prompts WHERE video_ref = %s ORDER BY id",
            ((video_ref or "").strip(),))]


def discard_pending(video_ref: str, dsn=None) -> int:
    """Drop this subject's not-yet-embedded entries, and return how many.

    The ONLY safe deletion in this table, and only because of what
    `ingested = 0` means: nothing has reached the RAG shelves, so there is
    no lesson to unteach. Used when a board pass is undone -- putting a
    card back on the board must take its deny with it, or the shelves
    learn from a decision that was reversed. An ingested row is never
    touched here (2026-09-02).
    """
    init(dsn)   # on-demand guard, same as list_all and add
    with db.connect(dsn) as conn:
        cur = conn.execute(
            "DELETE FROM winning_prompts WHERE video_ref = %s AND ingested = 0",
            ((video_ref or "").strip(),))
        return cur.rowcount


def ingest_pending(video_ref: str, dsn=None) -> dict:
    """Embed everything still waiting for this subject. Best-effort, the
    standing contract: a failure leaves the rows saved and re-ingestable,
    and the caller can tell because `ok` is False."""
    rows = pending(video_ref, dsn=dsn)
    errors = []
    done = 0
    for r in rows:
        result = ingest_to_rag(r["id"], dsn=dsn)
        if result.get("ok"):
            done += 1
        else:
            errors.append(result.get("error") or "store unavailable")
    return {"ok": not errors, "ingested": done, "pending": len(rows),
            "error": errors[0] if errors else None}


def record_and_learn(tool, prompt, note="", video_ref="", verdict="worked",
                     dsn=None, project: Optional[str] = None,
                     ingest: bool = True) -> dict:
    """Record one verdict. `ingest=False` records it and stops -- see
    pending() for why the two halves are separable."""
    entry_id = add(tool, prompt, note=note, video_ref=video_ref,
                   verdict=verdict, dsn=dsn)
    if not ingest:
        return {"id": entry_id, "verdict": _norm_verdict(verdict),
                "ingested": False, "deferred": True, "error": None}
    result = ingest_to_rag(entry_id, dsn=dsn, project=project)
    return {"id": entry_id, "verdict": _norm_verdict(verdict),
            "ingested": result.get("ok", False), "error": result.get("error")}


def record_pair(tool, failed_prompt, working_prompt, note="", video_ref="",
                dsn=None, project: Optional[str] = None,
                ingest: bool = True) -> dict:
    """
    The strongest feedback shape there is: "this one failed, and THIS is
    what I wrote instead that worked."

    Two rows, linked both ways, landing on both shelves -- the failure on
    avoid_prompts and the fix on winning_prompts -- with each document
    naming the other. Recording only the failure teaches what to run from
    without saying where to run to; recording only the fix throws away the
    contrast that makes it legible.

    Ingest is best-effort per half, the standing contract: a store that
    dies between the two writes leaves both rows saved and re-ingestable
    rather than losing the label.
    """
    failed_prompt = (failed_prompt or "").strip()
    working_prompt = (working_prompt or "").strip()
    if not working_prompt:
        raise ValueError("record_pair needs the prompt that actually worked")
    failed_id = add(tool, failed_prompt, note=note, video_ref=video_ref,
                    verdict="didnt_work", dsn=dsn)
    worked_id = add(tool, working_prompt, note=note, video_ref=video_ref,
                    verdict="worked", dsn=dsn)
    with db.connect(dsn) as conn:
        conn.execute("UPDATE winning_prompts SET pair_id = %s WHERE id = %s",
                     (worked_id, failed_id))
        conn.execute("UPDATE winning_prompts SET pair_id = %s WHERE id = %s",
                     (failed_id, worked_id))
    if not ingest:
        return {"id": worked_id, "failed_id": failed_id, "worked_id": worked_id,
                "verdict": "pair", "paired": True, "ingested": False,
                "deferred": True, "error": None}
    failed_result = ingest_to_rag(failed_id, dsn=dsn, project=project)
    worked_result = ingest_to_rag(worked_id, dsn=dsn, project=project)
    return {
        "id": worked_id, "failed_id": failed_id, "worked_id": worked_id,
        "verdict": "pair", "paired": True,
        "ingested": bool(failed_result.get("ok") and worked_result.get("ok")),
        "error": failed_result.get("error") or worked_result.get("error"),
    }


def avoid_guidance(limit=8, dsn=None) -> str:
    """A negative-steer block from prompts you marked 'didn't work', folded
    into generation so the next batch avoids repeating them. '' when none."""
    try:
        init(dsn)  # ensure the table + verdict column exist before querying
        with db.connect(dsn) as conn:
            rows = [dict(r) for r in conn.execute(
                "SELECT tool, note FROM winning_prompts WHERE verdict = 'didnt_work' "
                "ORDER BY created_at DESC LIMIT %s", (limit,))]
    except Exception:
        return ""   # negative steer is best-effort; never block a generation
    if not rows:
        return ""
    lines = ["AVOID what has failed before (do not repeat these):"]
    for r in rows:
        why = f" — {r['note']}" if r.get("note") else ""
        lines.append(f"- [{(r.get('tool') or 'runway')}]{why}")
    return "\n".join(lines)
