"""Copy data/pipeline.db (SQLite) into the Postgres database -- once.

The migration (docs/tasks/task-postgres-migration.md) moved the CODE off
SQLite on 2026-09-03; this is the one-off that moves the DATA. It reads
the SQLite file with the standard library, builds every module's schema
on the target by calling the same init() the app lifespan calls, and
copies table by table in the order the target's own foreign keys
dictate, ids preserved (identity columns are GENERATED BY DEFAULT for
exactly this reason). Then it resets every identity sequence past the
highest id it copied, and prints source-vs-target row counts.

Three things it does on purpose:

- **Users land unclaimed.** Identity is Supabase Auth's now (step 6):
  `users.id` is the auth.users UUID once a person has signed in, and a
  placeholder before. Every SQLite user (integer id, argon2 hash) becomes
  a placeholder-uuid row with claimed_at NULL, and account_members follows
  through the same map -- so each person's FIRST Supabase sign-in with
  that email claims their row and memberships (accounts.claim). No
  re-invite. password_hash and auth_identities are not copied; Supabase
  holds those the moment the person signs in there.
- **The seeds lose to the file.** autonomy.init seeds channels,
  inspiration.init seeds the researched accounts, evalstore.init seeds the
  golden set; the SQLite file holds the REAL rows (Zero Page's channel is
  `queue`, not the seed's `shadow`). Every table is truncated after the
  inits and before the copy.
- **It refuses a target that already holds rows** unless --truncate says
  so. A copy on top of a copy is duplicate ids at best and a mangled
  history at worst; the check happens before anything is created.

    venv/bin/python -m ops.copy_sqlite_to_postgres --dsn postgresql://... \
        [--sqlite data/pipeline.db] [--dry-run] [--truncate]

`--dsn` (or DATABASE_URL) is required: this script never falls through
to the compose default, because the one thing it must not do is copy a
production file into the throwaway test box by accident.
"""
from __future__ import annotations

import argparse
import importlib
import os
import pathlib
import sqlite3
import sys
import uuid
from typing import Optional

import psycopg

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src import accounts, db  # noqa: E402

# Tables the target no longer has, and why. Anything else in the SQLite
# file that the target lacks is reported and skipped -- a module that
# was deleted, or a table this script has not heard of.
DROPPED = {
    "auth_identities": "identities are Supabase Auth's (step 6)",
    "sqlite_sequence": "SQLite's own bookkeeping",
}
# Columns the target no longer has.
DROPPED_COLUMNS = {
    "users": {"password_hash": "passwords are Supabase Auth's (step 6)"},
}


def init_all(dsn: str) -> list[str]:
    """Every schema owner's init(), the way the app lifespan does it:
    db first (accounts is its FK target), then each src module that owns
    a SCHEMA. Returns the module names that ran."""
    db.init_db(dsn)
    accounts.init(dsn)
    ran = ["db", "accounts"]
    for path in sorted((ROOT / "src").glob("*.py")):
        name = path.stem
        if name in ("db", "accounts", "rag", "rag_eval") or name.startswith("_"):
            continue
        text = path.read_text()
        if "SCHEMA = " not in text or "def init(" not in text:
            continue
        module = importlib.import_module(f"src.{name}")
        module.init(dsn)
        ran.append(name)
    return ran


def pipeline_tables() -> set[str]:
    """The tables this script may read, count, truncate or write: the
    tenancy ledger (every pipeline table is OWNED or declared SHARED --
    tests/test_tenancy.py fails on one that is neither) plus the auth
    tables. Anything else living in the target schema is somebody
    else's -- on the Supabase project that is `rag_documents`, the RAG
    library, which shares the `public` schema and must never be
    truncated by a data copy that has no business with it."""
    return set(db.OWNED_TABLES) | set(db.SHARED_TABLES) | {"users", "accounts", "account_members"}


def target_tables(conn) -> list[str]:
    """The pipeline tables that exist on the target, and only those."""
    present = [r[0] for r in conn.execute(
        "SELECT table_name FROM information_schema.tables "
        "WHERE table_schema = current_schema() AND table_type = 'BASE TABLE' "
        "ORDER BY table_name")]
    return [t for t in present if t in pipeline_tables()]


def target_columns(conn, table: str) -> list[str]:
    return [r[0] for r in conn.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema = current_schema() AND table_name = %s "
        "ORDER BY ordinal_position", (table,))]


def fk_order(conn, tables: list[str]) -> list[str]:
    """Parents before children, from the target's own constraints."""
    edges = conn.execute(
        "SELECT c.conrelid::regclass::text, c.confrelid::regclass::text "
        "FROM pg_constraint c JOIN pg_namespace n ON n.oid = c.connamespace "
        "WHERE c.contype = 'f' AND n.nspname = current_schema()").fetchall()
    deps: dict[str, set] = {t: set() for t in tables}
    for child, parent in edges:
        child, parent = child.strip('"'), parent.strip('"')
        if child in deps and parent in deps and child != parent:
            deps[child].add(parent)
    ordered: list[str] = []
    while deps:
        ready = sorted(t for t, ps in deps.items() if not ps)
        if not ready:
            raise RuntimeError(f"foreign-key cycle among {sorted(deps)}")
        ordered.extend(ready)
        for t in ready:
            deps.pop(t)
        for ps in deps.values():
            ps.difference_update(ready)
    return ordered


def rows_in(conn, table: str) -> int:
    return conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]


def copy(sqlite_path: pathlib.Path, dsn: str, *, dry_run: bool = False,
         truncate: bool = False, out=sys.stdout) -> dict:
    src = sqlite3.connect(f"file:{sqlite_path}?mode=ro", uri=True)
    src.row_factory = sqlite3.Row
    source_tables = [r[0] for r in src.execute(
        "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name")]
    counts = {t: src.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
              for t in source_tables if t not in DROPPED}

    # the refusal happens before a single CREATE TABLE; foreign tables in
    # the same schema (the RAG library on Supabase) are neither counted
    # here nor touched below
    with psycopg.connect(dsn) as probe:
        existing = target_tables(probe)
        occupied = {t: rows_in(probe, t) for t in existing}
        occupied = {t: n for t, n in occupied.items() if n}
        foreign = [r[0] for r in probe.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = current_schema() AND table_type = 'BASE TABLE'")
            if r[0] not in pipeline_tables()]
    if foreign:
        print(f"leaving alone: {sorted(foreign)} (not pipeline tables)", file=out)
    if occupied and not truncate:
        raise SystemExit(
            f"refusing: the target already holds rows in {sorted(occupied)} -- "
            "pass --truncate to replace them, or point at an empty database")

    if dry_run:
        print(f"dry run: {sum(counts.values())} rows in {len(counts)} tables would be copied "
              f"from {sqlite_path}", file=out)
        for t, n in counts.items():
            print(f"  {t:24} {n:6}", file=out)
        for t, why in DROPPED.items():
            if t in source_tables:
                print(f"  {t:24} dropped: {why}", file=out)
        return {"dry_run": True, "counts": counts}

    ran = init_all(dsn)
    print(f"schema: {len(ran)} modules initialised on the target", file=out)

    user_map: dict = {}
    report: dict = {}
    with psycopg.connect(dsn) as conn:
        tables = target_tables(conn)
        order = fk_order(conn, tables)
        # the seeds lose to the file
        conn.execute("TRUNCATE " + ", ".join(tables) + " RESTART IDENTITY CASCADE")

        for table in order:
            if table not in source_tables:
                report[table] = ("not in the SQLite file", 0, 0)
                continue
            tcols = target_columns(conn, table)
            scols = [r[1] for r in src.execute(f"PRAGMA table_info({table})")]
            dropped = set(DROPPED_COLUMNS.get(table, {}))
            cols = [c for c in scols if c in tcols and c not in dropped]
            missing = [c for c in scols if c not in tcols and c not in dropped]
            if missing:
                print(f"  note: {table}: SQLite columns the target lacks, skipped: {missing}",
                      file=out)
            rows = src.execute(f"SELECT {', '.join(cols)} FROM {table}").fetchall()
            values = []
            for r in rows:
                rec = dict(zip(cols, r))
                if table == "users":
                    # placeholder id, unclaimed: the first Supabase sign-in
                    # with this email rewrites it to the real auth.users id
                    user_map[rec["id"]] = str(uuid.uuid4())
                    rec["id"] = user_map[rec["id"]]
                    rec["claimed_at"] = None
                elif table == "account_members":
                    rec["user_id"] = user_map.get(rec["user_id"], rec["user_id"])
                values.append(tuple(rec.get(c) for c in cols))
            if table == "users" and "claimed_at" in tcols and "claimed_at" not in cols:
                cols = cols + ["claimed_at"]
                values = [v + (None,) for v in values]
            if values:
                with conn.cursor() as cur:
                    cur.executemany(
                        f"INSERT INTO {table} ({', '.join(cols)}) "
                        f"VALUES ({', '.join(['%s'] * len(cols))})", values)
            # identity sequences must continue past the ids just copied
            if "id" in tcols and table != "users":
                seq = conn.execute("SELECT pg_get_serial_sequence(%s, 'id')", (table,)).fetchone()[0]
                if seq:
                    conn.execute(
                        f"SELECT setval(%s, COALESCE((SELECT MAX(id) FROM {table}), 1), "
                        f"(SELECT MAX(id) FROM {table}) IS NOT NULL)", (seq,))
            report[table] = ("copied", counts.get(table, 0), rows_in(conn, table))

        for t in source_tables:
            if t in DROPPED:
                report[t] = (f"dropped: {DROPPED[t]}", counts.get(t, 0), 0)
            elif t not in tables:
                report[t] = ("NOT IN THE TARGET SCHEMA -- skipped", counts.get(t, 0), 0)

    width = max(len(t) for t in report)
    bad = []
    for t, (state, n_src, n_dst) in report.items():
        flag = "" if (state != "copied" or n_src == n_dst) else "   <-- MISMATCH"
        if flag or state.startswith("NOT IN"):
            bad.append(t)
        print(f"  {t:{width}}  {n_src:6} -> {n_dst:6}  {state}{flag}", file=out)
    print(f"users: {len(user_map)} row(s) copied unclaimed; each claims itself on first "
          "Supabase sign-in with the same email", file=out)
    if bad:
        print(f"CHECK: {bad}", file=out)
    return {"dry_run": False, "report": report, "user_map": user_map, "problems": bad}


def main(argv: Optional[list] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--sqlite", default=str(ROOT / "data" / "pipeline.db"))
    ap.add_argument("--dsn", default=os.environ.get("DATABASE_URL"),
                    help="target Postgres URL (default: DATABASE_URL; never the compose box)")
    ap.add_argument("--dry-run", action="store_true", help="count what would be copied, write nothing")
    ap.add_argument("--truncate", action="store_true",
                    help="replace rows already on the target instead of refusing")
    args = ap.parse_args(argv)
    if not args.dsn:
        print("no target: pass --dsn or set DATABASE_URL", file=sys.stderr)
        return 2
    sqlite_path = pathlib.Path(args.sqlite)
    if not sqlite_path.is_file():
        print(f"no SQLite file at {sqlite_path}", file=sys.stderr)
        return 2
    result = copy(sqlite_path, args.dsn, dry_run=args.dry_run, truncate=args.truncate)
    return 1 if result.get("problems") else 0


if __name__ == "__main__":
    raise SystemExit(main())
